In [2]:
# pip install jupysql
# %pip install psycopg2-binary
%config SqlMagic.displaylimit = 100

In [3]:
%reload_ext sql
%sql postgresql://postgres:232323@localhost:5432/nepo

Connecting to 'postgresql://postgres:***@localhost:5432/nepo'

In [3]:
%%sql

select * from core.person limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

10 rows affected.

+------------+------------------+--------+------------+-----------+
| person_id  |       name       | gender | birthdate  |   nconst  |
+------------+------------------+--------+------------+-----------+
|  Q1000290  |   Tracy Adams    |  male  | 2000-01-01 | nm0011410 |
|  Q1000366  | Bucky Pizzarelli |  male  | 1926-01-09 | nm0686199 |
|  Q1000408  |  Larry Augustin  |  male  | 1962-10-01 | nm1128064 |
| Q100043539 |  Stuart Samuels  |  male  |    None    | nm0760523 |
|  Q1000471  |    Bud Fisher    |  male  | 1884-04-03 | nm0279404 |
|  Q1000491  |   Bud Collins    |  male  | 1929-06-17 | nm1460775 |
|  Q1000498  |  Bud Greenspan   |  male  | 1926-09-18 | nm0339175 |
|  Q1000505  |     Bud Lee      |  male  | 1955-09-30 | nm0496928 |
|  Q1000549  |   Bud Thackery   |  male  | 1903-01-31 | nm0856844 |
|  Q100074   |  Jessie Diggins  | female | 1991-08-26 | nm6257704 |
+------------+------------------+--------+------------+-----------+
Truncated to displaylimit of 10.

## DDL Core.mapkinship

In [111]:
%%sql
-- ============================================================
-- core.mapkinship v2
-- Aligned with vector-based kinship labels from core_kinship_v2
--
-- Role of this table:
--   1. Seeds for relationships that CAN be structurally inferred
--      (grandfather, uncle etc.) — used as fallback if parent
--      edges are missing from Wikidata
--   2. Primary source for relationships that CANNOT be inferred
--      from parent edges alone (in-laws, godparents, relatives)
-- ============================================================

DROP TABLE IF EXISTS core.mapkinship CASCADE;

CREATE TABLE IF NOT EXISTS core.mapkinship (
    relationship VARCHAR(100) PRIMARY KEY,
    kinship      VARCHAR(30)  NOT NULL   -- matches v2 labels
);

INSERT INTO core.mapkinship (relationship, kinship) VALUES

-- ── PARENT (gen=+1, deg=0) ────────────────────────────────────────────────
('father',                                        'PARENT'),
('mother',                                        'PARENT'),
('biological father',                             'PARENT'),
('adoptive father',                               'PARENT'),
('adoptive mother',                               'PARENT'),
('adoptive parent',                               'PARENT'),

-- ── GRANDPARENT (gen=+2, deg=0) ───────────────────────────────────────────
('grandfather',                                   'GRANDPARENT'),
('grandmother',                                   'GRANDPARENT'),
('paternal grandfather',                          'GRANDPARENT'),
('paternal grandmother',                          'GRANDPARENT'),
('maternal grandfather',                          'GRANDPARENT'),
('maternal grandmother',                          'GRANDPARENT'),
('grandparent',                                   'GRANDPARENT'),

-- ── ANCESTOR (gen=+3, deg=0) ──────────────────────────────────────────────
('great-grandfather',                             'ANCESTOR'),
('great-grandmother',                             'ANCESTOR'),
('great-great-grandfather',                       'ANCESTOR'),
('great-great-grandmother',                       'ANCESTOR'),
('great-great-grandparent',                       'ANCESTOR'),
('great-great-great-grandfather',                 'ANCESTOR'),
('great-great-great-grandmother',                 'ANCESTOR'),
('maternal great-grandfather',                    'ANCESTOR'),
('maternal great-grandparent',                    'ANCESTOR'),
('paternal great-grandparent',                    'ANCESTOR'),
('paternal grandfather''s father',                'ANCESTOR'),
('father''s father''s father''s father',          'ANCESTOR'),
('father''s father''s father''s mother',          'ANCESTOR'),
('father''s mother''s father',                    'ANCESTOR'),
('mother''s mother''s mother',                    'ANCESTOR'),
('mother''s mother''s father',                    'ANCESTOR'),
('maternal grandfather''s brother',               'ANCESTOR'),
('4th great-grandfather',                         'ANCESTOR'),
('6th great-grandfather',                         'ANCESTOR'),
('15th great-grandparent',                        'ANCESTOR'),
('ancestor',                                      'ANCESTOR'),
('progenitor',                                    'ANCESTOR'),

-- ── SIBLING (gen=0, deg=1) ────────────────────────────────────────────────
('brother',                                       'SIBLING'),
('sister',                                        'SIBLING'),
('half-brother',                                  'SIBLING'),
('half-sister',                                   'SIBLING'),
('twin brother',                                  'SIBLING'),
('elder brother',                                 'SIBLING'),
('younger brother',                               'SIBLING'),
('younger sister',                                'SIBLING'),
('blood brother',                                 'SIBLING'),
('adoptive brother',                              'SIBLING'),
('adoptive sister',                               'SIBLING'),
('paternal half-brother',                         'SIBLING'),
('paternal half-sister',                          'SIBLING'),
('maternal half-brother',                         'SIBLING'),
('maternal half-sister',                          'SIBLING'),
('sibling',                                       'SIBLING'),

-- ── CHILD (gen=-1, deg=0) ─────────────────────────────────────────────────
('son',                                           'CHILD'),
('daughter',                                      'CHILD'),
('adopted son',                                   'CHILD'),
('adopted daughter',                              'CHILD'),
('adopted child',                                 'CHILD'),
('godson',                                        'CHILD'),
('goddaughter',                                   'CHILD'),
('godchild',                                      'CHILD'),
('son of stepfather',                             'CHILD'),

-- ── GRANDCHILD (gen=-2, deg=0) ────────────────────────────────────────────
('grandson',                                      'GRANDCHILD'),
('granddaughter',                                 'GRANDCHILD'),
('grandchild',                                    'GRANDCHILD'),
('stepgrandson',                                  'GRANDCHILD'),
('stepgranddaughter',                             'GRANDCHILD'),

-- ── DESCENDANT (gen<=-3, deg=0) ───────────────────────────────────────────
('great-grandson',                                'DESCENDANT'),
('great-granddaughter',                           'DESCENDANT'),
('great-great-granddaughter',                     'DESCENDANT'),
('son''s son',                                    'DESCENDANT'),
('son''s daughter',                               'DESCENDANT'),
('daughter''s son',                               'DESCENDANT'),
('daughter''s daughter',                          'DESCENDANT'),

-- ── AUNT_UNCLE (gen=+1, deg=1) ────────────────────────────────────────────
('uncle',                                         'AUNT_UNCLE'),
('aunt',                                          'AUNT_UNCLE'),
('father''s brother',                             'AUNT_UNCLE'),
('father''s sister',                              'AUNT_UNCLE'),
('father''s younger brother',                     'AUNT_UNCLE'),
('mother''s brother',                             'AUNT_UNCLE'),
('mother''s sister',                              'AUNT_UNCLE'),
('parent''s brother',                             'AUNT_UNCLE'),
('parent''s sister',                              'AUNT_UNCLE'),
('paternal half-uncle',                           'AUNT_UNCLE'),
('second uncle',                                  'AUNT_UNCLE'),
('second aunt',                                   'AUNT_UNCLE'),

-- ── GREAT_AUNT_UNCLE (gen=+2, deg=1) — NEW in v2 ─────────────────────────
('granduncle',                                    'GREAT_AUNT_UNCLE'),
('grandaunt',                                     'GREAT_AUNT_UNCLE'),
('grandaunt or granduncle',                       'GREAT_AUNT_UNCLE'),
('great-uncle',                                   'GREAT_AUNT_UNCLE'),
('great-aunt',                                    'GREAT_AUNT_UNCLE'),
('great-granduncle',                              'GREAT_AUNT_UNCLE'),
('great-great-granduncle',                        'GREAT_AUNT_UNCLE'),
('paternal great-grandmother',                    'GREAT_AUNT_UNCLE'),  -- legacy mismap

-- ── NIECE_NEPHEW (gen=-1, deg=1) ─────────────────────────────────────────
('nephew',                                        'NIECE_NEPHEW'),
('niece',                                         'NIECE_NEPHEW'),
('fraternal nephew',                              'NIECE_NEPHEW'),
('fraternal niece',                               'NIECE_NEPHEW'),
('sororal nephew',                                'NIECE_NEPHEW'),
('sororal niece',                                 'NIECE_NEPHEW'),
('paternal nephew',                               'NIECE_NEPHEW'),
('maternal nephew',                               'NIECE_NEPHEW'),
('maternal niece',                                'NIECE_NEPHEW'),
('niece-in-law',                                  'NIECE_NEPHEW'),

-- ── GREAT_NIECE_NEPHEW (gen=-2, deg=1) — NEW in v2 ───────────────────────
('great-nephew',                                  'GREAT_NIECE_NEPHEW'),
('great-niece',                                   'GREAT_NIECE_NEPHEW'),
('great-grandniece',                              'GREAT_NIECE_NEPHEW'),
('second nephew',                                 'GREAT_NIECE_NEPHEW'),
('second niece',                                  'GREAT_NIECE_NEPHEW'),

-- ── COUSIN_1ST (gen=0, deg=2) — NEW granular labels in v2 ────────────────
('cousin',                                        'COUSIN_1ST'),
('first cousin',                                  'COUSIN_1ST'),
('male cousin',                                   'COUSIN_1ST'),
('female cousin',                                 'COUSIN_1ST'),
('male first cousin',                             'COUSIN_1ST'),
('female first cousin',                           'COUSIN_1ST'),
('maternal cousin',                               'COUSIN_1ST'),
('paternal cousin',                               'COUSIN_1ST'),
('maternal first cousin',                         'COUSIN_1ST'),
('male paternal parallel cousin',                 'COUSIN_1ST'),
('female paternal parallel cousin',               'COUSIN_1ST'),
('female parallel cousin',                        'COUSIN_1ST'),
('biaojie',                                       'COUSIN_1ST'),
('"child of a sibling aunt or uncle"',            'COUSIN_1ST'),

-- ── COUSIN_1ST_1R (gen=±1, deg=2) ────────────────────────────────────────
('first cousin once removed descending',          'COUSIN_1ST_1R_DOWN'),
('second cousin once removed ascending',          'COUSIN_2ND_1R_UP'),
('second cousin once removed descending',         'COUSIN_2ND_1R_DOWN'),

-- ── COUSIN_2ND (gen=0, deg=3) ─────────────────────────────────────────────
('second cousin',                                 'COUSIN_2ND'),
('male second cousin',                            'COUSIN_2ND'),
('female second cousin',                          'COUSIN_2ND'),

-- ── COUSIN (catch-all for unmapped cousin variants) ───────────────────────
('third cousin',                                  'RELATIVE'),
('fourth cousin',                                 'RELATIVE'),
('sixth cousin 4 times removed descending',       'RELATIVE'),
('cousin-in-law',                                 'RELATIVE'),

-- ── IN-LAWS (not structurally inferable — primary source) ─────────────────
('father-in-law',                                 'PARENT_INLAW'),
('mother-in-law',                                 'PARENT_INLAW'),
('stepfather-in-law',                             'PARENT_INLAW'),
('stepmother-in-law',                             'PARENT_INLAW'),
('grandfather-in-law',                            'PARENT_INLAW'),
('wife''s father',                                'PARENT_INLAW'),
('wife''s mother',                                'PARENT_INLAW'),
('husband''s father',                             'PARENT_INLAW'),
('husband''s mother',                             'PARENT_INLAW'),
('son-in-law',                                    'CHILD_INLAW'),
('daughter-in-law',                               'CHILD_INLAW'),
('child-in-law',                                  'CHILD_INLAW'),
('brother-in-law',                                'SIBLING_INLAW'),
('sister-in-law',                                 'SIBLING_INLAW'),
('sibling-in-law',                                'SIBLING_INLAW'),
('brother''s wife',                               'SIBLING_INLAW'),
('sister''s husband',                             'SIBLING_INLAW'),
('husband''s brother',                            'SIBLING_INLAW'),
('husband''s sister',                             'SIBLING_INLAW'),
('wife''s sister',                                'SIBLING_INLAW'),
('husband of sister of husband',                  'SIBLING_INLAW'),
('co-brother-in-law',                             'SIBLING_INLAW'),
('wife of mother''s brother',                     'RELATIVE_INLAW'),
('husband of father''s sister',                   'RELATIVE_INLAW'),
('spouse''s uncle',                               'RELATIVE_INLAW'),
('spouse''s aunt',                                'RELATIVE_INLAW'),
('fiancé',                                        'RELATIVE_INLAW'),

-- ── RELATIVE (catch-all) ──────────────────────────────────────────────────
('godfather',                                     'RELATIVE'),
('godmother',                                     'RELATIVE'),
('nurture kinship',                               'RELATIVE'),
('distant relative',                              'RELATIVE'),
('relative',                                      'RELATIVE'),

-- ── SPOUSE (used to infer step-relationships) ───────────────────────────
('spouse',                                        'SPOUSE'),
('wife',                                          'SPOUSE'),
('husband',                                       'SPOUSE'),
('partner',                                       'SPOUSE'),
('ex-wife',                                       'SPOUSE'),
('ex-husband',                                    'SPOUSE'),
('ex-spouse',                                     'SPOUSE'),
('domestic partner',                              'SPOUSE'),
('civil partner',                                 'SPOUSE'),

-- ── STEPPARENT / STEPCHILD (explicit Wikidata labels) ────────────────────
('stepfather',                                    'STEPPARENT'),
('stepmother',                                    'STEPPARENT'),
('stepson',                                       'STEPCHILD'),
('stepdaughter',                                  'STEPCHILD'),
('stepchild',                                     'STEPCHILD'),
('stepbrother',                                   'STEPSIBLING'),
('stepsister',                                    'STEPSIBLING'),

-- ── UNKNOWN (noise / data quality issues) ────────────────────────────────
('witness',                                       'UNKNOWN'),
('first course',                                  'UNKNOWN'),
('q111323925',                                    'UNKNOWN'),
('q10082309',                                     'UNKNOWN');

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

183 rows affected.

++
||
++
++

## DDL core.kinship

### restart

In [1]:
%reload_ext sql
%sql postgresql://postgres:232323@localhost:5432/nepo

Connecting to 'postgresql://postgres:***@localhost:5432/nepo'

### DDL kinship

In [1]:
%%sql
-- ============================================================
-- core.kinship v2 — Vector-based kinship inference
-- Fixed: split recursive CTE into separate up/lateral/down passes
-- ============================================================


-- ============================================================
-- STEP 1: parent edges
-- ============================================================
DROP TABLE IF EXISTS tmp_parent_edges;
CREATE TEMP TABLE tmp_parent_edges AS
SELECT
    r.person_id,
    r.related_person_id AS parent_id
FROM core.relationship r
JOIN core.mapkinship mk ON r.relationship = mk.relationship
WHERE mk.kinship = 'PARENT';

CREATE INDEX idx_v2_pe_person ON tmp_parent_edges (person_id);
CREATE INDEX idx_v2_pe_parent ON tmp_parent_edges (parent_id);


-- ============================================================
-- STEP 2: ancestor chain (go UP only, max depth 5)
-- Produces rows: (person_id, ancestor_id, up_steps)
-- ============================================================
DROP TABLE IF EXISTS tmp_up_chain;
CREATE TEMP TABLE tmp_up_chain AS
WITH RECURSIVE up_cte AS (
    SELECT person_id, parent_id AS ancestor_id, 1 AS up_steps
    FROM tmp_parent_edges

    UNION ALL

    SELECT u.person_id, pe.parent_id AS ancestor_id, u.up_steps + 1
    FROM up_cte u
    JOIN tmp_parent_edges pe ON pe.person_id = u.ancestor_id
    WHERE u.up_steps < 5
)
SELECT DISTINCT person_id, ancestor_id, up_steps FROM up_cte;

CREATE INDEX idx_v2_uc_person   ON tmp_up_chain (person_id);
CREATE INDEX idx_v2_uc_ancestor ON tmp_up_chain (ancestor_id);
CREATE INDEX idx_v2_uc_steps    ON tmp_up_chain (up_steps);


-- ============================================================
-- STEP 3: lateral edges
-- Two people are lateral (sibling) if they:
--   (a) share at least one direct parent in tmp_parent_edges, OR
--   (b) have an explicit sibling relationship in core.relationship
--       (covers cases where shared parents aren't in the DB)
-- ============================================================
DROP TABLE IF EXISTS tmp_lateral_edges;
CREATE TEMP TABLE tmp_lateral_edges AS

-- (a) structurally inferred: share a parent
SELECT DISTINCT
    p1.person_id    AS person_id,
    p2.person_id    AS lateral_id
FROM tmp_parent_edges p1
JOIN tmp_parent_edges p2
    ON p1.parent_id  = p2.parent_id
    AND p1.person_id <> p2.person_id

UNION

-- (b) explicit sibling from core.relationship
SELECT DISTINCT
    r.person_id,
    r.related_person_id AS lateral_id
FROM core.relationship r
JOIN core.mapkinship mk ON r.relationship = mk.relationship
WHERE mk.kinship = 'SIBLING';

CREATE INDEX idx_v2_le_person  ON tmp_lateral_edges (person_id);
CREATE INDEX idx_v2_le_lateral ON tmp_lateral_edges (lateral_id);


-- ============================================================
-- STEP 3b: spouse edges
-- Seeded from explicit spouse/partner relationships in core.relationship.
-- Used to infer step-relationships.
-- ============================================================
DROP TABLE IF EXISTS tmp_spouse_edges;
CREATE TEMP TABLE tmp_spouse_edges AS
SELECT DISTINCT
    r.person_id,
    r.related_person_id AS spouse_id
FROM core.relationship r
JOIN core.mapkinship mk ON r.relationship = mk.relationship
WHERE mk.kinship = 'SPOUSE';

-- make it bidirectional
INSERT INTO tmp_spouse_edges (person_id, spouse_id)
SELECT spouse_id, person_id FROM tmp_spouse_edges
ON CONFLICT DO NOTHING;

CREATE INDEX idx_v2_sp_person ON tmp_spouse_edges (person_id);
CREATE INDEX idx_v2_sp_spouse ON tmp_spouse_edges (spouse_id);


-- ============================================================
-- STEP 4: build kinship vectors
-- 
-- Canonical path: go UP to LCA → go LATERAL → go DOWN
-- Each combination of (up_steps, lat_steps, down_steps) maps
-- to a unique relationship via:
--   gen_delta = up_steps - down_steps
--   degree    = lat_steps
--   lca_gen   = up_steps
--
-- We enumerate all valid combinations:
--   A. Pure vertical:     lat=0, down = 0..up
--   B. Up + lateral:      up=1..5, lat=1..3, down = 0..up+lat
-- ============================================================
DROP TABLE IF EXISTS tmp_kinship_vectors;
CREATE TEMP TABLE tmp_kinship_vectors AS

-- ── A1. Direct ancestors (up only, no lateral, no down) ──────────────────
SELECT
    uc.person_id,
    uc.ancestor_id          AS related_person_id,
    uc.up_steps - 0         AS gen_delta,
    0                       AS degree,
    uc.up_steps             AS lca_gen
FROM tmp_up_chain uc

UNION ALL

-- ── A2. Direct descendants (reverse of ancestors) ────────────────────────
SELECT
    uc.ancestor_id          AS person_id,
    uc.person_id            AS related_person_id,
    0 - uc.up_steps         AS gen_delta,
    0                       AS degree,
    0                       AS lca_gen
FROM tmp_up_chain uc

UNION ALL

-- ── B1. Same-gen lateral: siblings (up=1, lat=1, down=1) ─────────────────
-- person → up 1 → lateral → down 1 → related
SELECT
    le.person_id,
    le.lateral_id           AS related_person_id,
    0                       AS gen_delta,    -- up=1, down=1
    1                       AS degree,
    1                       AS lca_gen
FROM tmp_lateral_edges le

UNION ALL

-- ── B2a. Up + lateral + down via up_chain ───────────────────────────────
-- person goes up u steps, lateral 1 step, then down d steps
-- Both endpoints reachable via tmp_up_chain (cousins, etc.)
SELECT DISTINCT
    uc1.person_id                  AS person_id,
    uc2.person_id                  AS related_person_id,
    (uc1.up_steps - uc2.up_steps)  AS gen_delta,
    1                              AS degree,
    uc1.up_steps                   AS lca_gen
FROM tmp_up_chain uc1
JOIN tmp_lateral_edges le ON le.person_id   = uc1.ancestor_id
JOIN tmp_up_chain uc2     ON uc2.ancestor_id = le.lateral_id
WHERE uc1.person_id <> uc2.person_id
  AND uc1.up_steps <= 4
  AND uc2.up_steps <= 4

UNION ALL

-- ── B2b. Up + lateral (no down): aunt/uncle with no parent data ───────────
-- person goes up u steps to an ancestor, then lateral to a sibling
-- of that ancestor — the sibling IS the related person (down=0).
-- gen_delta = up_steps (went up u, came down 0), degree = 1
SELECT DISTINCT
    uc.person_id                   AS person_id,
    le.lateral_id                  AS related_person_id,
    uc.up_steps                    AS gen_delta,   -- up=u, down=0
    1                              AS degree,
    uc.up_steps                    AS lca_gen
FROM tmp_up_chain uc
JOIN tmp_lateral_edges le ON le.person_id = uc.ancestor_id
WHERE uc.person_id <> le.lateral_id
  AND uc.up_steps <= 4

UNION ALL

-- ── B2b reverse. Lateral's child → person (NIECE_NEPHEW with no parent data)
-- Bentley→Grace: lateral_id's descendant sees person as niece/nephew target
-- gen_delta = -up_steps (went up 0, effectively down u), degree = 1
SELECT DISTINCT
    le.lateral_id                  AS person_id,
    uc.person_id                   AS related_person_id,
    0 - uc.up_steps                AS gen_delta,   -- down=u, up=0
    1                              AS degree,
    uc.up_steps                    AS lca_gen
FROM tmp_up_chain uc
JOIN tmp_lateral_edges le ON le.person_id = uc.ancestor_id
WHERE uc.person_id <> le.lateral_id
  AND uc.up_steps <= 4

UNION ALL

-- ── B3a. Two lateral hops + down via up_chain (2nd cousins) ─────────────
SELECT DISTINCT
    uc1.person_id                  AS person_id,
    uc2.person_id                  AS related_person_id,
    (uc1.up_steps - uc2.up_steps)  AS gen_delta,
    2                              AS degree,
    uc1.up_steps                   AS lca_gen
FROM tmp_up_chain uc1
JOIN tmp_lateral_edges le1 ON le1.person_id   = uc1.ancestor_id
JOIN tmp_lateral_edges le2 ON le2.person_id   = le1.lateral_id
                           AND le2.lateral_id <> uc1.ancestor_id
JOIN tmp_up_chain uc2      ON uc2.ancestor_id = le2.lateral_id
WHERE uc1.person_id <> uc2.person_id
  AND uc1.up_steps <= 3
  AND uc2.up_steps <= 3

UNION ALL

-- ── B3b. Two lateral hops, no down (cousin with no parent data) ───────────
SELECT DISTINCT
    uc.person_id                   AS person_id,
    le2.lateral_id                 AS related_person_id,
    uc.up_steps                    AS gen_delta,
    2                              AS degree,
    uc.up_steps                    AS lca_gen
FROM tmp_up_chain uc
JOIN tmp_lateral_edges le1 ON le1.person_id   = uc.ancestor_id
JOIN tmp_lateral_edges le2 ON le2.person_id   = le1.lateral_id
                           AND le2.lateral_id <> uc.ancestor_id
WHERE uc.person_id <> le2.lateral_id
  AND uc.up_steps <= 3

UNION ALL

-- ── B3b reverse. Cousin's child → person (cousin once removed, no parent data)
SELECT DISTINCT
    le2.lateral_id                 AS person_id,
    uc.person_id                   AS related_person_id,
    0 - uc.up_steps                AS gen_delta,
    2                              AS degree,
    uc.up_steps                    AS lca_gen
FROM tmp_up_chain uc
JOIN tmp_lateral_edges le1 ON le1.person_id   = uc.ancestor_id
JOIN tmp_lateral_edges le2 ON le2.person_id   = le1.lateral_id
                           AND le2.lateral_id <> uc.ancestor_id
WHERE uc.person_id <> le2.lateral_id
  AND uc.up_steps <= 3

UNION ALL

-- ── S1. Stepparent: person's parent married someone → stepparent ──────────
-- Path: person →(up)→ parent →(spouse)→ stepparent
-- gen_delta = +1, degree = 0, marked via degree=0 but needs label override
-- We use degree=10 as a flag for "step" relationships (not a real geo degree)
SELECT DISTINCT
    uc.person_id                   AS person_id,
    sp.spouse_id                   AS related_person_id,
    uc.up_steps                    AS gen_delta,
    10 + uc.up_steps               AS degree,   -- 10=step flag, +up_steps for gen
    uc.up_steps                    AS lca_gen
FROM tmp_up_chain uc
JOIN tmp_spouse_edges sp ON sp.person_id = uc.ancestor_id
WHERE uc.person_id <> sp.spouse_id
  AND uc.up_steps <= 2            -- stepparent (1) and step-grandparent (2)

UNION ALL

-- ── S1 reverse. Stepchild: stepparent sees person as stepchild ────────────
SELECT DISTINCT
    sp.spouse_id                   AS person_id,
    uc.person_id                   AS related_person_id,
    0 - uc.up_steps                AS gen_delta,
    10 + uc.up_steps               AS degree,
    uc.up_steps                    AS lca_gen
FROM tmp_up_chain uc
JOIN tmp_spouse_edges sp ON sp.person_id = uc.ancestor_id
WHERE uc.person_id <> sp.spouse_id
  AND uc.up_steps <= 2

UNION ALL

-- ── S2. Stepsibling: person's parent's spouse's child ────────────────────
-- Path: person →(up 1)→ parent →(spouse)→ stepparent →(down 1)→ stepsibling
SELECT DISTINCT
    uc1.person_id                  AS person_id,
    uc2.person_id                  AS related_person_id,
    0                              AS gen_delta,   -- same generation
    11                             AS degree,      -- 11 = stepsibling flag
    1                              AS lca_gen
FROM tmp_up_chain uc1
JOIN tmp_spouse_edges sp  ON sp.person_id   = uc1.ancestor_id
JOIN tmp_up_chain uc2     ON uc2.ancestor_id = sp.spouse_id
WHERE uc1.up_steps = 1
  AND uc2.up_steps = 1
  AND uc1.person_id <> uc2.person_id;

CREATE INDEX idx_v2_kv_person  ON tmp_kinship_vectors (person_id);
CREATE INDEX idx_v2_kv_related ON tmp_kinship_vectors (related_person_id);
CREATE INDEX idx_v2_kv_gendeg  ON tmp_kinship_vectors (gen_delta, degree);


-- ============================================================
-- STEP 5: label assignment
-- Pick the closest path per pair, then map (gen_delta, degree)
-- to a kinship label.
-- ============================================================
DROP TABLE IF EXISTS tmp_labeled_kinships;
CREATE TEMP TABLE tmp_labeled_kinships AS
SELECT
    person_id,
    related_person_id,
    gen_delta,
    degree,
    lca_gen,
    CASE
        -- degree 0: direct lineage
        WHEN degree = 0 AND gen_delta =  1 THEN 'PARENT'
        WHEN degree = 0 AND gen_delta = -1 THEN 'CHILD'
        WHEN degree = 0 AND gen_delta =  2 THEN 'GRANDPARENT'
        WHEN degree = 0 AND gen_delta = -2 THEN 'GRANDCHILD'
        WHEN degree = 0 AND gen_delta >=  3 THEN 'ANCESTOR'
        WHEN degree = 0 AND gen_delta <= -3 THEN 'DESCENDANT'

        -- degree 1: sibling line
        WHEN degree = 1 AND gen_delta =  0 THEN 'SIBLING'
        WHEN degree = 1 AND gen_delta =  1 THEN 'AUNT_UNCLE'
        WHEN degree = 1 AND gen_delta = -1 THEN 'NIECE_NEPHEW'
        WHEN degree = 1 AND gen_delta =  2 THEN 'GREAT_AUNT_UNCLE'
        WHEN degree = 1 AND gen_delta = -2 THEN 'GREAT_NIECE_NEPHEW'
        WHEN degree = 1 AND gen_delta >=  3 THEN 'ANCESTOR'
        WHEN degree = 1 AND gen_delta <= -3 THEN 'DESCENDANT'

        -- degree 2: 1st cousins
        WHEN degree = 2 AND gen_delta =  0 THEN 'COUSIN_1ST'
        WHEN degree = 2 AND gen_delta =  1 THEN 'COUSIN_1ST_1R_UP'
        WHEN degree = 2 AND gen_delta = -1 THEN 'COUSIN_1ST_1R_DOWN'
        WHEN degree = 2 AND gen_delta =  2 THEN 'COUSIN_1ST_2R_UP'
        WHEN degree = 2 AND gen_delta = -2 THEN 'COUSIN_1ST_2R_DOWN'
        WHEN degree = 2 AND ABS(gen_delta) >= 3 THEN 'RELATIVE'

        -- degree 3: 2nd cousins (from B3 lateral x2)
        WHEN degree = 3 AND gen_delta =  0 THEN 'COUSIN_2ND'
        WHEN degree = 3 AND gen_delta =  1 THEN 'COUSIN_2ND_1R_UP'
        WHEN degree = 3 AND gen_delta = -1 THEN 'COUSIN_2ND_1R_DOWN'
        WHEN degree = 3 AND ABS(gen_delta) >= 2 THEN 'RELATIVE'

        -- step-relationships (degree 10+ flag)
        WHEN degree = 11                THEN 'STEPSIBLING'
        WHEN degree = 10 AND gen_delta =  1 THEN 'STEPPARENT'
        WHEN degree = 10 AND gen_delta = -1 THEN 'STEPCHILD'
        WHEN degree = 10 AND gen_delta =  2 THEN 'STEP_GRANDPARENT'
        WHEN degree = 10 AND gen_delta = -2 THEN 'STEP_GRANDCHILD'

        ELSE 'RELATIVE'
    END AS kinship
FROM (
    SELECT DISTINCT ON (person_id, related_person_id)
        person_id,
        related_person_id,
        gen_delta,
        degree,
        lca_gen
    FROM tmp_kinship_vectors
    ORDER BY
        person_id,
        related_person_id,
        degree    ASC,
        ABS(gen_delta) ASC,
        lca_gen   ASC
) closest;

CREATE INDEX idx_v2_lk_person  ON tmp_labeled_kinships (person_id);
CREATE INDEX idx_v2_lk_related ON tmp_labeled_kinships (related_person_id);


-- ============================================================
-- STEP 6: explicit non-inferable relationships (in-laws etc.)
-- ============================================================
DROP TABLE IF EXISTS tmp_explicit_kinships;
CREATE TEMP TABLE tmp_explicit_kinships AS
SELECT
    r.person_id,
    r.related_person_id,
    mk.kinship,
    0 AS gen_delta,
    0 AS degree,
    0 AS lca_gen
FROM core.relationship r
JOIN core.mapkinship mk ON r.relationship = mk.relationship
WHERE mk.kinship IN (
    'PARENT_INLAW','CHILD_INLAW','SIBLING_INLAW','RELATIVE_INLAW','RELATIVE',
    'STEPPARENT','STEPCHILD','STEPSIBLING'   -- explicit step-rels override inferred
)
AND NOT EXISTS (
    SELECT 1 FROM tmp_labeled_kinships lk
    WHERE lk.person_id         = r.person_id
      AND lk.related_person_id = r.related_person_id
      AND lk.kinship NOT IN ('RELATIVE')
);


-- ============================================================
-- STEP 7: final insert into core.kinship
-- ============================================================
DROP TABLE IF EXISTS core.kinship CASCADE;

CREATE TABLE core.kinship (
    person_id         VARCHAR(50)  NOT NULL,
    kinship           VARCHAR(30)  NOT NULL,
    related_person_id VARCHAR(50)  NOT NULL,
    gen_delta         SMALLINT,
    degree            SMALLINT,
    lca_gen           SMALLINT,
    PRIMARY KEY (person_id, related_person_id)
);

INSERT INTO core.kinship
    (person_id, kinship, related_person_id, gen_delta, degree, lca_gen)
SELECT person_id, kinship, related_person_id, gen_delta, degree, lca_gen
FROM (
    SELECT
        person_id, kinship, related_person_id, gen_delta, degree, lca_gen,
        ROW_NUMBER() OVER (
            PARTITION BY person_id, related_person_id
            ORDER BY CASE kinship
                WHEN 'PARENT'              THEN 1
                WHEN 'CHILD'               THEN 2
                WHEN 'SIBLING'             THEN 3
                WHEN 'GRANDPARENT'         THEN 4
                WHEN 'GRANDCHILD'          THEN 5
                WHEN 'AUNT_UNCLE'          THEN 6
                WHEN 'NIECE_NEPHEW'        THEN 7
                WHEN 'GREAT_AUNT_UNCLE'    THEN 8
                WHEN 'GREAT_NIECE_NEPHEW'  THEN 9
                WHEN 'COUSIN_1ST'          THEN 10
                WHEN 'COUSIN_1ST_1R_UP'    THEN 11
                WHEN 'COUSIN_1ST_1R_DOWN'  THEN 11
                WHEN 'COUSIN_1ST_2R_UP'    THEN 12
                WHEN 'COUSIN_1ST_2R_DOWN'  THEN 12
                WHEN 'COUSIN_2ND'          THEN 13
                WHEN 'COUSIN_2ND_1R_UP'    THEN 14
                WHEN 'COUSIN_2ND_1R_DOWN'  THEN 14
                WHEN 'ANCESTOR'            THEN 15
                WHEN 'DESCENDANT'          THEN 16
                WHEN 'PARENT_INLAW'        THEN 17
                WHEN 'CHILD_INLAW'         THEN 18
                WHEN 'SIBLING_INLAW'       THEN 19
                WHEN 'RELATIVE_INLAW'      THEN 20
                WHEN 'RELATIVE'            THEN 21
                WHEN 'STEPPARENT'          THEN 22
                WHEN 'STEPCHILD'           THEN 23
                WHEN 'STEPSIBLING'         THEN 24
                WHEN 'STEP_GRANDPARENT'    THEN 25
                WHEN 'STEP_GRANDCHILD'     THEN 26
                ELSE 99
            END
        ) AS rn
    FROM (
        SELECT person_id, kinship, related_person_id, gen_delta, degree, lca_gen
        FROM tmp_labeled_kinships
        UNION ALL
        SELECT person_id, kinship, related_person_id, gen_delta, degree, lca_gen
        FROM tmp_explicit_kinships
    ) combined
    WHERE person_id <> related_person_id
) ranked
WHERE rn = 1;

CREATE INDEX idx_kinship_person_id  ON core.kinship (person_id);
CREATE INDEX idx_kinship_related_id ON core.kinship (related_person_id);
CREATE INDEX idx_kinship_type       ON core.kinship (kinship);
CREATE INDEX idx_kinship_gen_deg    ON core.kinship (gen_delta, degree);


-- ============================================================
-- STEP 8: cleanup
-- ============================================================
DROP TABLE IF EXISTS tmp_parent_edges;
DROP TABLE IF EXISTS tmp_up_chain;
DROP TABLE IF EXISTS tmp_lateral_edges;
DROP TABLE IF EXISTS tmp_spouse_edges;
DROP TABLE IF EXISTS tmp_kinship_vectors;
DROP TABLE IF EXISTS tmp_labeled_kinships;
DROP TABLE IF EXISTS tmp_explicit_kinships;


-- ============================================================
-- VERIFICATION
-- ============================================================
-- SELECT kinship, gen_delta, degree, COUNT(*)
-- FROM core.kinship
-- GROUP BY kinship, gen_delta, degree
-- ORDER BY degree, gen_delta DESC;

UsageError: Cell magic `%%sql` not found.

In [ ]:
%%sql
-- ============================================================
-- TRACE QUERY: verify a specific path (run separately)
-- Example: Grace Van Dien → Bentley Mitchum via Carrie Mitchum
-- ============================================================
-- Step 1: confirm parent edge Grace→Carrie exists
-- SELECT * FROM tmp_parent_edges WHERE person_id = 'Q50400184';
--
-- Step 2: confirm sibling edge Carrie→Bentley exists
-- SELECT * FROM tmp_lateral_edges
-- WHERE person_id = 'Q9184868' AND lateral_id = 'Q4890485';
--
-- Step 3: confirm kinship vector produced
-- SELECT * FROM tmp_kinship_vectors
-- WHERE person_id = 'Q50400184' AND related_person_id = 'Q4890485';
-- Expected: gen_delta=1, degree=1, lca_gen=1 → AUNT_UNCLE
--
-- Step 4: confirm final label
-- SELECT * FROM core.kinship
-- WHERE person_id = 'Q50400184' AND related_person_id = 'Q4890485';

### testing Blake Lively

In [6]:
%%sql
SELECT 
    k.person_id,
    p1.name AS person_name,
    k.kinship,
    k.related_person_id,
    p2.name AS related_person_name
FROM core.kinship k
JOIN core.person p1 ON p1.person_id = k.person_id
JOIN core.person p2 ON p2.person_id = k.related_person_id
WHERE k.person_id = 'Q162959';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

5 rows affected.

+-----------+--------------+---------+-------------------+---------------------+
| person_id | person_name  | kinship | related_person_id | related_person_name |
+-----------+--------------+---------+-------------------+---------------------+
|  Q162959  | Blake Lively | SIBLING |      Q4253117     |     Lori Lively     |
|  Q162959  | Blake Lively |  PARENT |      Q4253122     |     Ernie Lively    |
|  Q162959  | Blake Lively | SIBLING |      Q469891      |     Robyn Lively    |
|  Q162959  | Blake Lively | SIBLING |      Q712936      |     Eric Lively     |
|  Q162959  | Blake Lively | SIBLING |      Q900783      |     Jason Lively    |
+-----------+--------------+---------+-------------------+---------------------+

<!-- Ryan Reynolds (Q192682) -->
<!-- James Reynolds (Q116869845) -->
<!-- Chester Reynolds (Q30460493) -->

In [ ]:
%%sql
SELECT * from core.kinship where person_id = 'Q116869845';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

7 rows affected.

+------------+-------------+-------------------+
| person_id  |   kinship   | related_person_id |
+------------+-------------+-------------------+
| Q116869845 |   SAMEGEN   |     Q116869826    |
| Q116869845 |   SAMEGEN   |     Q116869858    |
| Q116869845 |   SAMEGEN   |     Q116869931    |
| Q116869845 |    PARENT   |      Q162959      |
| Q116869845 |    PARENT   |      Q192682      |
| Q116869845 | GRANDPARENT |      Q4253122     |
| Q116869845 |   RELATIVE  |      Q712936      |
+------------+-------------+-------------------+

In [ ]:
%%sql
SELECT 
    k.person_id,
    p1.name AS person_name,
    k.kinship,
    k.related_person_id,
    p2.name AS related_person_name
FROM core.kinship k
LEFT JOIN core.person p1 ON p1.person_id = k.person_id
LEFT JOIN core.person p2 ON p2.person_id = k.related_person_id
WHERE k.person_id = 'Q116869845';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

7 rows affected.

+------------+-------------+-------------+-------------------+---------------------+
| person_id  | person_name |   kinship   | related_person_id | related_person_name |
+------------+-------------+-------------+-------------------+---------------------+
| Q116869845 |     None    |   SAMEGEN   |     Q116869826    |         None        |
| Q116869845 |     None    |   SAMEGEN   |     Q116869858    |         None        |
| Q116869845 |     None    |   SAMEGEN   |     Q116869931    |         None        |
| Q116869845 |     None    |    PARENT   |      Q162959      |     Blake Lively    |
| Q116869845 |     None    |    PARENT   |      Q192682      |    Ryan Reynolds    |
| Q116869845 |     None    | GRANDPARENT |      Q4253122     |     Ernie Lively    |
| Q116869845 |     None    |   RELATIVE  |      Q712936      |     Eric Lively     |
+------------+-------------+-------------+-------------------+---------------------+

In [ ]:
%%sql
SELECT * from core.kinship where person_id = 'Q192682';
SELECT * from raw.relative where personid like '%Q192682%';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

5 rows affected.

2 rows affected.

+----------+------------+-----------+----------------------+----------------+
| personid | relativeid | kinshipid |     kinshiplabel     | source_country |
+----------+------------+-----------+----------------------+----------------+
| Q192682  | Q30460493  | Q19682162 | paternal grandfather |       US       |
| Q192682  | Q30460493  | Q19682162 | paternal grandfather |       CA       |
+----------+------------+-----------+----------------------+----------------+

<!-- Ryan Reynolds (Q192682) --> 
<!-- paternal grandfather	 -->
<!-- Chester Reynolds (Q30460493) -->

In [ ]:
%%sql 
SELECT * from core.relationship where person_id = 'Q192682';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

1 rows affected.

+-----------+----------------------+-------------------+
| person_id |     relationship     | related_person_id |
+-----------+----------------------+-------------------+
|  Q192682  | paternal grandfather |     Q30460493     |
+-----------+----------------------+-------------------+

In [ ]:
%%sql 
SELECT * from core.kinship_old where person_id = 'Q192682';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

1 rows affected.

+-----------+-------------+-------------------+
| person_id |   kinship   | related_person_id |
+-----------+-------------+-------------------+
|  Q192682  | GRANDPARENT |     Q30460493     |
+-----------+-------------+-------------------+

In [ ]:
%%sql
select * from core.kinship where kinship = 'ANCESTOR';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

2281 rows affected.

+------------+----------+-------------------+
| person_id  | kinship  | related_person_id |
+------------+----------+-------------------+
| Q100135417 | ANCESTOR |     Q108223448    |
| Q100135417 | ANCESTOR |     Q98700213     |
| Q100135417 | ANCESTOR |     Q98700233     |
| Q100135417 | ANCESTOR |     Q98700266     |
| Q100135417 | ANCESTOR |     Q98700276     |
| Q100147497 | ANCESTOR |     Q18844140     |
| Q100147497 | ANCESTOR |     Q28465164     |
| Q100147497 | ANCESTOR |      Q324742      |
| Q100147497 | ANCESTOR |      Q4100648     |
| Q100147497 | ANCESTOR |      Q535360      |
+------------+----------+-------------------+
Truncated to displaylimit of 10.

### Farrow 
<!-- Dylan Farrow (Q100135417) -->

In [ ]:
%%sql 
SELECT * from core.kinship_old where person_id = 'Q100135417';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

6 rows affected.

+------------+-------------+-------------------+
| person_id  |   kinship   | related_person_id |
+------------+-------------+-------------------+
| Q100135417 | GRANDPARENT |     Q108223439    |
| Q100135417 | GRANDPARENT |     Q108223445    |
| Q100135417 |    PARENT   |      Q202725      |
| Q100135417 | GRANDPARENT |      Q230084      |
| Q100135417 |    PARENT   |       Q25089      |
| Q100135417 | GRANDPARENT |      Q547495      |
+------------+-------------+-------------------+

In [ ]:
%%sql 
SELECT * from core.kinship where person_id = 'Q100135417';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

22 rows affected.

+------------+-------------+-------------------+
| person_id  |   kinship   | related_person_id |
+------------+-------------+-------------------+
| Q100135417 | GRANDPARENT |     Q108223439    |
| Q100135417 | GRANDPARENT |     Q108223445    |
| Q100135417 |   ANCESTOR  |     Q108223448    |
| Q100135417 |   SAMEGEN   |      Q1140914     |
| Q100135417 |   SAMEGEN   |     Q16217493     |
| Q100135417 |   RELATIVE  |     Q18387067     |
| Q100135417 |    PARENT   |      Q202725      |
| Q100135417 |   SAMEGEN   |     Q22673707     |
| Q100135417 |   SAMEGEN   |     Q22673708     |
| Q100135417 | GRANDPARENT |      Q230084      |
+------------+-------------+-------------------+
Truncated to displaylimit of 10.

In [ ]:
%%sql
SELECT 
    k.person_id,
    p1.name AS person_name,
    k.kinship,
    k.related_person_id,
    p2.name AS related_person_name
FROM core.kinship k
LEFT JOIN core.person p1 ON p1.person_id = k.person_id
LEFT JOIN core.person p2 ON p2.person_id = k.related_person_id
WHERE k.person_id = 'Q100135417';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

22 rows affected.

+------------+--------------+-------------+-------------------+---------------------+
| person_id  | person_name  |   kinship   | related_person_id | related_person_name |
+------------+--------------+-------------+-------------------+---------------------+
| Q100135417 | Dylan Farrow | GRANDPARENT |     Q108223439    |         None        |
| Q100135417 | Dylan Farrow | GRANDPARENT |     Q108223445    |  Nettie Königsberg  |
| Q100135417 | Dylan Farrow |   ANCESTOR  |     Q108223448    |         None        |
| Q100135417 | Dylan Farrow |   SAMEGEN   |      Q1140914     |    Soon-Yi Previn   |
| Q100135417 | Dylan Farrow |   SAMEGEN   |     Q16217493     |     Moses Farrow    |
| Q100135417 | Dylan Farrow |   RELATIVE  |     Q18387067     |         None        |
| Q100135417 | Dylan Farrow |    PARENT   |      Q202725      |      Mia Farrow     |
| Q100135417 | Dylan Farrow |   SAMEGEN   |     Q22673707     |         None        |
| Q100135417 | Dylan Farrow |   SAMEGEN   |     Q22673708     |         None        |
| Q100135417 | Dylan Farrow | GRANDPARENT |      Q230084      |  Maureen O'Sullivan |
+------------+--------------+-------------+-------------------+---------------------+
Truncated to displaylimit of 10.

## DDL nepo baby score

In [9]:
%%sql
DROP TABLE IF EXISTS core.neposcore CASCADE;

CREATE TABLE IF NOT EXISTS core.neposcore (
    person_id                VARCHAR(20) PRIMARY KEY,
    nepo_score               NUMERIC(10,2),
    parent_score             NUMERIC(10,2),
    grandparent_score        NUMERIC(10,2),
    ancestor_score           NUMERIC(10,2),
    stepparent_score         NUMERIC(10,2),
    step_grandparent_score   NUMERIC(10,2),
    inlaw_score              NUMERIC(10,2),
    nepotag                  BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO core.neposcore (
    person_id,
    nepo_score,
    parent_score,
    grandparent_score,
    ancestor_score,
    stepparent_score,
    step_grandparent_score,
    inlaw_score,
    nepotag
)
SELECT
    k.person_id,
    ROUND(SUM(
        COALESCE(pp.person_point, 0) *
        CASE
            WHEN k.kinship = 'PARENT'              THEN 1.0
            WHEN k.kinship = 'GRANDPARENT'         THEN 0.5
            WHEN k.kinship = 'ANCESTOR'            THEN 0.25
            WHEN k.kinship = 'AUNT_UNCLE'          THEN 0.25
            WHEN k.kinship = 'GREAT_AUNT_UNCLE'    THEN 0.15
            WHEN k.kinship = 'STEPPARENT'          THEN 0.5
            WHEN k.kinship = 'STEP_GRANDPARENT'    THEN 0.25
            WHEN k.kinship = 'PARENT_INLAW'        THEN 0.25
            WHEN k.kinship = 'RELATIVE_INLAW'      THEN 0.1
                        WHEN k.kinship = 'SIBLING'      THEN 0.1
                        WHEN k.kinship = 'COUSIN_1ST'      THEN 0.05
            ELSE 0.001   -- has kinship but not in above list
        END
    ), 2) AS nepo_score,

    ROUND(SUM(CASE WHEN k.kinship = 'PARENT'
        THEN COALESCE(pp.person_point, 0) * 1.0   ELSE 0 END), 2) AS parent_score,
    ROUND(SUM(CASE WHEN k.kinship = 'GRANDPARENT'
        THEN COALESCE(pp.person_point, 0) * 0.5   ELSE 0 END), 2) AS grandparent_score,
    ROUND(SUM(CASE WHEN k.kinship = 'ANCESTOR'
        THEN COALESCE(pp.person_point, 0) * 0.25  ELSE 0 END), 2) AS ancestor_score,
    ROUND(SUM(CASE WHEN k.kinship = 'STEPPARENT'
        THEN COALESCE(pp.person_point, 0) * 0.5   ELSE 0 END), 2) AS stepparent_score,
    ROUND(SUM(CASE WHEN k.kinship = 'STEP_GRANDPARENT'
        THEN COALESCE(pp.person_point, 0) * 0.25  ELSE 0 END), 2) AS step_grandparent_score,
    ROUND(SUM(CASE WHEN k.kinship IN ('PARENT_INLAW', 'RELATIVE_INLAW')
        THEN COALESCE(pp.person_point, 0) * 0.25  ELSE 0 END), 2) AS inlaw_score,

    -- nepotag: TRUE if any upper-gen relative has an IMDb number
    BOOL_OR(
        k.kinship IN (
            'PARENT', 'GRANDPARENT', 'ANCESTOR',
            'AUNT_UNCLE', 'GREAT_AUNT_UNCLE',
            'STEPPARENT', 'STEP_GRANDPARENT',
            'PARENT_INLAW', 'RELATIVE_INLAW'
        )
        AND EXISTS (
            SELECT 1
            FROM core.person rel
            WHERE rel.person_id = k.related_person_id
              AND rel.nconst IS NOT NULL
        )
    ) AS nepotag

FROM core.kinship k
LEFT JOIN core.personpoint pp ON k.related_person_id = pp.person_id
GROUP BY k.person_id;

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

42356 rows affected.

++
||
++
++

### count

In [ ]:
%%sql
%%sql
select count(*) from core.neposcore where nepo_tag = TRUE;

In [11]:
%%sql
select count(*) from core.neposcore where nepo_score > 1;

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

1 rows affected.

+-------+
| count |
+-------+
|  9616 |
+-------+

In [12]:
%%sql
-- Group 1: person has upper-gen relative with IMDb
SELECT 'Group 1: Upper-gen has IMDb' AS group_label,
       COUNT(DISTINCT k.person_id)   AS person_count
FROM core.kinship k
JOIN core.person rel ON rel.person_id = k.related_person_id
WHERE k.kinship IN (
    'PARENT', 'GRANDPARENT', 'ANCESTOR',
    'AUNT_UNCLE', 'GREAT_AUNT_UNCLE',
    'STEPPARENT', 'STEP_GRANDPARENT',
    'PARENT_INLAW', 'RELATIVE_INLAW'
)
AND rel.nconst IS NOT NULL

UNION ALL

-- Group 2: Group 1 + same-gen relative with IMDb
SELECT 'Group 2: Upper-gen + Same-gen has IMDb' AS group_label,
       COUNT(DISTINCT k.person_id)              AS person_count
FROM core.kinship k
JOIN core.person rel ON rel.person_id = k.related_person_id
WHERE k.kinship IN (
    'PARENT', 'GRANDPARENT', 'ANCESTOR',
    'AUNT_UNCLE', 'GREAT_AUNT_UNCLE',
    'STEPPARENT', 'STEP_GRANDPARENT',
    'PARENT_INLAW', 'RELATIVE_INLAW',
    'SIBLING', 'SPOUSE', 'RELATIVE'
)
AND rel.nconst IS NOT NULL

UNION ALL

-- Group 3: Group 1 + 2 + lower-gen relative with IMDb
SELECT 'Group 3: Upper-gen + Same-gen + Lower-gen has IMDb' AS group_label,
       COUNT(DISTINCT k.person_id)                          AS person_count
FROM core.kinship k
JOIN core.person rel ON rel.person_id = k.related_person_id
WHERE k.kinship IN (
    'PARENT', 'GRANDPARENT', 'ANCESTOR',
    'AUNT_UNCLE', 'GREAT_AUNT_UNCLE',
    'STEPPARENT', 'STEP_GRANDPARENT',
    'PARENT_INLAW', 'RELATIVE_INLAW',
    'SIBLING', 'SPOUSE', 'RELATIVE',
    'CHILD', 'GRANDCHILD'
)
AND rel.nconst IS NOT NULL

UNION ALL

-- Group 4: person themselves has IMDb
SELECT 'Group 4: Person has IMDb'  AS group_label,
       COUNT(DISTINCT p.person_id) AS person_count
FROM core.person p
WHERE p.nconst IS NOT NULL;

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

4 rows affected.

+----------------------------------------------------+--------------+
|                    group_label                     | person_count |
+----------------------------------------------------+--------------+
|              Group 4: Person has IMDb              |    112608    |
|            Group 1: Upper-gen has IMDb             |     5650     |
| Group 3: Upper-gen + Same-gen + Lower-gen has IMDb |    17212     |
|       Group 2: Upper-gen + Same-gen has IMDb       |     9344     |
+----------------------------------------------------+--------------+

In [13]:
%%sql
SELECT
    CASE
        WHEN nepo_score >= 10000 THEN '6. 10000+'
        WHEN nepo_score >= 7000  THEN '5. 7000+'
        WHEN nepo_score >= 5000  THEN '4. 5000+'
        WHEN nepo_score >= 1000  THEN '3. 1000+'
        WHEN nepo_score >= 100   THEN '2. 100+'
        WHEN nepo_score >= 10    THEN '1. 10+'
        ELSE                          '0. under 10'
        END AS score_bucket,
    COUNT(*) AS person_count
FROM core.neposcore
WHERE nepo_score > 0
GROUP BY score_bucket
ORDER BY score_bucket;

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

7 rows affected.

+--------------+--------------+
| score_bucket | person_count |
+--------------+--------------+
| 0. under 10  |     8913     |
|    1. 10+    |     2964     |
|   2. 100+    |     2609     |
|   3. 1000+   |     1290     |
|   4. 5000+   |      59      |
|   5. 7000+   |      16      |
|  6. 10000+   |      1       |
+--------------+--------------+

## peoplepoint moviepoint

### breakdown points

In [119]:
%%sql

DROP TABLE IF EXISTS core.personmoviepoint CASCADE;

CREATE TABLE IF NOT EXISTS core.personmoviepoint (
    person_id          VARCHAR(20),
    tconst             VARCHAR(10)   NOT NULL,
    primary_title      VARCHAR(255),
    ordering           INT,
    ordering_weight    NUMERIC(10,2),
    movie_point        NUMERIC(10,2),
    weighted_point     NUMERIC(10,2),
    PRIMARY KEY (person_id, tconst)
);

INSERT INTO core.personmoviepoint (
    person_id,
    tconst,
    primary_title,
    ordering,
    ordering_weight,
    movie_point,
    weighted_point
)
WITH
moviepoints AS (
    SELECT
        t.tconst,
        t.primary_title,
        (
            COALESCE(LOG(CAST(r.num_votes AS NUMERIC)) * r.average_rating, 0) +
            COALESCE(SUM(CASE WHEN m.type = 'Award' THEN 10 ELSE 3 END), 0)
        ) AS movie_point
    FROM core.title t
    LEFT JOIN core.rating     r ON t.tconst = r.tconst
    LEFT JOIN core.movieaward m ON t.tconst = m.tconst
    GROUP BY t.tconst, t.primary_title, r.num_votes, r.average_rating
),
cast_weights AS (
    SELECT
        tconst,
        ordering,
        (COUNT(*) OVER (PARTITION BY tconst) - ordering + 1.0) /
        (COUNT(*) OVER (PARTITION BY tconst) *
            (COUNT(*) OVER (PARTITION BY tconst) + 1.0) / 2.0) AS weight
    FROM core.principal
),
person_movie_raw AS (
    SELECT
        p.person_id,
        pr.tconst,
        mp.primary_title,
        pr.ordering,
        cw.weight                   AS ordering_weight,
        mp.movie_point              AS movie_point,
        cw.weight * mp.movie_point  AS weighted_point,
        ROW_NUMBER() OVER (
            PARTITION BY p.person_id, pr.tconst
            ORDER BY pr.ordering ASC
        ) AS rn
    FROM core.person p
    LEFT JOIN core.principal  pr ON pr.nconst  = p.nconst      
    LEFT JOIN moviepoints     mp ON mp.tconst  = pr.tconst    
    LEFT JOIN cast_weights    cw ON cw.tconst  = pr.tconst
                           AND cw.ordering = pr.ordering
    WHERE p.nconst IS NOT NULL                             -- explicit guard
      AND pr.tconst IS NOT NULL
)
SELECT
    person_id,
    tconst,
    primary_title,
    ordering,
    ROUND(ordering_weight, 2)  AS ordering_weight,
    ROUND(movie_point,     2)  AS movie_point,
    ROUND(weighted_point,  2)  AS weighted_point
FROM person_movie_raw
WHERE rn = 1
ORDER BY person_id, weighted_point DESC;

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

973243 rows affected.

++
||
++
++

### Jaden Smith (Q221364)

In [29]:
nepo_breakdown('Q221364')

───────────────────────────────────────────────────────
  Jaden Smith (Q221364)
  Nepo score (stored): 3769.0
  Contribution sum   : 3748
  Relatives found    : 7
  Contributing (>0)  : 2
───────────────────────────────────────────────────────

,person_id,person_name,kinship,gen_delta,degree,raw_relationship,related_person_id,related_name,person_point,movie_point,award_point,kinship_weight,contribution,person_nepo_score,person_parent_score,person_grandparent_score,person_ancestor_score
0,Q221364,Jaden Smith,PARENT,1,0,father,Q40096,Will Smith,2608.0,2385.0,223.0,1.0,2608.0,3769.0,3748.0,0.0,0.0
1,Q221364,Jaden Smith,PARENT,1,0,mother,Q228787,Jada Pinkett Smith,1140.0,1100.0,40.0,1.0,1140.0,3769.0,3748.0,0.0,0.0
2,Q221364,Jaden Smith,GRANDPARENT,2,0,None,Q64877990,None,0.0,0.0,0.0,0.5,0.0,3769.0,3748.0,0.0,0.0
3,Q221364,Jaden Smith,GRANDPARENT,2,0,None,Q107338232,None,0.0,0.0,0.0,0.5,0.0,3769.0,3748.0,0.0,0.0
4,Q221364,Jaden Smith,SIBLING,0,1,sibling,Q298209,Willow Smith,195.0,155.0,40.0,0.0,0.0,3769.0,3748.0,0.0,0.0
5,Q221364,Jaden Smith,SIBLING,0,1,sibling,Q7885297,Trey Smith,17.0,17.0,0.0,0.0,0.0,3769.0,3748.0,0.0,0.0
6,Q221364,Jaden Smith,STEPSIBLING,1,11,None,Q21012774,Sheree Zampino,34.0,34.0,0.0,0.0,0.0,3769.0,3748.0,0.0,0.0

### Gwyneth Paltrow (Q34460)

In [30]:
nepo_breakdown('Q34460')

───────────────────────────────────────────────────────
  Gwyneth Paltrow (Q34460)
  Nepo score (stored): 1452.0
  Contribution sum   : 1433
  Relatives found    : 4
  Contributing (>0)  : 2
───────────────────────────────────────────────────────

,person_id,person_name,kinship,gen_delta,degree,raw_relationship,related_person_id,related_name,person_point,movie_point,award_point,kinship_weight,contribution,person_nepo_score,person_parent_score,person_grandparent_score,person_ancestor_score
0,Q34460,Gwyneth Paltrow,PARENT,1,0,mother,Q40064,Blythe Danner,1309.0,1263.0,46.0,1.0,1309.0,1452.0,1433.0,0.0,0.0
1,Q34460,Gwyneth Paltrow,PARENT,1,0,father,Q991765,Bruce Paltrow,124.0,114.0,10.0,1.0,124.0,1452.0,1433.0,0.0,0.0
2,Q34460,Gwyneth Paltrow,GRANDPARENT,2,0,None,Q61726423,None,0.0,0.0,0.0,0.5,0.0,1452.0,1433.0,0.0,0.0
3,Q34460,Gwyneth Paltrow,SIBLING,0,1,sibling,Q727938,Jake Paltrow,189.0,179.0,10.0,0.0,0.0,1452.0,1433.0,0.0,0.0

In [ ]:
%%sql
select * from core.kinship where person_id = 'Q40064';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

2 rows affected.

+-----------+---------+-------------------+-----------+--------+---------+
| person_id | kinship | related_person_id | gen_delta | degree | lca_gen |
+-----------+---------+-------------------+-----------+--------+---------+
|   Q40064  |  CHILD  |       Q34460      |     -1    |   0    |    0    |
|   Q40064  |  CHILD  |      Q727938      |     -1    |   0    |    0    |
+-----------+---------+-------------------+-----------+--------+---------+

In [ ]:
nepo_breakdown('Q727938')

,person_id,person_name,kinship,relationship,related_person_id,related_person_name,person_point,person_movie_point,person_award_point,kinship_weight,contribution,person_nepo_score,parent_score,grandparent_score,ancestor_score,relative_score
0,Q727938,Jake Paltrow,GRANDPARENT,None,Q61726423,None,0.0,0.0,0.0,0.5,0.0,1433.0,1433.0,0.0,0.0,0.0
1,Q727938,Jake Paltrow,PARENT,mother,Q40064,Blythe Danner,1309.0,1263.0,46.0,1.0,1309.0,1433.0,1433.0,0.0,0.0,0.0
2,Q727938,Jake Paltrow,PARENT,father,Q991765,Bruce Paltrow,124.0,114.0,10.0,1.0,124.0,1433.0,1433.0,0.0,0.0,0.0
3,Q727938,Jake Paltrow,SIBLING,sibling,Q34460,Gwyneth Paltrow,2134.0,2044.0,90.0,0.5,1067.0,1433.0,1433.0,0.0,0.0,0.0

### Sosie Bacon (Q3491343)
Sosie Bacon (Q3491343) --> Kyra Sedgwick (Q229572): mother
Kyra Sedgwick (Q229572) --> Robert Sedgwick (Q7349673): sibling 
Therefore:
Sosie Bacon (Q3491343) --> Robert Sedgwick (Q7349673): uncle

In [25]:
%%sql 
select * from core.kinship_old where person_id = 'Q3491343';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

6 rows affected.

+-----------+-------------+-------------------+
| person_id |   kinship   | related_person_id |
+-----------+-------------+-------------------+
|  Q3491343 | GRANDPARENT |      Q1285964     |
|  Q3491343 |    PARENT   |      Q229572      |
|  Q3491343 |    PARENT   |      Q3454165     |
|  Q3491343 | GRANDPARENT |     Q84627701     |
|  Q3491343 | GRANDPARENT |     Q92506118     |
|  Q3491343 | GRANDPARENT |     Q96089569     |
+-----------+-------------+-------------------+

In [26]:

nepo_breakdown('Q3491343')

───────────────────────────────────────────────────────
  Sosie Bacon (Q3491343)
  Nepo score (stored): 3984.0
  Contribution sum   : 3978
  Relatives found    : 14
  Contributing (>0)  : 4
───────────────────────────────────────────────────────

,person_id,person_name,kinship,gen_delta,degree,raw_relationship,related_person_id,related_name,person_point,movie_point,award_point,kinship_weight,contribution,person_nepo_score,person_parent_score,person_grandparent_score,person_ancestor_score
0,Q3491343,Sosie Bacon,PARENT,1,0,father,Q3454165,Kevin Bacon,2728.0,2688.0,40.0,1.00,2728.0,3984.0,3877.0,0.0,0.0
1,Q3491343,Sosie Bacon,PARENT,1,0,mother,Q229572,Kyra Sedgwick,1149.0,1119.0,30.0,1.00,1149.0,3984.0,3877.0,0.0,0.0
2,Q3491343,Sosie Bacon,GRANDPARENT,2,0,None,Q96089569,None,0.0,0.0,0.0,0.50,0.0,3984.0,3877.0,0.0,0.0
3,Q3491343,Sosie Bacon,GRANDPARENT,2,0,None,Q84627701,None,0.0,0.0,0.0,0.50,0.0,3984.0,3877.0,0.0,0.0
4,Q3491343,Sosie Bacon,GRANDPARENT,2,0,None,Q1285964,None,0.0,0.0,0.0,0.50,0.0,3984.0,3877.0,0.0,0.0
5,Q3491343,Sosie Bacon,GRANDPARENT,2,0,None,Q92506118,None,0.0,0.0,0.0,0.50,0.0,3984.0,3877.0,0.0,0.0
6,Q3491343,Sosie Bacon,AUNT_UNCLE,1,1,None,Q3308009,Michael Bacon,341.0,331.0,10.0,0.25,85.0,3984.0,3877.0,0.0,0.0
7,Q3491343,Sosie Bacon,AUNT_UNCLE,1,1,None,Q7349673,Robert Sedgwick,64.0,64.0,0.0,0.25,16.0,3984.0,3877.0,0.0,0.0
8,Q3491343,Sosie Bacon,ANCESTOR,3,0,None,Q84627670,None,0.0,0.0,0.0,0.25,0.0,3984.0,3877.0,0.0,0.0
9,Q3491343,Sosie Bacon,ANCESTOR,3,0,None,Q92377560,None,0.0,0.0,0.0,0.25,0.0,3984.0,3877.0,0.0,0.0
10,Q3491343,Sosie Bacon,ANCESTOR,3,0,None,Q96089566,None,0.0,0.0,0.0,0.25,0.0,3984.0,3877.0,0.0,0.0
11,Q3491343,Sosie Bacon,ANCESTOR,3,0,None,Q96089567,None,0.0,0.0,0.0,0.25,0.0,3984.0,3877.0,0.0,0.0
12,Q3491343,Sosie Bacon,AUNT_UNCLE,1,1,None,Q220889,None,0.0,0.0,0.0,0.25,0.0,3984.0,3877.0,0.0,0.0
13,Q3491343,Sosie Bacon,SIBLING,0,1,sibling,Q123035774,Travis Bacon,53.0,53.0,0.0,0.00,0.0,3984.0,3877.0,0.0,0.0

### Grace Van Dien

Grace Van Dien (Q50400184) -> Carrie Mitchum (Q9184868) : mother
Carrie Mitchum (Q9184868) -> Bentley Mitchum (Q4890485) : sibling 
Therefore:
Grace Van Dien (Q50400184) -> Bentley Mitchum (Q4890485) : Uncle

In [24]:
#Grace Van Dien (Q50400184)

nepo_breakdown('Q50400184') 
## half-sibling Celeste Van Dien share father

───────────────────────────────────────────────────────
  Grace Van Dien (Q50400184)
  Nepo score (stored): 2449.0
  Contribution sum   : 2448
  Relatives found    : 13
  Contributing (>0)  : 8
───────────────────────────────────────────────────────

,person_id,person_name,kinship,gen_delta,degree,raw_relationship,related_person_id,related_name,person_point,movie_point,award_point,kinship_weight,contribution,person_nepo_score,person_parent_score,person_grandparent_score,person_ancestor_score
0,Q50400184,Grace Van Dien,PARENT,1,0,father,Q313804,Casper Van Dien,1218.0,1218.0,0.0,1.00,1218.0,2449.0,1249.0,281.0,788.0
1,Q50400184,Grace Van Dien,PARENT,1,0,mother,Q9184868,Carrie Mitchum,31.0,31.0,0.0,1.00,31.0,2449.0,1249.0,281.0,788.0
2,Q50400184,Grace Van Dien,GRANDPARENT,2,0,None,Q1086852,Christopher Mitchum,561.0,561.0,0.0,0.50,281.0,2449.0,1249.0,281.0,788.0
3,Q50400184,Grace Van Dien,ANCESTOR,3,0,None,Q16472,Robert Mitchum,2779.0,2746.0,33.0,0.25,695.0,2449.0,1249.0,281.0,788.0
4,Q50400184,Grace Van Dien,ANCESTOR,3,1,None,Q474746,John Mitchum,324.0,324.0,0.0,0.25,81.0,2449.0,1249.0,281.0,788.0
5,Q50400184,Grace Van Dien,AUNT_UNCLE,1,1,None,Q4890485,Bentley Mitchum,311.0,311.0,0.0,0.25,78.0,2449.0,1249.0,281.0,788.0
6,Q50400184,Grace Van Dien,ANCESTOR,3,1,None,Q3189245,Julie Mitchum,50.0,50.0,0.0,0.25,12.0,2449.0,1249.0,281.0,788.0
7,Q50400184,Grace Van Dien,ANCESTOR,4,0,None,Q116480419,None,0.0,0.0,0.0,0.25,0.0,2449.0,1249.0,281.0,788.0
8,Q50400184,Grace Van Dien,ANCESTOR,4,0,None,Q116480418,None,0.0,0.0,0.0,0.25,0.0,2449.0,1249.0,281.0,788.0
9,Q50400184,Grace Van Dien,GREAT_AUNT_UNCLE,2,1,None,Q1586724,James Mitchum,347.0,347.0,0.0,0.15,52.0,2449.0,1249.0,281.0,788.0
10,Q50400184,Grace Van Dien,SIBLING,0,1,None,Q113950100,Allexanne Mitchum,8.0,8.0,0.0,0.00,0.0,2449.0,1249.0,281.0,788.0
11,Q50400184,Grace Van Dien,STEPSIBLING,1,11,None,Q235284,Catherine Oxenberg,284.0,284.0,0.0,0.00,0.0,2449.0,1249.0,281.0,788.0
12,Q50400184,Grace Van Dien,STEPSIBLING,0,11,None,Q75244337,India Oxenberg,17.0,17.0,0.0,0.00,0.0,2449.0,1249.0,281.0,788.0

In [ ]:
nepo_breakdown('Q1086852')

───────────────────────────────────────────────────────
  Christopher Mitchum (Q1086852)
  Nepo score (stored): 2779.0
  Contribution sum   : 2872
  Relatives found    : 10
  Contributing (>0)  : 3
───────────────────────────────────────────────────────

,person_id,person_name,kinship,gen_delta,degree,raw_relationship,related_person_id,related_name,person_point,movie_point,award_point,kinship_weight,contribution,person_nepo_score,person_parent_score,person_grandparent_score,person_ancestor_score
0,Q1086852,Christopher Mitchum,PARENT,1,0,father,Q16472,Robert Mitchum,2779.0,2746.0,33.0,1.00,2779.0,2779.0,2779.0,0.0,0.0
1,Q1086852,Christopher Mitchum,GRANDPARENT,2,0,None,Q116480418,None,0.0,0.0,0.0,0.50,0.0,2779.0,2779.0,0.0,0.0
2,Q1086852,Christopher Mitchum,GRANDPARENT,2,0,None,Q116480419,None,0.0,0.0,0.0,0.50,0.0,2779.0,2779.0,0.0,0.0
3,Q1086852,Christopher Mitchum,AUNT_UNCLE,1,1,None,Q474746,John Mitchum,324.0,324.0,0.0,0.25,81.0,2779.0,2779.0,0.0,0.0
4,Q1086852,Christopher Mitchum,AUNT_UNCLE,1,1,None,Q3189245,Julie Mitchum,50.0,50.0,0.0,0.25,12.0,2779.0,2779.0,0.0,0.0
5,Q1086852,Christopher Mitchum,CHILD,-1,0,None,Q9184868,Carrie Mitchum,31.0,31.0,0.0,0.00,0.0,2779.0,2779.0,0.0,0.0
6,Q1086852,Christopher Mitchum,CHILD,-1,0,None,Q4890485,Bentley Mitchum,311.0,311.0,0.0,0.00,0.0,2779.0,2779.0,0.0,0.0
7,Q1086852,Christopher Mitchum,GRANDCHILD,-2,0,None,Q113950100,Allexanne Mitchum,8.0,8.0,0.0,0.00,0.0,2779.0,2779.0,0.0,0.0
8,Q1086852,Christopher Mitchum,GRANDCHILD,-2,0,None,Q50400184,Grace Van Dien,361.0,361.0,0.0,0.00,0.0,2779.0,2779.0,0.0,0.0
9,Q1086852,Christopher Mitchum,SIBLING,0,1,sibling,Q1586724,James Mitchum,347.0,347.0,0.0,0.00,0.0,2779.0,2779.0,0.0,0.0

In [ ]:
nepo_breakdown('Q9184868')

───────────────────────────────────────────────────────
  Carrie Mitchum (Q9184868)
  Nepo score (stored): 1951.0
  Contribution sum   : 2094
  Relatives found    : 9
  Contributing (>0)  : 5
───────────────────────────────────────────────────────

,person_id,person_name,kinship,gen_delta,degree,raw_relationship,related_person_id,related_name,person_point,movie_point,award_point,kinship_weight,contribution,person_nepo_score,person_parent_score,person_grandparent_score,person_ancestor_score
0,Q9184868,Carrie Mitchum,PARENT,1,0,father,Q1086852,Christopher Mitchum,561.0,561.0,0.0,1.00,561.0,1951.0,561.0,1390.0,0.0
1,Q9184868,Carrie Mitchum,GRANDPARENT,2,0,None,Q16472,Robert Mitchum,2779.0,2746.0,33.0,0.50,1390.0,1951.0,561.0,1390.0,0.0
2,Q9184868,Carrie Mitchum,AUNT_UNCLE,1,1,None,Q1586724,James Mitchum,347.0,347.0,0.0,0.25,87.0,1951.0,561.0,1390.0,0.0
3,Q9184868,Carrie Mitchum,ANCESTOR,3,0,None,Q116480418,None,0.0,0.0,0.0,0.25,0.0,1951.0,561.0,1390.0,0.0
4,Q9184868,Carrie Mitchum,ANCESTOR,3,0,None,Q116480419,None,0.0,0.0,0.0,0.25,0.0,1951.0,561.0,1390.0,0.0
5,Q9184868,Carrie Mitchum,GREAT_AUNT_UNCLE,2,1,None,Q474746,John Mitchum,324.0,324.0,0.0,0.15,49.0,1951.0,561.0,1390.0,0.0
6,Q9184868,Carrie Mitchum,GREAT_AUNT_UNCLE,2,1,None,Q3189245,Julie Mitchum,50.0,50.0,0.0,0.15,7.0,1951.0,561.0,1390.0,0.0
7,Q9184868,Carrie Mitchum,CHILD,-1,0,None,Q50400184,Grace Van Dien,361.0,361.0,0.0,0.00,0.0,1951.0,561.0,1390.0,0.0
8,Q9184868,Carrie Mitchum,SIBLING,0,1,sibling,Q4890485,Bentley Mitchum,311.0,311.0,0.0,0.00,0.0,1951.0,561.0,1390.0,0.0

In [ ]:
nepo_breakdown('Q3925') ##Grace Kelly

,person_id,person_name,kinship,relationship,related_person_id,related_person_name,person_point,person_movie_point,person_award_point,kinship_weight,contribution,person_nepo_score,parent_score,grandparent_score,ancestor_score,relative_score
0,Q3925,Grace Kelly,CHILD,None,Q3910,"Albert II, Prince of Monaco",530.0,80.0,450.0,1.0,530.0,0.0,0.0,0.0,0.0,0.0
1,Q3925,Grace Kelly,GRANDCHILD,None,Q2738333,Jazmin Grace Grimaldi,28.0,28.0,0.0,0.5,14.0,0.0,0.0,0.0,0.0,0.0
2,Q3925,Grace Kelly,PARENT,mother,Q18715802,None,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Q3925,Grace Kelly,PARENT,father,Q1334513,None,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Q3925,Grace Kelly,SIBLING,None,Q3181856,None,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0
5,Q3925,Grace Kelly,SIBLING,None,Q76324062,None,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0
6,Q3925,Grace Kelly,SIBLING,None,Q76324064,None,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
nepo_breakdown('Q2738333') ##Jazmin Grace Grimaldi

,person_id,person_name,kinship,relationship,related_person_id,related_person_name,person_point,person_movie_point,person_award_point,kinship_weight,contribution,person_nepo_score,parent_score,grandparent_score,ancestor_score,relative_score
0,Q2738333,Jazmin Grace Grimaldi,ANCESTOR,None,Q1334513,None,0.0,0.0,0.0,0.25,0.0,943.0,530.0,413.0,0.0,0.0
1,Q2738333,Jazmin Grace Grimaldi,ANCESTOR,None,Q18715802,None,0.0,0.0,0.0,0.25,0.0,943.0,530.0,413.0,0.0,0.0
2,Q2738333,Jazmin Grace Grimaldi,GRANDPARENT,None,Q3925,Grace Kelly,826.0,703.0,123.0,0.50,413.0,943.0,530.0,413.0,0.0,0.0
3,Q2738333,Jazmin Grace Grimaldi,GRANDPARENT,None,Q185025,None,0.0,0.0,0.0,0.50,0.0,943.0,530.0,413.0,0.0,0.0
4,Q2738333,Jazmin Grace Grimaldi,PARENT,father,Q3910,"Albert II, Prince of Monaco",530.0,80.0,450.0,1.00,530.0,943.0,530.0,413.0,0.0,0.0
5,Q2738333,Jazmin Grace Grimaldi,PARENT,mother,Q61742565,None,0.0,0.0,0.0,1.00,0.0,943.0,530.0,413.0,0.0,0.0

In [ ]:
%%sql 
select * from core.kinship_old where person_id = 'Q50400184';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

3 rows affected.

+-----------+-------------+-------------------+
| person_id |   kinship   | related_person_id |
+-----------+-------------+-------------------+
| Q50400184 | GRANDPARENT |      Q1086852     |
| Q50400184 |    PARENT   |      Q313804      |
| Q50400184 |    PARENT   |      Q9184868     |
+-----------+-------------+-------------------+

In [ ]:
nepo_breakdown('Q229011')

,person_id,person_name,kinship,relationship,related_person_id,related_person_name,person_point,person_movie_point,person_award_point,kinship_weight,contribution,person_nepo_score,parent_score,grandparent_score,ancestor_score,relative_score
0,Q229011,Leslie Mann,CHILD,None,Q16147452,Maude Apatow,276.0,276.0,0.0,1.0,276.0,0.0,0.0,0.0,0.0,0.0
1,Q229011,Leslie Mann,CHILD,None,Q16021057,Iris Apatow,274.0,274.0,0.0,1.0,274.0,0.0,0.0,0.0,0.0,0.0

### Emilio Estevez (Q220918)

In [23]:
nepo_breakdown('Q46994907')

───────────────────────────────────────────────────────
  Maya Hawke (Q46994907)
  Nepo score (stored): 5414.0
  Contribution sum   : 5405
  Relatives found    : 14
  Contributing (>0)  : 3
───────────────────────────────────────────────────────

,person_id,person_name,kinship,gen_delta,degree,raw_relationship,related_person_id,related_name,person_point,movie_point,award_point,kinship_weight,contribution,person_nepo_score,person_parent_score,person_grandparent_score,person_ancestor_score
0,Q46994907,Maya Hawke,PARENT,1,0,father,Q484615,Ethan Hawke,3034.0,3002.0,32.0,1.00,3034.0,5414.0,5339.0,66.0,0.0
1,Q46994907,Maya Hawke,PARENT,1,0,mother,Q125017,Uma Thurman,2305.0,2209.0,96.0,1.00,2305.0,5414.0,5339.0,66.0,0.0
2,Q46994907,Maya Hawke,GRANDPARENT,2,0,maternal grandfather,Q1377791,Robert Thurman,133.0,113.0,20.0,0.50,66.0,5414.0,5339.0,66.0,0.0
3,Q46994907,Maya Hawke,GRANDPARENT,2,0,maternal grandmother,Q623962,Nena von Schlebrügge,0.0,0.0,0.0,0.50,0.0,5414.0,5339.0,66.0,0.0
4,Q46994907,Maya Hawke,GRANDPARENT,2,0,None,Q96308451,None,0.0,0.0,0.0,0.50,0.0,5414.0,5339.0,66.0,0.0
5,Q46994907,Maya Hawke,GRANDPARENT,2,0,None,Q96308484,None,0.0,0.0,0.0,0.50,0.0,5414.0,5339.0,66.0,0.0
6,Q46994907,Maya Hawke,ANCESTOR,3,0,None,Q98099965,None,0.0,0.0,0.0,0.25,0.0,5414.0,5339.0,66.0,0.0
7,Q46994907,Maya Hawke,ANCESTOR,3,0,None,Q98100000,None,0.0,0.0,0.0,0.25,0.0,5414.0,5339.0,66.0,0.0
8,Q46994907,Maya Hawke,ANCESTOR,3,0,None,Q98100003,None,0.0,0.0,0.0,0.25,0.0,5414.0,5339.0,66.0,0.0
9,Q46994907,Maya Hawke,ANCESTOR,3,0,None,Q98099996,None,0.0,0.0,0.0,0.25,0.0,5414.0,5339.0,66.0,0.0
10,Q46994907,Maya Hawke,RELATIVE,2,12,None,Q211731,Timothy Leary,493.0,493.0,0.0,0.00,0.0,5414.0,5339.0,66.0,0.0
11,Q46994907,Maya Hawke,SIBLING,0,1,sibling,Q119248191,Levon Hawke,55.0,55.0,0.0,0.00,0.0,5414.0,5339.0,66.0,0.0
12,Q46994907,Maya Hawke,SIBLING,0,1,None,Q128601382,None,0.0,0.0,0.0,0.00,0.0,5414.0,5339.0,66.0,0.0
13,Q46994907,Maya Hawke,STEPSIBLING,1,11,None,Q83492,Gary Oldman,2847.0,2761.0,86.0,0.00,0.0,5414.0,5339.0,66.0,0.0

In [ ]:
nepo_breakdown('Q8877')

,person_id,person_name,kinship,relationship,related_person_id,related_person_name,person_point,person_movie_point,person_award_point,kinship_weight,contribution,person_nepo_score,parent_score,grandparent_score,ancestor_score,relative_score
0,Q8877,Steven Spielberg,CHILD,None,Q40057,Jessica Capshaw,389.0,389.0,0.0,1.0,389.0,10.0,10.0,0.0,0.0,0.0
1,Q8877,Steven Spielberg,CHILD,None,Q29260395,Sawyer Spielberg,76.0,76.0,0.0,1.0,76.0,10.0,10.0,0.0,0.0,0.0
2,Q8877,Steven Spielberg,CHILD,None,Q7425114,Sasha Spielberg,52.0,52.0,0.0,1.0,52.0,10.0,10.0,0.0,0.0,0.0
3,Q8877,Steven Spielberg,CHILD,None,Q117265290,Destry Spielberg,32.0,32.0,0.0,1.0,32.0,10.0,10.0,0.0,0.0,0.0
4,Q8877,Steven Spielberg,CHILD,None,Q29260589,Max Spielberg,0.0,0.0,0.0,1.0,0.0,10.0,10.0,0.0,0.0,0.0
5,Q8877,Steven Spielberg,CHILD,None,Q29260744,Theo Spielberg,0.0,0.0,0.0,1.0,0.0,10.0,10.0,0.0,0.0,0.0
6,Q8877,Steven Spielberg,GRANDCHILD,None,Q133892112,None,0.0,0.0,0.0,0.5,0.0,10.0,10.0,0.0,0.0,0.0
7,Q8877,Steven Spielberg,PARENT,father,Q15784029,Arnold Spielberg,10.0,0.0,10.0,1.0,10.0,10.0,10.0,0.0,0.0,0.0
8,Q8877,Steven Spielberg,SIBLING,sibling,Q469204,Anne Spielberg,83.0,60.0,23.0,0.5,42.0,10.0,10.0,0.0,0.0,0.0

In [ ]:
nepo_breakdown('Q106997')

,person_id,person_name,kinship,relationship,related_person_id,related_person_name,person_point,person_movie_point,person_award_point,kinship_weight,contribution,person_nepo_score,parent_score,grandparent_score,ancestor_score,relative_score
0,Q106997,Jamie Lee Curtis,CHILD,None,Q43376115,Ruby Guest,0.0,0.0,0.0,1.0,0.0,4091.0,4091.0,0.0,0.0,0.0
1,Q106997,Jamie Lee Curtis,CHILD,None,Q56234831,Annie Guest,0.0,0.0,0.0,1.0,0.0,4091.0,4091.0,0.0,0.0,0.0
2,Q106997,Jamie Lee Curtis,GRANDPARENT,None,Q75486200,None,0.0,0.0,0.0,0.5,0.0,4091.0,4091.0,0.0,0.0,0.0
3,Q106997,Jamie Lee Curtis,GRANDPARENT,None,Q75486196,None,0.0,0.0,0.0,0.5,0.0,4091.0,4091.0,0.0,0.0,0.0
4,Q106997,Jamie Lee Curtis,GRANDPARENT,None,Q75486198,None,0.0,0.0,0.0,0.5,0.0,4091.0,4091.0,0.0,0.0,0.0
5,Q106997,Jamie Lee Curtis,GRANDPARENT,None,Q75486199,None,0.0,0.0,0.0,0.5,0.0,4091.0,4091.0,0.0,0.0,0.0
6,Q106997,Jamie Lee Curtis,PARENT,father,Q162389,Tony Curtis,2718.0,2622.0,96.0,1.0,2718.0,4091.0,4091.0,0.0,0.0,0.0
7,Q106997,Jamie Lee Curtis,PARENT,mother,Q205314,Janet Leigh,1373.0,1350.0,23.0,1.0,1373.0,4091.0,4091.0,0.0,0.0,0.0
8,Q106997,Jamie Lee Curtis,SIBLING,sibling,Q273574,Kelly Curtis,77.0,77.0,0.0,0.5,38.0,4091.0,4091.0,0.0,0.0,0.0
9,Q106997,Jamie Lee Curtis,SIBLING,None,Q1660236,Allegra Curtis,15.0,15.0,0.0,0.5,7.0,4091.0,4091.0,0.0,0.0,0.0

### Blake Lively (Q162959)

In [22]:
nepo_breakdown('Q162959') #Blake Lively

───────────────────────────────────────────────────────
  Blake Lively (Q162959)
  Nepo score (stored): 331.0
  Contribution sum   : 236
  Relatives found    : 9
  Contributing (>0)  : 1
───────────────────────────────────────────────────────

,person_id,person_name,kinship,gen_delta,degree,raw_relationship,related_person_id,related_name,person_point,movie_point,award_point,kinship_weight,contribution,person_nepo_score,person_parent_score,person_grandparent_score,person_ancestor_score
0,Q162959,Blake Lively,PARENT,1,0,father,Q4253122,Ernie Lively,236.0,236.0,0.0,1.0,236.0,331.0,236.0,0.0,0.0
1,Q162959,Blake Lively,CHILD,-1,0,None,Q116869858,None,0.0,0.0,0.0,0.0,0.0,331.0,236.0,0.0,0.0
2,Q162959,Blake Lively,CHILD,-1,0,None,Q116869931,None,0.0,0.0,0.0,0.0,0.0,331.0,236.0,0.0,0.0
3,Q162959,Blake Lively,CHILD,-1,0,None,Q116869826,None,0.0,0.0,0.0,0.0,0.0,331.0,236.0,0.0,0.0
4,Q162959,Blake Lively,CHILD,-1,0,None,Q116869845,None,0.0,0.0,0.0,0.0,0.0,331.0,236.0,0.0,0.0
5,Q162959,Blake Lively,SIBLING,0,1,sibling,Q900783,Jason Lively,195.0,195.0,0.0,0.0,0.0,331.0,236.0,0.0,0.0
6,Q162959,Blake Lively,SIBLING,0,1,sibling,Q4253117,Lori Lively,59.0,59.0,0.0,0.0,0.0,331.0,236.0,0.0,0.0
7,Q162959,Blake Lively,SIBLING,0,1,sibling,Q469891,Robyn Lively,492.0,492.0,0.0,0.0,0.0,331.0,236.0,0.0,0.0
8,Q162959,Blake Lively,SIBLING,0,1,sibling,Q712936,Eric Lively,200.0,200.0,0.0,0.0,0.0,331.0,236.0,0.0,0.0

In [ ]:
nepo_breakdown('Q116869845') #James Reynolds (Q116869845)

,person_id,person_name,kinship,relationship,related_person_id,related_person_name,person_point,person_movie_point,person_award_point,kinship_weight,contribution,person_nepo_score,parent_score,grandparent_score,ancestor_score,relative_score
0,Q116869845,None,GRANDPARENT,None,Q4253122,Ernie Lively,236.0,236.0,0.0,0.5,118.0,3802.0,3684.0,118.0,0.0,0.0
1,Q116869845,None,PARENT,father,Q192682,Ryan Reynolds,3000.0,2930.0,70.0,1.0,3000.0,3802.0,3684.0,118.0,0.0,0.0
2,Q116869845,None,PARENT,mother,Q162959,Blake Lively,684.0,684.0,0.0,1.0,684.0,3802.0,3684.0,118.0,0.0,0.0
3,Q116869845,None,SIBLING,None,Q116869826,None,0.0,0.0,0.0,0.5,0.0,3802.0,3684.0,118.0,0.0,0.0
4,Q116869845,None,SIBLING,None,Q116869858,None,0.0,0.0,0.0,0.5,0.0,3802.0,3684.0,118.0,0.0,0.0
5,Q116869845,None,SIBLING,None,Q116869931,None,0.0,0.0,0.0,0.5,0.0,3802.0,3684.0,118.0,0.0,0.0

In [ ]:
nepo_breakdown('Q192682') #Ryan Reynolds

,person_id,person_name,kinship,relationship,related_person_id,related_person_name,person_point,person_movie_point,person_award_point,kinship_weight,contribution,person_nepo_score,parent_score,grandparent_score,ancestor_score,relative_score
0,Q192682,Ryan Reynolds,CHILD,None,Q116869826,None,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Q192682,Ryan Reynolds,CHILD,None,Q116869845,None,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Q192682,Ryan Reynolds,CHILD,None,Q116869858,None,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Q192682,Ryan Reynolds,CHILD,None,Q116869931,None,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# Robyn Lively (Q469891)
nepo_breakdown('Q469891')

,person_id,person_name,kinship,relationship,related_person_id,related_person_name,person_point,person_movie_point,person_award_point,kinship_weight,contribution,person_nepo_score,parent_score,grandparent_score,ancestor_score,relative_score
0,Q469891,Robyn Lively,SIBLING,sibling,Q162959,Blake Lively,684.0,684.0,0.0,0.5,342.0,0.0,0.0,0.0,0.0,0.0
1,Q469891,Robyn Lively,SIBLING,sibling,Q712936,Eric Lively,200.0,200.0,0.0,0.5,100.0,0.0,0.0,0.0,0.0,0.0
2,Q469891,Robyn Lively,SIBLING,sibling,Q900783,Jason Lively,195.0,195.0,0.0,0.5,97.0,0.0,0.0,0.0,0.0,0.0
3,Q469891,Robyn Lively,SIBLING,sibling,Q4253117,Lori Lively,59.0,59.0,0.0,0.5,30.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
%%sql 
select * from core.kinship where person_id = 'Q469891';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

4 rows affected.

+-----------+---------+-------------------+-----------+--------+---------+
| person_id | kinship | related_person_id | gen_delta | degree | lca_gen |
+-----------+---------+-------------------+-----------+--------+---------+
|  Q469891  | SIBLING |      Q162959      |     0     |   1    |    1    |
|  Q469891  | SIBLING |      Q4253117     |     0     |   1    |    1    |
|  Q469891  | SIBLING |      Q712936      |     0     |   1    |    1    |
|  Q469891  | SIBLING |      Q900783      |     0     |   1    |    1    |
+-----------+---------+-------------------+-----------+--------+---------+

In [ ]:
%%sql 
select * from raw.relative where personid like '%Q469891';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

+----------+------------+-----------+--------------+----------------+
| personid | relativeid | kinshipid | kinshiplabel | source_country |
+----------+------------+-----------+--------------+----------------+
+----------+------------+-----------+--------------+----------------+

### Dylan Farrow (Q100135417)

In [21]:
nepo_breakdown('Q100135417')

───────────────────────────────────────────────────────
  Dylan Farrow (Q100135417)
  Nepo score (stored): 9524.0
  Contribution sum   : 9499
  Relatives found    : 28
  Contributing (>0)  : 8
───────────────────────────────────────────────────────

,person_id,person_name,kinship,gen_delta,degree,raw_relationship,related_person_id,related_name,person_point,movie_point,award_point,kinship_weight,contribution,person_nepo_score,person_parent_score,person_grandparent_score,person_ancestor_score
0,Q100135417,Dylan Farrow,PARENT,1,0,father,Q25089,Woody Allen,6297.0,5945.0,352.0,1.00,6297.0,9524.0,7878.0,1368.0,0.0
1,Q100135417,Dylan Farrow,PARENT,1,0,mother,Q202725,Mia Farrow,1580.0,1537.0,43.0,1.00,1580.0,9524.0,7878.0,1368.0,0.0
2,Q100135417,Dylan Farrow,GRANDPARENT,2,0,None,Q230084,Maureen O'Sullivan,1478.0,1468.0,10.0,0.50,739.0,9524.0,7878.0,1368.0,0.0
3,Q100135417,Dylan Farrow,GRANDPARENT,2,0,None,Q547495,John Farrow,1231.0,1188.0,43.0,0.50,615.0,9524.0,7878.0,1368.0,0.0
4,Q100135417,Dylan Farrow,GRANDPARENT,2,0,None,Q108223445,Nettie Königsberg,28.0,28.0,0.0,0.50,14.0,9524.0,7878.0,1368.0,0.0
5,Q100135417,Dylan Farrow,GRANDPARENT,2,0,None,Q108223439,None,0.0,0.0,0.0,0.50,0.0,9524.0,7878.0,1368.0,0.0
6,Q100135417,Dylan Farrow,AUNT_UNCLE,1,1,None,Q3831197,Letty Aronson,666.0,653.0,13.0,0.25,166.0,9524.0,7878.0,1368.0,0.0
7,Q100135417,Dylan Farrow,AUNT_UNCLE,1,1,None,Q3991790,Tisa Farrow,280.0,280.0,0.0,0.25,70.0,9524.0,7878.0,1368.0,0.0
8,Q100135417,Dylan Farrow,AUNT_UNCLE,1,1,None,Q7608277,Stephanie Farrow,72.0,72.0,0.0,0.25,18.0,9524.0,7878.0,1368.0,0.0
9,Q100135417,Dylan Farrow,ANCESTOR,3,0,None,Q98700276,None,0.0,0.0,0.0,0.25,0.0,9524.0,7878.0,1368.0,0.0
10,Q100135417,Dylan Farrow,ANCESTOR,3,0,None,Q108223448,None,0.0,0.0,0.0,0.25,0.0,9524.0,7878.0,1368.0,0.0
11,Q100135417,Dylan Farrow,ANCESTOR,3,0,None,Q98700213,None,0.0,0.0,0.0,0.25,0.0,9524.0,7878.0,1368.0,0.0
12,Q100135417,Dylan Farrow,ANCESTOR,3,0,None,Q98700233,None,0.0,0.0,0.0,0.25,0.0,9524.0,7878.0,1368.0,0.0
13,Q100135417,Dylan Farrow,ANCESTOR,3,0,None,Q98700266,None,0.0,0.0,0.0,0.25,0.0,9524.0,7878.0,1368.0,0.0
14,Q100135417,Dylan Farrow,AUNT_UNCLE,1,1,None,Q18387067,None,0.0,0.0,0.0,0.25,0.0,9524.0,7878.0,1368.0,0.0
15,Q100135417,Dylan Farrow,AUNT_UNCLE,1,1,None,Q7252957,Prudence Farrow,0.0,0.0,0.0,0.25,0.0,9524.0,7878.0,1368.0,0.0
16,Q100135417,Dylan Farrow,SIBLING,0,1,None,Q22673707,None,0.0,0.0,0.0,0.00,0.0,9524.0,7878.0,1368.0,0.0
17,Q100135417,Dylan Farrow,SIBLING,0,1,sibling,Q16217493,Moses Farrow,0.0,0.0,0.0,0.00,0.0,9524.0,7878.0,1368.0,0.0
18,Q100135417,Dylan Farrow,SIBLING,0,1,sibling,Q7365461,Ronan Farrow,165.0,125.0,40.0,0.00,0.0,9524.0,7878.0,1368.0,0.0
19,Q100135417,Dylan Farrow,SIBLING,0,1,None,Q75624453,None,0.0,0.0,0.0,0.00,0.0,9524.0,7878.0,1368.0,0.0
20,Q100135417,Dylan Farrow,SIBLING,0,1,sibling,Q1140914,Soon-Yi Previn,32.0,32.0,0.0,0.00,0.0,9524.0,7878.0,1368.0,0.0
21,Q100135417,Dylan Farrow,SIBLING,0,1,None,Q22673708,None,0.0,0.0,0.0,0.00,0.0,9524.0,7878.0,1368.0,0.0
22,Q100135417,Dylan Farrow,STEPSIBLING,1,11,None,Q273532,Louise Lasser,550.0,550.0,0.0,0.00,0.0,9524.0,7878.0,1368.0,0.0
23,Q100135417,Dylan Farrow,STEPSIBLING,0,11,None,Q1349639,Frank Sinatra Jr.,85.0,85.0,0.0,0.00,0.0,9524.0,7878.0,1368.0,0.0
24,Q100135417,Dylan Farrow,STEPSIBLING,0,11,None,Q545438,Tina Sinatra,53.0,53.0,0.0,0.00,0.0,9524.0,7878.0,1368.0,0.0
25,Q100135417,Dylan Farrow,STEPSIBLING,1,11,None,Q155712,André Previn,827.0,711.0,116.0,0.00,0.0,9524.0,7878.0,1368.0,0.0
26,Q100135417,Dylan Farrow,STEPSIBLING,1,11,None,Q40912,Frank Sinatra,1909.0,1696.0,213.0,0.00,0.0,9524.0,7878.0,1368.0,0.0
27,Q100135417,Dylan Farrow,STEPSIBLING,0,11,None,Q233937,Nancy Sinatra,217.0,207.0,10.0,0.00,0.0,9524.0,7878.0,1368.0,0.0

In [ ]:
nepo_breakdown('Q25089')

,person_id,person_name,kinship,relationship,related_person_id,related_person_name,person_point,person_movie_point,person_award_point,kinship_weight,contribution,person_nepo_score,parent_score,grandparent_score,ancestor_score,relative_score
0,Q25089,Woody Allen,CHILD,None,Q7365461,Ronan Farrow,165.0,125.0,40.0,1.0,165.0,28.0,28.0,0.0,0.0,0.0
1,Q25089,Woody Allen,CHILD,None,Q100135417,Dylan Farrow,49.0,49.0,0.0,1.0,49.0,28.0,28.0,0.0,0.0,0.0
2,Q25089,Woody Allen,CHILD,None,Q22673707,None,0.0,0.0,0.0,1.0,0.0,28.0,28.0,0.0,0.0,0.0
3,Q25089,Woody Allen,CHILD,None,Q16217493,Moses Farrow,0.0,0.0,0.0,1.0,0.0,28.0,28.0,0.0,0.0,0.0
4,Q25089,Woody Allen,CHILD,None,Q22673708,None,0.0,0.0,0.0,1.0,0.0,28.0,28.0,0.0,0.0,0.0
5,Q25089,Woody Allen,GRANDPARENT,None,Q108223448,None,0.0,0.0,0.0,0.5,0.0,28.0,28.0,0.0,0.0,0.0
6,Q25089,Woody Allen,PARENT,mother,Q108223445,Nettie Königsberg,28.0,28.0,0.0,1.0,28.0,28.0,28.0,0.0,0.0,0.0
7,Q25089,Woody Allen,PARENT,father,Q108223439,None,0.0,0.0,0.0,1.0,0.0,28.0,28.0,0.0,0.0,0.0
8,Q25089,Woody Allen,SIBLING,sibling,Q3831197,Letty Aronson,666.0,653.0,13.0,0.5,333.0,28.0,28.0,0.0,0.0,0.0

### Kendall Jenner (Q1375057)

In [20]:
nepo_breakdown('Q1375057')

───────────────────────────────────────────────────────
  Kendall Jenner (Q1375057)
  Nepo score (stored): 628.0
  Contribution sum   : 479
  Relatives found    : 30
  Contributing (>0)  : 2
───────────────────────────────────────────────────────

,person_id,person_name,kinship,gen_delta,degree,raw_relationship,related_person_id,related_name,person_point,movie_point,award_point,kinship_weight,contribution,person_nepo_score,person_parent_score,person_grandparent_score,person_ancestor_score
0,Q1375057,Kendall Jenner,PARENT,1,0,father,Q365144,Caitlyn Jenner,273.0,240.0,33.0,1.0,273.0,628.0,479.0,0.0,0.0
1,Q1375057,Kendall Jenner,PARENT,1,0,mother,Q1138235,Kris Jenner,206.0,196.0,10.0,1.0,206.0,628.0,479.0,0.0,0.0
2,Q1375057,Kendall Jenner,GRANDPARENT,2,0,None,Q107323569,None,0.0,0.0,0.0,0.5,0.0,628.0,479.0,0.0,0.0
3,Q1375057,Kendall Jenner,GRANDPARENT,2,0,None,Q99952140,None,0.0,0.0,0.0,0.5,0.0,628.0,479.0,0.0,0.0
4,Q1375057,Kendall Jenner,GRANDPARENT,2,0,None,Q54997217,None,0.0,0.0,0.0,0.5,0.0,628.0,479.0,0.0,0.0
5,Q1375057,Kendall Jenner,NIECE_NEPHEW,-1,1,None,Q48016876,None,0.0,0.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
6,Q1375057,Kendall Jenner,NIECE_NEPHEW,-1,1,None,Q108091581,None,0.0,0.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
7,Q1375057,Kendall Jenner,NIECE_NEPHEW,-1,1,None,Q108091648,None,0.0,0.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
8,Q1375057,Kendall Jenner,NIECE_NEPHEW,-1,1,None,Q110994323,None,0.0,0.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
9,Q1375057,Kendall Jenner,NIECE_NEPHEW,-1,1,None,Q132158413,None,0.0,0.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
10,Q1375057,Kendall Jenner,NIECE_NEPHEW,-1,1,None,Q55428718,North West,0.0,0.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
11,Q1375057,Kendall Jenner,NIECE_NEPHEW,-1,1,None,Q55428786,None,0.0,0.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
12,Q1375057,Kendall Jenner,NIECE_NEPHEW,-1,1,None,Q56034652,None,0.0,0.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
13,Q1375057,Kendall Jenner,NIECE_NEPHEW,-1,1,None,Q59532027,Mason Dash Disick,39.0,39.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
14,Q1375057,Kendall Jenner,NIECE_NEPHEW,-1,1,None,Q59532183,None,0.0,0.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
15,Q1375057,Kendall Jenner,NIECE_NEPHEW,-1,1,None,Q59532283,None,0.0,0.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
16,Q1375057,Kendall Jenner,NIECE_NEPHEW,-1,1,None,Q59532454,None,0.0,0.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
17,Q1375057,Kendall Jenner,NIECE_NEPHEW,-1,1,None,Q59534229,None,0.0,0.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
18,Q1375057,Kendall Jenner,NIECE_NEPHEW,-1,1,None,Q63927876,None,0.0,0.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
19,Q1375057,Kendall Jenner,SIBLING,0,1,sibling,Q575689,Kourtney Kardashian,214.0,214.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
20,Q1375057,Kendall Jenner,SIBLING,0,1,None,Q107323598,None,0.0,0.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
21,Q1375057,Kendall Jenner,SIBLING,0,1,sibling,Q16209581,Brandon Jenner,31.0,31.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
22,Q1375057,Kendall Jenner,SIBLING,0,1,sibling,Q554091,Brody Jenner,98.0,98.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
23,Q1375057,Kendall Jenner,SIBLING,0,1,sibling,Q186304,Kim Kardashian,590.0,580.0,10.0,0.0,0.0,628.0,479.0,0.0,0.0
24,Q1375057,Kendall Jenner,SIBLING,0,1,sibling,Q231270,Khloé Kardashian,307.0,307.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
25,Q1375057,Kendall Jenner,SIBLING,0,1,sibling,Q26318,Rob Kardashian,65.0,65.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
26,Q1375057,Kendall Jenner,SIBLING,0,1,sibling,Q1770624,Kylie Jenner,184.0,184.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
27,Q1375057,Kendall Jenner,SIBLING,0,1,None,Q106554522,Burt Jenner,0.0,0.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
28,Q1375057,Kendall Jenner,STEPSIBLING,1,11,None,Q1816737,Robert Kardashian,14.0,14.0,0.0,0.0,0.0,628.0,479.0,0.0,0.0
29,Q1375057,Kendall Jenner,STEPSIBLING,1,11,None,Q780846,Linda Thompson,103.0,80.0,23.0,0.0,0.0,628.0,479.0,0.0,0.0

In [ ]:
%%sql
select * from core.kinship_old where person_id = 'Q1375057';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

5 rows affected.

+-----------+-------------+-------------------+
| person_id |   kinship   | related_person_id |
+-----------+-------------+-------------------+
|  Q1375057 | GRANDPARENT |     Q107323569    |
|  Q1375057 |    PARENT   |      Q1138235     |
|  Q1375057 |    PARENT   |      Q365144      |
|  Q1375057 | GRANDPARENT |     Q54997217     |
|  Q1375057 | GRANDPARENT |     Q99952140     |
+-----------+-------------+-------------------+

### Kim Kardashian (Q186304, nm2578007)

In [19]:
nepo_breakdown('Q186304')

───────────────────────────────────────────────────────
  Kim Kardashian (Q186304)
  Nepo score (stored): 317.0
  Contribution sum   : 220
  Relatives found    : 30
  Contributing (>0)  : 2
───────────────────────────────────────────────────────

,person_id,person_name,kinship,gen_delta,degree,raw_relationship,related_person_id,related_name,person_point,movie_point,award_point,kinship_weight,contribution,person_nepo_score,person_parent_score,person_grandparent_score,person_ancestor_score
0,Q186304,Kim Kardashian,PARENT,1,0,mother,Q1138235,Kris Jenner,206.0,196.0,10.0,1.0,206.0,317.0,220.0,0.0,0.0
1,Q186304,Kim Kardashian,PARENT,1,0,father,Q1816737,Robert Kardashian,14.0,14.0,0.0,1.0,14.0,317.0,220.0,0.0,0.0
2,Q186304,Kim Kardashian,GRANDPARENT,2,0,None,Q102047927,None,0.0,0.0,0.0,0.5,0.0,317.0,220.0,0.0,0.0
3,Q186304,Kim Kardashian,GRANDPARENT,2,0,None,Q102047932,None,0.0,0.0,0.0,0.5,0.0,317.0,220.0,0.0,0.0
4,Q186304,Kim Kardashian,GRANDPARENT,2,0,None,Q54997217,None,0.0,0.0,0.0,0.5,0.0,317.0,220.0,0.0,0.0
5,Q186304,Kim Kardashian,GRANDPARENT,2,0,None,Q99952140,None,0.0,0.0,0.0,0.5,0.0,317.0,220.0,0.0,0.0
6,Q186304,Kim Kardashian,CHILD,-1,0,None,Q55428718,North West,0.0,0.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
7,Q186304,Kim Kardashian,CHILD,-1,0,None,Q63927876,None,0.0,0.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
8,Q186304,Kim Kardashian,CHILD,-1,0,None,Q56034652,None,0.0,0.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
9,Q186304,Kim Kardashian,CHILD,-1,0,None,Q55428786,None,0.0,0.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
10,Q186304,Kim Kardashian,COUSIN_1ST_1R_DOWN,-1,2,None,Q108091648,None,0.0,0.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
11,Q186304,Kim Kardashian,COUSIN_1ST_1R_DOWN,-1,2,None,Q108091581,None,0.0,0.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
12,Q186304,Kim Kardashian,NIECE_NEPHEW,-1,1,None,Q110994323,None,0.0,0.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
13,Q186304,Kim Kardashian,NIECE_NEPHEW,-1,1,None,Q132158413,None,0.0,0.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
14,Q186304,Kim Kardashian,NIECE_NEPHEW,-1,1,None,Q48016876,None,0.0,0.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
15,Q186304,Kim Kardashian,NIECE_NEPHEW,-1,1,None,Q59532027,Mason Dash Disick,39.0,39.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
16,Q186304,Kim Kardashian,NIECE_NEPHEW,-1,1,None,Q59532183,None,0.0,0.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
17,Q186304,Kim Kardashian,NIECE_NEPHEW,-1,1,None,Q59532283,None,0.0,0.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
18,Q186304,Kim Kardashian,NIECE_NEPHEW,-1,1,None,Q59532454,None,0.0,0.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
19,Q186304,Kim Kardashian,NIECE_NEPHEW,-1,1,None,Q59534229,None,0.0,0.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
20,Q186304,Kim Kardashian,SIBLING,0,1,sibling,Q575689,Kourtney Kardashian,214.0,214.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
21,Q186304,Kim Kardashian,SIBLING,0,1,sibling,Q1375057,Kendall Jenner,196.0,176.0,20.0,0.0,0.0,317.0,220.0,0.0,0.0
22,Q186304,Kim Kardashian,SIBLING,0,1,sibling,Q231270,Khloé Kardashian,307.0,307.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
23,Q186304,Kim Kardashian,SIBLING,0,1,sibling,Q26318,Rob Kardashian,65.0,65.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
24,Q186304,Kim Kardashian,SIBLING,0,1,sibling,Q1770624,Kylie Jenner,184.0,184.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
25,Q186304,Kim Kardashian,STEPSIBLING,0,11,None,Q106554522,Burt Jenner,0.0,0.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
26,Q186304,Kim Kardashian,STEPSIBLING,0,11,None,Q16209581,Brandon Jenner,31.0,31.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
27,Q186304,Kim Kardashian,STEPSIBLING,0,11,None,Q107323598,None,0.0,0.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0
28,Q186304,Kim Kardashian,STEPSIBLING,1,11,None,Q365144,Caitlyn Jenner,273.0,240.0,33.0,0.0,0.0,317.0,220.0,0.0,0.0
29,Q186304,Kim Kardashian,STEPSIBLING,0,11,None,Q554091,Brody Jenner,98.0,98.0,0.0,0.0,0.0,317.0,220.0,0.0,0.0

In [ ]:
%%sql
SELECT * from core.kinship_old where person_id = 'Q186304';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

6 rows affected.

+-----------+-------------+-------------------+
| person_id |   kinship   | related_person_id |
+-----------+-------------+-------------------+
|  Q186304  | GRANDPARENT |     Q102047927    |
|  Q186304  | GRANDPARENT |     Q102047932    |
|  Q186304  |    PARENT   |      Q1138235     |
|  Q186304  |    PARENT   |      Q1816737     |
|  Q186304  | GRANDPARENT |     Q54997217     |
|  Q186304  | GRANDPARENT |     Q99952140     |
+-----------+-------------+-------------------+

In [ ]:
%%sql
SELECT
    pmp.person_id,
    pmp.tconst,
    pmp.primary_title,
    pmp.ordering,
    pmp.ordering_weight,
    pmp.movie_point,
    pmp.weighted_point,
    r.average_rating,
    r.num_votes
FROM core.personmoviepoint pmp
LEFT JOIN core.rating r ON r.tconst = pmp.tconst
WHERE pmp.person_id = 'Q186304'
ORDER BY pmp.weighted_point DESC;

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

50 rows affected.

+-----------+------------+----------------------------------------------------------+----------+-----------------+-------------+----------------+----------------+-----------+
| person_id |   tconst   |                      primary_title                       | ordering | ordering_weight | movie_point | weighted_point | average_rating | num_votes |
+-----------+------------+----------------------------------------------------------+----------+-----------------+-------------+----------------+----------------+-----------+
|  Q186304  | tt15791630 |                     The Kardashians                      |    1     |        0        |      37     |       8        |      4.5       |    6259   |
|  Q186304  | tt2726286  |            Kim Kardashian: The Fabulous Life             |    1     |        1        |      7      |       7        |      2.2       |     44    |
|  Q186304  | tt37272587 |             The Kim Kardashian Diamond Heist             |    1     |        1        |      9      |       6        |      3.1       |    103    |
|  Q186304  | tt7829834  | My Next Guest Needs No Introduction with David Letterman |    3     |        0        |      33     |       5        |      7.8       |    6580   |
|  Q186304  | tt31079920 |            Elizabeth Taylor: Rebel Superstar             |    2     |        0        |      20     |       4        |      7.6       |    195    |
|  Q186304  | tt15036422 |                    Cooking with Paris                    |    2     |        0        |      20     |       4        |      5.4       |    1277   |
|  Q186304  | tt0276656  |                          Cribs                           |    2     |        0        |      20     |       4        |      5.2       |    1993   |
|  Q186304  | tt30291387 |                        All's Fair                        |    1     |        0        |      17     |       3        |      3.5       |   10865   |
|  Q186304  | tt2070862  |     Temptation: Confessions of a Marriage Counselor      |    4     |        0        |      24     |       3        |      5.0       |   12709   |
|  Q186304  | tt1821879  |               Kourtney & Kim Take New York               |    1     |        0        |      14     |       3        |      3.3       |    2684   |
+-----------+------------+----------------------------------------------------------+----------+-----------------+-------------+----------------+----------------+-----------+
Truncated to displaylimit of 10.

In [ ]:
%%sql
SELECT * from core.kinship k
                  LEFT JOIN core.personpoint pp on pp.person_id = k.related_person_id
where k.person_id = 'Q186304'
order by kinship ;

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

15 rows affected.

+-----------+-------------+-------------------+-----------+--------+---------+-------------+-------------------------------------------+-------------------------------------------+--------------------+
| person_id |   kinship   | related_person_id | gen_delta | degree | lca_gen | person_id_1 |                person_point               |             person_movie_point            | person_award_point |
+-----------+-------------+-------------------+-----------+--------+---------+-------------+-------------------------------------------+-------------------------------------------+--------------------+
|  Q186304  |    CHILD    |     Q55428786     |     -1    |   0    |    0    |     None    |                    None                   |                    None                   |        None        |
|  Q186304  |    CHILD    |     Q55428718     |     -1    |   0    |    0    |  Q55428718  |                     0                     |                     0                     |         0          |
|  Q186304  |    CHILD    |     Q63927876     |     -1    |   0    |    0    |     None    |                    None                   |                    None                   |        None        |
|  Q186304  |    CHILD    |     Q56034652     |     -1    |   0    |    0    |     None    |                    None                   |                    None                   |        None        |
|  Q186304  | GRANDPARENT |     Q102047927    |     2     |   0    |    2    |     None    |                    None                   |                    None                   |        None        |
|  Q186304  | GRANDPARENT |     Q102047932    |     2     |   0    |    2    |     None    |                    None                   |                    None                   |        None        |
|  Q186304  | GRANDPARENT |     Q54997217     |     2     |   0    |    2    |     None    |                    None                   |                    None                   |        None        |
|  Q186304  | GRANDPARENT |     Q99952140     |     2     |   0    |    2    |     None    |                    None                   |                    None                   |        None        |
|  Q186304  |    PARENT   |      Q1138235     |     1     |   0    |    1    |   Q1138235  | 205.8283661162540626924708175613448685182 | 195.8283661162540626924708175613448685182 |         10         |
|  Q186304  |    PARENT   |      Q1816737     |     1     |   0    |    1    |   Q1816737  |  13.8968746327804739307020724029983763630 |  13.8968746327804739307020724029983763630 |         0          |
+-----------+-------------+-------------------+-----------+--------+---------+-------------+-------------------------------------------+-------------------------------------------+--------------------+
Truncated to displaylimit of 10.

In [ ]:
%%sql
SELECT
    k.person_id,
    p1.name                         AS person_name,
    ns.nepo_score                   AS person_nepo_score,
    k.kinship,
    k.related_person_id,
    p2.name                         AS related_person_name,
    COALESCE(pp.person_point, 0)    AS related_person_point,
    CASE
        WHEN k.kinship = 'PARENT'      THEN 1.0
        WHEN k.kinship = 'GRANDPARENT' THEN 0.5
        WHEN k.kinship = 'ANCESTOR'    THEN 0.25
        WHEN k.kinship = 'SAMEGEN'     THEN 0.25
        WHEN k.kinship = 'RELATIVE'    THEN 0.1
        WHEN k.kinship = 'LOWERGEN'    THEN 0.0
        ELSE 0.1
    END                             AS kinship_weight,
    COALESCE(pp.person_point, 0) *
    CASE
        WHEN k.kinship = 'PARENT'      THEN 1.0
        WHEN k.kinship = 'GRANDPARENT' THEN 0.5
        WHEN k.kinship = 'ANCESTOR'    THEN 0.25
        WHEN k.kinship = 'SAMEGEN'     THEN 0.25
        WHEN k.kinship = 'RELATIVE'    THEN 0.1
        WHEN k.kinship = 'LOWERGEN'    THEN 0.0
        ELSE 0.1
    END                             AS contribution
FROM core.kinship k
JOIN core.person p1   ON p1.person_id = k.person_id
JOIN core.person p2   ON p2.person_id = k.related_person_id
LEFT JOIN core.personpoint pp ON pp.person_id = k.related_person_id
LEFT JOIN core.neposcore ns   ON ns.person_id = k.person_id
WHERE k.person_id = 'Q186304'
#   AND k.kinship <> 'LOWERGEN'
ORDER BY contribution DESC;

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

8 rows affected.

+-----------+----------------+-------------------+---------+-------------------+---------------------+-------------------------------------------+----------------+--------------------------------------------+
| person_id |  person_name   | person_nepo_score | kinship | related_person_id | related_person_name |            related_person_point           | kinship_weight |                contribution                |
+-----------+----------------+-------------------+---------+-------------------+---------------------+-------------------------------------------+----------------+--------------------------------------------+
|  Q186304  | Kim Kardashian |       219.73      |  PARENT |      Q1138235     |     Kris Jenner     | 205.8283661162540626924708175613448685182 |      1.0       | 205.82836611625406269247081756134486851820 |
|  Q186304  | Kim Kardashian |       219.73      | SIBLING |      Q231270      |   Khloé Kardashian  | 307.3581776715988708265961386373433747225 |      0.1       | 30.73581776715988708265961386373433747225  |
|  Q186304  | Kim Kardashian |       219.73      | SIBLING |      Q575689      | Kourtney Kardashian | 213.8563874043375972339640829743472856725 |      0.1       | 21.38563874043375972339640829743472856725  |
|  Q186304  | Kim Kardashian |       219.73      | SIBLING |      Q1375057     |    Kendall Jenner   | 196.2367919458949435138791723838471593968 |      0.1       | 19.62367919458949435138791723838471593968  |
|  Q186304  | Kim Kardashian |       219.73      | SIBLING |      Q1770624     |     Kylie Jenner    | 183.9238178124971491577509894183658335684 |      0.1       | 18.39238178124971491577509894183658335684  |
|  Q186304  | Kim Kardashian |       219.73      |  PARENT |      Q1816737     |  Robert Kardashian  |  13.8968746327804739307020724029983763630 |      1.0       | 13.89687463278047393070207240299837636300  |
|  Q186304  | Kim Kardashian |       219.73      | SIBLING |       Q26318      |    Rob Kardashian   |  64.8710025228738011505695464089537304860 |      0.1       |  6.48710025228738011505695464089537304860  |
|  Q186304  | Kim Kardashian |       219.73      |  CHILD  |     Q55428718     |      North West     |                     0                     |      0.1       |                    0.0                     |
+-----------+----------------+-------------------+---------+-------------------+---------------------+-------------------------------------------+----------------+--------------------------------------------+

### Arnold Schwarzenegger (Q2685)

In [ ]:
nepo_breakdown('Q2685')

,person_id,person_name,kinship,relationship,related_person_id,related_person_name,person_point,person_movie_point,person_award_point,kinship_weight,contribution,person_nepo_score,parent_score,grandparent_score,ancestor_score,relative_score
0,Q2685,Arnold Schwarzenegger,CHILD,None,Q901541,Patrick Schwarzenegger,194.0,194.0,0.0,1.0,194.0,0.0,0.0,0.0,0.0,0.0
1,Q2685,Arnold Schwarzenegger,CHILD,None,Q4521676,Katherine Schwarzenegger,33.0,33.0,0.0,1.0,33.0,0.0,0.0,0.0,0.0,0.0
2,Q2685,Arnold Schwarzenegger,CHILD,None,Q28109921,Christina Schwarzenegger,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Q2685,Arnold Schwarzenegger,CHILD,None,Q28109928,None,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Q2685,Arnold Schwarzenegger,GRANDCHILD,None,Q112833739,Eloise Christina Schwarzenegger Pratt,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0
5,Q2685,Arnold Schwarzenegger,GRANDCHILD,None,Q133809411,Ford Pratt,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0
6,Q2685,Arnold Schwarzenegger,GRANDCHILD,None,Q133809424,None,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0
7,Q2685,Arnold Schwarzenegger,PARENT,father,Q3288486,None,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8,Q2685,Arnold Schwarzenegger,PARENT,mother,Q23800370,None,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

### Ford Pratt (Q133809411)

In [ ]:
nepo_breakdown('Q133809411')

,person_id,person_name,kinship,relationship,related_person_id,related_person_name,person_point,person_movie_point,person_award_point,kinship_weight,contribution,person_nepo_score,parent_score,grandparent_score,ancestor_score,relative_score
0,Q133809411,Ford Pratt,ANCESTOR,None,Q272908,Eunice Kennedy Shriver,224.0,64.0,160.0,0.25,56.0,3266.0,1940.0,1260.0,66.0,0.0
1,Q133809411,Ford Pratt,ANCESTOR,None,Q313696,Joseph P. Kennedy Sr.,30.0,30.0,0.0,0.25,7.0,3266.0,1940.0,1260.0,66.0,0.0
2,Q133809411,Ford Pratt,ANCESTOR,None,Q236540,Rose Kennedy,10.0,10.0,0.0,0.25,3.0,3266.0,1940.0,1260.0,66.0,0.0
3,Q133809411,Ford Pratt,ANCESTOR,None,Q96077740,None,0.0,0.0,0.0,0.25,0.0,3266.0,1940.0,1260.0,66.0,0.0
4,Q133809411,Ford Pratt,ANCESTOR,None,Q3288486,None,0.0,0.0,0.0,0.25,0.0,3266.0,1940.0,1260.0,66.0,0.0
5,Q133809411,Ford Pratt,ANCESTOR,None,Q317248,None,0.0,0.0,0.0,0.25,0.0,3266.0,1940.0,1260.0,66.0,0.0
6,Q133809411,Ford Pratt,ANCESTOR,None,Q23800370,None,0.0,0.0,0.0,0.25,0.0,3266.0,1940.0,1260.0,66.0,0.0
7,Q133809411,Ford Pratt,ANCESTOR,None,Q96077739,None,0.0,0.0,0.0,0.25,0.0,3266.0,1940.0,1260.0,66.0,0.0
8,Q133809411,Ford Pratt,AUNT_UNCLE,None,Q75326829,Robert F. Kennedy III,77.0,77.0,0.0,0.25,19.0,3266.0,1940.0,1260.0,66.0,0.0
9,Q133809411,Ford Pratt,AUNT_UNCLE,None,Q15149340,Jack Schlossberg,3.0,3.0,0.0,0.25,1.0,3266.0,1940.0,1260.0,66.0,0.0
10,Q133809411,Ford Pratt,AUNT_UNCLE,None,Q1707784,Joe Kennedy III,3.0,3.0,0.0,0.25,1.0,3266.0,1940.0,1260.0,66.0,0.0
11,Q133809411,Ford Pratt,AUNT_UNCLE,None,Q66108091,None,0.0,0.0,0.0,0.25,0.0,3266.0,1940.0,1260.0,66.0,0.0
12,Q133809411,Ford Pratt,AUNT_UNCLE,None,Q104127085,None,0.0,0.0,0.0,0.25,0.0,3266.0,1940.0,1260.0,66.0,0.0
13,Q133809411,Ford Pratt,AUNT_UNCLE,None,Q104127116,None,0.0,0.0,0.0,0.25,0.0,3266.0,1940.0,1260.0,66.0,0.0
14,Q133809411,Ford Pratt,AUNT_UNCLE,None,Q112972338,None,0.0,0.0,0.0,0.25,0.0,3266.0,1940.0,1260.0,66.0,0.0
15,Q133809411,Ford Pratt,AUNT_UNCLE,None,Q21012764,Rose Schlossberg,0.0,0.0,0.0,0.25,0.0,3266.0,1940.0,1260.0,66.0,0.0
16,Q133809411,Ford Pratt,AUNT_UNCLE,None,Q21012765,None,0.0,0.0,0.0,0.25,0.0,3266.0,1940.0,1260.0,66.0,0.0
17,Q133809411,Ford Pratt,AUNT_UNCLE,None,Q24550652,None,0.0,0.0,0.0,0.25,0.0,3266.0,1940.0,1260.0,66.0,0.0
18,Q133809411,Ford Pratt,AUNT_UNCLE,None,Q61440298,None,0.0,0.0,0.0,0.25,0.0,3266.0,1940.0,1260.0,66.0,0.0
19,Q133809411,Ford Pratt,AUNT_UNCLE,None,Q104127073,None,0.0,0.0,0.0,0.25,0.0,3266.0,1940.0,1260.0,66.0,0.0
20,Q133809411,Ford Pratt,AUNT_UNCLE,None,Q75326815,None,0.0,0.0,0.0,0.25,0.0,3266.0,1940.0,1260.0,66.0,0.0
21,Q133809411,Ford Pratt,AUNT_UNCLE,None,Q75326830,None,0.0,0.0,0.0,0.25,0.0,3266.0,1940.0,1260.0,66.0,0.0
22,Q133809411,Ford Pratt,GRANDPARENT,grandfather,Q2685,Arnold Schwarzenegger,2399.0,2206.0,193.0,0.50,1199.0,3266.0,1940.0,1260.0,66.0,0.0
23,Q133809411,Ford Pratt,GRANDPARENT,grandmother,Q230654,Maria Shriver,122.0,102.0,20.0,0.50,61.0,3266.0,1940.0,1260.0,66.0,0.0
24,Q133809411,Ford Pratt,GRANDPARENT,None,Q135703714,None,0.0,0.0,0.0,0.50,0.0,3266.0,1940.0,1260.0,66.0,0.0
25,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q3048622,Edward M. Kennedy Jr.,10.0,0.0,10.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
26,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q1386420,Joseph P. Kennedy II,11.0,11.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
27,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q316064,John F. Kennedy Jr.,107.0,107.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
28,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q1352872,Robert F. Kennedy Jr.,487.0,477.0,10.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
29,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q3290402,None,0.0,0.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
30,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q3568759,None,0.0,0.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
31,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q467861,Kathleen Kennedy Townsend,110.0,110.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
32,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q467912,Kerry Kennedy,36.0,36.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
33,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q1086823,Christopher Lawford,240.0,240.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
34,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q1804720,Michael LeMoyne Kennedy,23.0,23.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
35,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q273833,Rory Kennedy,610.0,597.0,13.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
36,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q75326792,None,0.0,0.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
37,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q75326795,None,0.0,0.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
38,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q230303,Caroline Kennedy,119.0,89.0,30.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
39,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q1975383,David A. Kennedy,0.0,0.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
40,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q2383370,Kara Kennedy,0.0,0.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
41,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q5112377,None,0.0,0.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
42,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q5178632,None,0.0,0.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
43,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q5301573,Douglas Harriman Kennedy,0.0,0.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
44,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q75326840,None,0.0,0.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
45,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q948920,Patrick J. Kennedy,6.0,6.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
46,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q6794923,Max Kennedy,0.0,0.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
47,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q75326753,None,0.0,0.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
48,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q75326777,None,0.0,0.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
49,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q75326779,None,0.0,0.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
50,Q133809411,Ford Pratt,GREAT_AUNT_UNCLE,None,Q75326780,None,0.0,0.0,0.0,0.00,0.0,3266.0,1940.0,1260.0,66.0,0.0
51,Q133809411,Ford Pratt,PARENT,father,Q503706,Chris Pratt,1907.0,1887.0,20.0,1.00,1907.0,3266.0,1940.0,1260.0,66.0,0.0
52,Q133809411,Ford Pratt,PARENT,mother,Q4521676,Katherine Schwarzenegger,33.0,33.0,0.0,1.00,33.0,3266.0,1940.0,1260.0,66.0,0.0
53,Q133809411,Ford Pratt,SIBLING,sibling,Q112833739,Eloise Christina Schwarzenegger Pratt,0.0,0.0,0.0,0.50,0.0,3266.0,1940.0,1260.0,66.0,0.0
54,Q133809411,Ford Pratt,SIBLING,None,Q133809424,None,0.0,0.0,0.0,0.50,0.0,3266.0,1940.0,1260.0,66.0,0.0
55,Q133809411,Ford Pratt,SIBLING,sibling,Q43100988,Jack Pratt,0.0,0.0,0.0,0.50,0.0,3266.0,1940.0,1260.0,66.0,0.0

In [ ]:
%%sql
select * from core.kinship 
left join core.person pp on pp.person_id = core.kinship.related_person_id
where person_id = 'Q133809411';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

RuntimeError: (psycopg2.errors.AmbiguousColumn) column reference "person_id" is ambiguous
LINE 3: where person_id = 'Q133809411';
              ^

[SQL: select * from core.kinship
left join core.person pp on pp.person_id = core.kinship.related_person_id
where person_id = 'Q133809411';]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
%%sql
Select * from core.neposcore where person_id = 'Q133809411';

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

1 rows affected.

+------------+------------+--------------+-------------------+----------------+---------------+----------------+
| person_id  | nepo_score | parent_score | grandparent_score | ancestor_score | samegen_score | relative_score |
+------------+------------+--------------+-------------------+----------------+---------------+----------------+
| Q133809411 |  3772.87   |   1939.76    |      1392.27      |      0.00      |      0.00     |     440.84     |
+------------+------------+--------------+-------------------+----------------+---------------+----------------+

In [ ]:
%%sql
SELECT k.* , p.name ,r.relationship from core.kinship k
left join core.person p on p.person_id = k.related_person_id
left join core.relationship r on r.person_id = k.person_id and r.related_person_id = k.related_person_id
where k.person_id = 'Q133809411'
order by kinship, relationship
;

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

74 rows affected.

+------------+-------------+-------------------+---------------------------------------+--------------+
| person_id  |   kinship   | related_person_id |                  name                 | relationship |
+------------+-------------+-------------------+---------------------------------------+--------------+
| Q133809411 | GRANDPARENT |       Q2685       |         Arnold Schwarzenegger         | grandfather  |
| Q133809411 | GRANDPARENT |      Q230654      |             Maria Shriver             | grandmother  |
| Q133809411 | GRANDPARENT |     Q96077739     |                  None                 |     None     |
| Q133809411 | GRANDPARENT |      Q3288486     |                  None                 |     None     |
| Q133809411 | GRANDPARENT |      Q317248      |                  None                 |     None     |
| Q133809411 | GRANDPARENT |      Q313696      |         Joseph P. Kennedy Sr.         |     None     |
| Q133809411 | GRANDPARENT |      Q272908      |         Eunice Kennedy Shriver        |     None     |
| Q133809411 | GRANDPARENT |     Q135703714    |                  None                 |     None     |
| Q133809411 | GRANDPARENT |     Q23800370     |                  None                 |     None     |
| Q133809411 | GRANDPARENT |      Q236540      |              Rose Kennedy             |     None     |
| Q133809411 | GRANDPARENT |     Q96077740     |                  None                 |     None     |
| Q133809411 |    PARENT   |      Q503706      |              Chris Pratt              |    father    |
| Q133809411 |    PARENT   |      Q4521676     |        Katherine Schwarzenegger       |    mother    |
| Q133809411 |   RELATIVE  |      Q901541      |         Patrick Schwarzenegger        |    uncle     |
| Q133809411 |   RELATIVE  |      Q1975383     |            David A. Kennedy           |     None     |
| Q133809411 |   RELATIVE  |     Q21012764     |            Rose Schlossberg           |     None     |
| Q133809411 |   RELATIVE  |     Q21012765     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |      Q230303      |            Caroline Kennedy           |     None     |
| Q133809411 |   RELATIVE  |      Q1707784     |            Joe Kennedy III            |     None     |
| Q133809411 |   RELATIVE  |     Q15149340     |            Jack Schlossberg           |     None     |
| Q133809411 |   RELATIVE  |     Q23800185     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |      Q1386420     |          Joseph P. Kennedy II         |     None     |
| Q133809411 |   RELATIVE  |      Q2383370     |              Kara Kennedy             |     None     |
| Q133809411 |   RELATIVE  |     Q24004771     |               Q24004771               |     None     |
| Q133809411 |   RELATIVE  |     Q24550652     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |       Q25310      |           Robert F. Kennedy           |     None     |
| Q133809411 |   RELATIVE  |      Q265595      |            Rosemary Kennedy           |     None     |
| Q133809411 |   RELATIVE  |      Q1352872     |         Robert F. Kennedy Jr.         |     None     |
| Q133809411 |   RELATIVE  |      Q268799      |           Kathleen Cavendish          |     None     |
| Q133809411 |   RELATIVE  |      Q272401      |           Jean Kennedy Smith          |     None     |
| Q133809411 |   RELATIVE  |      Q134549      |              Ted Kennedy              |     None     |
| Q133809411 |   RELATIVE  |      Q273833      |              Rory Kennedy             |     None     |
| Q133809411 |   RELATIVE  |     Q28109921     |        Christina Schwarzenegger       |     None     |
| Q133809411 |   RELATIVE  |     Q28109928     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |      Q3048622     |         Edward M. Kennedy Jr.         |     None     |
| Q133809411 |   RELATIVE  |      Q316064      |          John F. Kennedy Jr.          |     None     |
| Q133809411 |   RELATIVE  |     Q112972338    |                  None                 |     None     |
| Q133809411 |   RELATIVE  |       Q9696       |            John F. Kennedy            |     None     |
| Q133809411 |   RELATIVE  |     Q104127116    |                  None                 |     None     |
| Q133809411 |   RELATIVE  |     Q104127085    |                  None                 |     None     |
| Q133809411 |   RELATIVE  |      Q1804720     |        Michael LeMoyne Kennedy        |     None     |
| Q133809411 |   RELATIVE  |      Q3290402     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |      Q3436301     |             Bobby Shriver             |     None     |
| Q133809411 |   RELATIVE  |      Q3529079     |            Timothy Shriver            |     None     |
| Q133809411 |   RELATIVE  |      Q3568759     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |     Q38196234     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |      Q432694      |        Patricia Kennedy Lawford       |     None     |
| Q133809411 |   RELATIVE  |     Q104127073    |                  None                 |     None     |
| Q133809411 |   RELATIVE  |      Q467861      |       Kathleen Kennedy Townsend       |     None     |
| Q133809411 |   RELATIVE  |      Q467912      |             Kerry Kennedy             |     None     |
| Q133809411 |   RELATIVE  |      Q4773467     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |      Q1086823     |          Christopher Lawford          |     None     |
| Q133809411 |   RELATIVE  |      Q505178      |         Joseph P. Kennedy Jr.         |     None     |
| Q133809411 |   RELATIVE  |      Q5112377     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |      Q5178632     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |      Q5301573     |        Douglas Harriman Kennedy       |     None     |
| Q133809411 |   RELATIVE  |     Q61440298     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |     Q66108091     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |      Q6769708     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |      Q6794923     |              Max Kennedy              |     None     |
| Q133809411 |   RELATIVE  |     Q75326753     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |     Q75326777     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |     Q75326779     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |     Q75326780     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |     Q75326792     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |     Q75326795     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |     Q75326815     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |     Q75326829     |         Robert F. Kennedy III         |     None     |
| Q133809411 |   RELATIVE  |     Q75326830     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |     Q75326840     |                  None                 |     None     |
| Q133809411 |   RELATIVE  |      Q948920      |           Patrick J. Kennedy          |     None     |
| Q133809411 |   SAMEGEN   |     Q112833739    | Eloise Christina Schwarzenegger Pratt |   sibling    |
| Q133809411 |   SAMEGEN   |     Q43100988     |               Jack Pratt              |   sibling    |
| Q133809411 |   SAMEGEN   |     Q133809424    |                  None                 |     None     |
+------------+-------------+-------------------+---------------------------------------+--------------+

### Maria Shriver (Q230654)

In [ ]:
nepo_breakdown('Q230654')

,person_id,person_name,kinship,relationship,related_person_id,related_person_name,person_point,person_movie_point,person_award_point,kinship_weight,contribution,person_nepo_score,parent_score,grandparent_score,ancestor_score,relative_score
0,Q230654,Maria Shriver,AUNT_UNCLE,uncle,Q9696,John F. Kennedy,1520.0,1354.0,166.0,0.25,380.0,244.0,224.0,20.0,0.0,0.0
1,Q230654,Maria Shriver,AUNT_UNCLE,uncle,Q25310,Robert F. Kennedy,470.0,440.0,30.0,0.25,117.0,244.0,224.0,20.0,0.0,0.0
2,Q230654,Maria Shriver,AUNT_UNCLE,uncle,Q134549,Ted Kennedy,305.0,175.0,130.0,0.25,76.0,244.0,224.0,20.0,0.0,0.0
3,Q230654,Maria Shriver,AUNT_UNCLE,None,Q505178,Joseph P. Kennedy Jr.,43.0,3.0,40.0,0.25,11.0,244.0,224.0,20.0,0.0,0.0
4,Q230654,Maria Shriver,AUNT_UNCLE,None,Q265595,Rosemary Kennedy,10.0,10.0,0.0,0.25,3.0,244.0,224.0,20.0,0.0,0.0
5,Q230654,Maria Shriver,AUNT_UNCLE,None,Q272401,Jean Kennedy Smith,10.0,0.0,10.0,0.25,3.0,244.0,224.0,20.0,0.0,0.0
6,Q230654,Maria Shriver,AUNT_UNCLE,None,Q268799,Kathleen Cavendish,0.0,0.0,0.0,0.25,0.0,244.0,224.0,20.0,0.0,0.0
7,Q230654,Maria Shriver,AUNT_UNCLE,None,Q432694,Patricia Kennedy Lawford,0.0,0.0,0.0,0.25,0.0,244.0,224.0,20.0,0.0,0.0
8,Q230654,Maria Shriver,CHILD,None,Q901541,Patrick Schwarzenegger,194.0,194.0,0.0,1.00,194.0,244.0,224.0,20.0,0.0,0.0
9,Q230654,Maria Shriver,CHILD,None,Q4521676,Katherine Schwarzenegger,33.0,33.0,0.0,1.00,33.0,244.0,224.0,20.0,0.0,0.0
10,Q230654,Maria Shriver,CHILD,None,Q28109928,None,0.0,0.0,0.0,1.00,0.0,244.0,224.0,20.0,0.0,0.0
11,Q230654,Maria Shriver,CHILD,None,Q28109921,Christina Schwarzenegger,0.0,0.0,0.0,1.00,0.0,244.0,224.0,20.0,0.0,0.0
12,Q230654,Maria Shriver,COUSIN,None,Q273833,Rory Kennedy,610.0,597.0,13.0,0.25,153.0,244.0,224.0,20.0,0.0,0.0
13,Q230654,Maria Shriver,COUSIN,None,Q1352872,Robert F. Kennedy Jr.,487.0,477.0,10.0,0.25,122.0,244.0,224.0,20.0,0.0,0.0
14,Q230654,Maria Shriver,COUSIN,None,Q1086823,Christopher Lawford,240.0,240.0,0.0,0.25,60.0,244.0,224.0,20.0,0.0,0.0
15,Q230654,Maria Shriver,COUSIN,None,Q230303,Caroline Kennedy,119.0,89.0,30.0,0.25,30.0,244.0,224.0,20.0,0.0,0.0
16,Q230654,Maria Shriver,COUSIN,None,Q467861,Kathleen Kennedy Townsend,110.0,110.0,0.0,0.25,28.0,244.0,224.0,20.0,0.0,0.0
17,Q230654,Maria Shriver,COUSIN,None,Q316064,John F. Kennedy Jr.,107.0,107.0,0.0,0.25,27.0,244.0,224.0,20.0,0.0,0.0
18,Q230654,Maria Shriver,COUSIN,None,Q467912,Kerry Kennedy,36.0,36.0,0.0,0.25,9.0,244.0,224.0,20.0,0.0,0.0
19,Q230654,Maria Shriver,COUSIN,None,Q1804720,Michael LeMoyne Kennedy,23.0,23.0,0.0,0.25,6.0,244.0,224.0,20.0,0.0,0.0
20,Q230654,Maria Shriver,COUSIN,None,Q1386420,Joseph P. Kennedy II,11.0,11.0,0.0,0.25,3.0,244.0,224.0,20.0,0.0,0.0
21,Q230654,Maria Shriver,COUSIN,None,Q3048622,Edward M. Kennedy Jr.,10.0,0.0,10.0,0.25,3.0,244.0,224.0,20.0,0.0,0.0
22,Q230654,Maria Shriver,COUSIN,None,Q948920,Patrick J. Kennedy,6.0,6.0,0.0,0.25,1.0,244.0,224.0,20.0,0.0,0.0
23,Q230654,Maria Shriver,COUSIN,None,Q3290402,None,0.0,0.0,0.0,0.25,0.0,244.0,224.0,20.0,0.0,0.0
24,Q230654,Maria Shriver,COUSIN,None,Q75326795,None,0.0,0.0,0.0,0.25,0.0,244.0,224.0,20.0,0.0,0.0
25,Q230654,Maria Shriver,COUSIN,None,Q75326792,None,0.0,0.0,0.0,0.25,0.0,244.0,224.0,20.0,0.0,0.0
26,Q230654,Maria Shriver,COUSIN,None,Q3568759,None,0.0,0.0,0.0,0.25,0.0,244.0,224.0,20.0,0.0,0.0
27,Q230654,Maria Shriver,COUSIN,None,Q75326780,None,0.0,0.0,0.0,0.25,0.0,244.0,224.0,20.0,0.0,0.0
28,Q230654,Maria Shriver,COUSIN,None,Q1975383,David A. Kennedy,0.0,0.0,0.0,0.25,0.0,244.0,224.0,20.0,0.0,0.0
29,Q230654,Maria Shriver,COUSIN,None,Q75326779,None,0.0,0.0,0.0,0.25,0.0,244.0,224.0,20.0,0.0,0.0
30,Q230654,Maria Shriver,COUSIN,None,Q5112377,None,0.0,0.0,0.0,0.25,0.0,244.0,224.0,20.0,0.0,0.0
31,Q230654,Maria Shriver,COUSIN,None,Q5178632,None,0.0,0.0,0.0,0.25,0.0,244.0,224.0,20.0,0.0,0.0
32,Q230654,Maria Shriver,COUSIN,None,Q5301573,Douglas Harriman Kennedy,0.0,0.0,0.0,0.25,0.0,244.0,224.0,20.0,0.0,0.0
33,Q230654,Maria Shriver,COUSIN,None,Q6794923,Max Kennedy,0.0,0.0,0.0,0.25,0.0,244.0,224.0,20.0,0.0,0.0
34,Q230654,Maria Shriver,COUSIN,None,Q75326777,None,0.0,0.0,0.0,0.25,0.0,244.0,224.0,20.0,0.0,0.0
35,Q230654,Maria Shriver,COUSIN,None,Q75326753,None,0.0,0.0,0.0,0.25,0.0,244.0,224.0,20.0,0.0,0.0
36,Q230654,Maria Shriver,COUSIN,None,Q2383370,Kara Kennedy,0.0,0.0,0.0,0.25,0.0,244.0,224.0,20.0,0.0,0.0
37,Q230654,Maria Shriver,COUSIN,None,Q75326840,None,0.0,0.0,0.0,0.25,0.0,244.0,224.0,20.0,0.0,0.0
38,Q230654,Maria Shriver,GRANDCHILD,None,Q112833739,Eloise Christina Schwarzenegger Pratt,0.0,0.0,0.0,0.50,0.0,244.0,224.0,20.0,0.0,0.0
39,Q230654,Maria Shriver,GRANDCHILD,None,Q133809424,None,0.0,0.0,0.0,0.50,0.0,244.0,224.0,20.0,0.0,0.0
40,Q230654,Maria Shriver,GRANDCHILD,None,Q133809411,Ford Pratt,0.0,0.0,0.0,0.50,0.0,244.0,224.0,20.0,0.0,0.0
41,Q230654,Maria Shriver,GRANDPARENT,None,Q313696,Joseph P. Kennedy Sr.,30.0,30.0,0.0,0.50,15.0,244.0,224.0,20.0,0.0,0.0
42,Q230654,Maria Shriver,GRANDPARENT,None,Q236540,Rose Kennedy,10.0,10.0,0.0,0.50,5.0,244.0,224.0,20.0,0.0,0.0
43,Q230654,Maria Shriver,GRANDPARENT,None,Q96077739,None,0.0,0.0,0.0,0.50,0.0,244.0,224.0,20.0,0.0,0.0
44,Q230654,Maria Shriver,GRANDPARENT,None,Q96077740,None,0.0,0.0,0.0,0.50,0.0,244.0,224.0,20.0,0.0,0.0
45,Q230654,Maria Shriver,PARENT,mother,Q272908,Eunice Kennedy Shriver,224.0,64.0,160.0,1.00,224.0,244.0,224.0,20.0,0.0,0.0
46,Q230654,Maria Shriver,PARENT,father,Q317248,None,0.0,0.0,0.0,1.00,0.0,244.0,224.0,20.0,0.0,0.0
47,Q230654,Maria Shriver,SIBLING,sibling,Q3529079,Timothy Shriver,14.0,14.0,0.0,0.50,7.0,244.0,224.0,20.0,0.0,0.0
48,Q230654,Maria Shriver,SIBLING,None,Q6769708,None,0.0,0.0,0.0,0.50,0.0,244.0,224.0,20.0,0.0,0.0
49,Q230654,Maria Shriver,SIBLING,sibling,Q3436301,Bobby Shriver,0.0,0.0,0.0,0.50,0.0,244.0,224.0,20.0,0.0,0.0
50,Q230654,Maria Shriver,SIBLING,None,Q4773467,None,0.0,0.0,0.0,0.50,0.0,244.0,224.0,20.0,0.0,0.0

### Q26876

In [18]:
nepo_breakdown('Q26876')

───────────────────────────────────────────────────────
  Taylor Swift (Q26876)
  Nepo score (stored): 75.0
  Contribution sum   : 69
  Relatives found    : 9
  Contributing (>0)  : 2
───────────────────────────────────────────────────────

,person_id,person_name,kinship,gen_delta,degree,raw_relationship,related_person_id,related_name,person_point,movie_point,award_point,kinship_weight,contribution,person_nepo_score,person_parent_score,person_grandparent_score,person_ancestor_score
0,Q26876,Taylor Swift,PARENT,1,0,mother,Q17319206,Andrea Finlay,35.0,35.0,0.0,1.00,35.0,75.0,70.0,0.0,0.0
1,Q26876,Taylor Swift,PARENT,1,0,father,Q17319204,Scott Swift,34.0,34.0,0.0,1.00,34.0,75.0,70.0,0.0,0.0
2,Q26876,Taylor Swift,GRANDPARENT,2,0,None,Q107325972,None,0.0,0.0,0.0,0.50,0.0,75.0,70.0,0.0,0.0
3,Q26876,Taylor Swift,GRANDPARENT,2,0,None,Q107325983,None,0.0,0.0,0.0,0.50,0.0,75.0,70.0,0.0,0.0
4,Q26876,Taylor Swift,GRANDPARENT,2,0,None,Q100942446,None,0.0,0.0,0.0,0.50,0.0,75.0,70.0,0.0,0.0
5,Q26876,Taylor Swift,GRANDPARENT,2,0,grandmother,Q104126119,None,0.0,0.0,0.0,0.50,0.0,75.0,70.0,0.0,0.0
6,Q26876,Taylor Swift,ANCESTOR,3,0,None,Q107326045,None,0.0,0.0,0.0,0.25,0.0,75.0,70.0,0.0,0.0
7,Q26876,Taylor Swift,ANCESTOR,3,0,None,Q107326047,None,0.0,0.0,0.0,0.25,0.0,75.0,70.0,0.0,0.0
8,Q26876,Taylor Swift,SIBLING,0,1,sibling,Q17319209,Austin Swift,56.0,56.0,0.0,0.00,0.0,75.0,70.0,0.0,0.0

## family

In [37]:
%%sql
/* ============================================================
  SECTION 6 — FAMILY DYNASTIES (DERIVED FROM LAST NAME, IGNORING SUFFIXES)
  ------------------------------------------------------------
  Depends On: core.person, core.neposcore
  Purpose: Identify prominent families using last name, handling suffixes
  ============================================================ */


WITH person_family AS (
   SELECT
       p.person_id,
       p.name,
       ns.nepo_score,
       -- Split name into array
       string_to_array(p.name, ' ') AS name_parts
   FROM core.person p
            LEFT JOIN core.neposcore ns
                      ON ns.person_id = p.person_id
   WHERE ns.nepo_score IS NOT NULL
),
    family_extracted AS (
        SELECT
            person_id,
            name,
            nepo_score,
            CASE
                WHEN upper(name_parts[array_length(name_parts,1)]) IN ('JR.','SR.','II','III','IV','V')
                    THEN name_parts[array_length(name_parts,1)-1]
                ELSE name_parts[array_length(name_parts,1)]
                END AS family_name
        FROM person_family
    )
SELECT
   family_name,
   COUNT(DISTINCT person_id) AS family_members,
   AVG(nepo_score)::numeric(10,2) AS avg_family_nepo_score,
   MAX(nepo_score) ::numeric(10,2) AS top_family_nepo_score
FROM family_extracted
WHERE family_name IS NOT NULL
GROUP BY family_name
HAVING COUNT(DISTINCT person_id) >= 2
ORDER BY avg_family_nepo_score DESC NULLS LAST,
        family_members DESC
LIMIT 100;

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sql/connection/connection.py:865: JupySQLRollbackPerformed: Found invalid transaction. JupySQL executed a ROLLBACK operation.
  warnings.warn(

100 rows affected.

+-------------+----------------+-----------------------+-----------------------+
| family_name | family_members | avg_family_nepo_score | top_family_nepo_score |
+-------------+----------------+-----------------------+-----------------------+
|   Eastwood  |       9        |        5231.12        |        8327.93        |
|    Farrow   |       8        |        4821.47        |        9245.78        |
|    Jolie    |       2        |        4784.24        |        7220.60        |
|   Estévez   |       2        |        3805.71        |        3805.71        |
|  Spielberg  |       8        |        3668.11        |        6281.62        |
|    Hawke    |       3        |        3603.53        |        5405.29        |
|  Sutherland |       6        |        3479.34        |        4546.65        |
|     Niro    |       5        |        3458.10        |        5828.66        |
|  Carradine  |       8        |        3334.84        |        4734.57        |
|    Sheen    |       7        |        2989.89        |        4847.23        |
+-------------+----------------+-----------------------+-----------------------+
Truncated to displaylimit of 10.

In [38]:
%%sql
WITH family_groups AS (
    -- Find all connected family components via core.kinship
    -- Each person + their relatives form a "family"
    SELECT DISTINCT
        LEAST(k.person_id, k.related_person_id)    AS person_a,
        GREATEST(k.person_id, k.related_person_id) AS person_b
    FROM core.kinship k
    WHERE k.kinship IN ('PARENT', 'GRANDPARENT', 'ANCESTOR', 'SAMEGEN', 'RELATIVE')
),
-- Assign a family_id = the smallest person_id in the connected group
-- Use recursive CTE to find all connected components
family_components AS (
    SELECT
        person_a AS person_id,
        person_a AS family_id
    FROM family_groups

    UNION

    SELECT
        person_b AS person_id,
        person_a AS family_id
    FROM family_groups
),
-- For each person, pick the smallest family_id as their family root
family_assigned AS (
    SELECT
        person_id,
        MIN(family_id) AS family_id
    FROM family_components
    GROUP BY person_id
),
-- Get the name of the family root person as the family name
family_named AS (
    SELECT
        fa.person_id,
        fa.family_id,
        p_root.name AS family_name,
        p.name      AS person_name,
        ns.nepo_score
    FROM family_assigned fa
    JOIN core.person p      ON p.person_id      = fa.person_id
    JOIN core.person p_root ON p_root.person_id = fa.family_id
    LEFT JOIN core.neposcore ns ON ns.person_id = fa.person_id
    WHERE ns.nepo_score IS NOT NULL
)
SELECT
    family_id,
    family_name                             AS family_root_person,
    COUNT(DISTINCT person_id)               AS family_members,
    AVG(nepo_score)::NUMERIC(10,2)          AS avg_family_nepo_score,
    MAX(nepo_score)      ::NUMERIC(10,2)                    AS top_family_nepo_score,
    STRING_AGG(person_name, ', '
        ORDER BY nepo_score DESC NULLS LAST) AS members
FROM family_named
GROUP BY family_id, family_name
HAVING COUNT(DISTINCT person_id) >= 2
ORDER BY avg_family_nepo_score DESC NULLS LAST,
         family_members DESC
LIMIT 100;

Running query in 'postgresql://postgres:***@localhost:5432/nepo'

100 rows affected.

+-----------+--------------------+----------------+-----------------------+-----------------------+----------------------------------------------------------------------------------------------------------------+
| family_id | family_root_person | family_members | avg_family_nepo_score | top_family_nepo_score |                                                    members                                                     |
+-----------+--------------------+----------------+-----------------------+-----------------------+----------------------------------------------------------------------------------------------------------------+
| Q15784029 |  Arnold Spielberg  |       5        |        4714.81        |        6281.62        |                Max Spielberg, Sasha Spielberg, Theo Spielberg, Sawyer Spielberg, Anne Spielberg                |
|   Q36949  |   Robert De Niro   |       2        |        4491.36        |        5828.66        |                                    Drena De Niro, Leandro De Niro Rodriguez                                    |
| Q18932313 |   Maggie Johnson   |       3        |        4301.86        |        6452.79        |                                 Kyle Eastwood, Alison Eastwood, Maggie Johnson                                 |
|   Q35011  |   Frances Fisher   |       2        |        4163.97        |        8327.93        |                                       Francesca Eastwood, Frances Fisher                                       |
| Q63649755 |     Cora Baker     |       2        |        3658.17        |        7316.34        |                                         Cora Baker, Dee Bradley Baker                                          |
|   Q13938  |    Grey DeLisle    |       2        |        3540.47        |        7080.94        |                                           Tex Hammond, Grey DeLisle                                            |
|  Q103784  | Donald Sutherland  |       6        |        3479.34        |        4546.65        | Sarah Sutherland, Rachel Sutherland, Kiefer Sutherland, Angus Sutherland, Rossif Sutherland, Donald Sutherland |
|  Q162389  |    Tony Curtis     |       2        |        3404.26        |        4090.71        |                                          Kelly Curtis, Allegra Curtis                                          |
|  Q104027  |    Kirk Douglas    |       4        |        3387.19        |        4370.23        |                            Dylan Douglas, Joel Douglas, Eric Douglas, Peter Douglas                            |
|  Q3323973 |  Morgan Eastwood   |       2        |        3244.10        |        6488.19        |                                         Morgan Eastwood, Dina Eastwood                                         |
+-----------+--------------------+----------------+-----------------------+-----------------------+----------------------------------------------------------------------------------------------------------------+
Truncated to displaylimit of 10.

## FUNCTION

### nepo breakdown

In [15]:
from sqlalchemy import create_engine, text
import pandas as pd
import getpass

password = getpass.getpass("Enter PostgreSQL password: ")
engine = create_engine(f'postgresql://postgres:{password}@localhost:5432/nepo')

# ── Weights — only higher-gen ancestors contribute ────────────────────────────
KINSHIP_WEIGHTS = {
    'PARENT':           1.0,
    'GRANDPARENT':      0.5,
    'ANCESTOR':         0.25,
    'AUNT_UNCLE':       0.25,
    'GREAT_AUNT_UNCLE': 0.15,
}

def ensure_indexes():
    with engine.connect() as conn:
        conn.execute(text("""
            CREATE INDEX IF NOT EXISTS idx_kinship_person_id
                ON core.kinship (person_id);
        """))
        conn.execute(text("""
            CREATE INDEX IF NOT EXISTS idx_relationship_person_related
                ON core.relationship (person_id, related_person_id);
        """))
        conn.commit()


def _resolve_person(identifier, blur=False):
    """Resolve a name or QID to a person_id. Returns (person_id, name)."""
    if str(identifier).startswith('Q'):
        with engine.connect() as conn:
            row = conn.execute(
                text("SELECT person_id, name FROM core.person WHERE person_id = :pid"),
                {"pid": identifier}
            ).fetchone()
        if not row:
            print(f"No person found with ID: {identifier}")
            return None, None
        return row[0], row[1]

    search_term = f'%{identifier}%' if blur else identifier
    limit       = 10 if blur else 1
    with engine.connect() as conn:
        results = conn.execute(
            text("SELECT person_id, name FROM core.person WHERE name ILIKE :name ORDER BY name LIMIT :lim"),
            {"name": search_term, "lim": limit}
        ).fetchall()

    if not results:
        print(f"No person found with name: {identifier}")
        return None, None

    if blur and len(results) > 1:
        print("Multiple matches found:")
        for i, row in enumerate(results):
            print(f"  [{i}] {row[0]} — {row[1]}")
        choice = int(input("Enter number to select: "))
        return results[choice][0], results[choice][1]

    print(f"Resolved '{identifier}' → {results[0][0]} ({results[0][1]})")
    return results[0][0], results[0][1]


def nepo_breakdown(identifier, blur=False):
    """
    Get nepo score breakdown for a person.
    Only higher-generation relatives contribute (PARENT, GRANDPARENT,
    ANCESTOR, AUNT_UNCLE, GREAT_AUNT_UNCLE). All same-gen, lower-gen,
    and in-law relationships show weight=0 and contribution=0.

    Usage:
        nepo_breakdown('Q116869845')
        nepo_breakdown('Blake Lively')
        nepo_breakdown('lively', blur=True)
    """
    person_id, person_name = _resolve_person(identifier, blur)
    if not person_id:
        return None

    # Build SQL CASE from KINSHIP_WEIGHTS dict
    weight_case = "CASE k.kinship\n" + \
        "\n".join(f"        WHEN '{k}' THEN {v}" for k, v in KINSHIP_WEIGHTS.items()) + \
        "\n        ELSE 0.0\n    END"

    query = text(f"""
        SELECT
            k.person_id,
            p1.name                                         AS person_name,
            k.kinship,
            k.gen_delta,
            k.degree,
            r.relationship                                  AS raw_relationship,
            k.related_person_id,
            p2.name                                         AS related_name,
            ROUND(COALESCE(pp.person_point,       0))       AS person_point,
            ROUND(COALESCE(pp.person_movie_point, 0))       AS movie_point,
            ROUND(COALESCE(pp.person_award_point, 0))       AS award_point,
            {weight_case}                                   AS kinship_weight,
            ROUND(COALESCE(pp.person_point, 0) *
                {weight_case})                              AS contribution,

            -- person's own nepo score summary
            ROUND(COALESCE(ns.nepo_score,        0))        AS person_nepo_score,
            ROUND(COALESCE(ns.parent_score,      0))        AS person_parent_score,
            ROUND(COALESCE(ns.grandparent_score, 0))        AS person_grandparent_score,
            ROUND(COALESCE(ns.ancestor_score,    0))        AS person_ancestor_score

        FROM core.kinship k
        LEFT JOIN core.person       p1 ON p1.person_id       = k.person_id
        LEFT JOIN core.person       p2 ON p2.person_id       = k.related_person_id
        LEFT JOIN core.personpoint  pp ON pp.person_id       = k.related_person_id
        LEFT JOIN core.neposcore    ns ON ns.person_id       = k.person_id
        LEFT JOIN core.relationship  r ON r.person_id        = :person_id
                                      AND r.related_person_id = k.related_person_id
        WHERE k.person_id = :person_id
        ORDER BY
            kinship_weight DESC,
            contribution   DESC NULLS LAST,
            k.kinship
    """)

    with engine.connect() as conn:
        df = pd.read_sql(query, conn, params={"person_id": person_id})

    if df.empty:
        print(f"No kinship data found for: {identifier}")
        return None

    # Summary banner
    total = df['contribution'].sum()
    print(f"\n{'─'*55}")
    print(f"  {person_name} ({person_id})")
    print(f"  Nepo score (stored): {df['person_nepo_score'].iloc[0]}")
    print(f"  Contribution sum   : {total:.0f}")
    print(f"  Relatives found    : {len(df)}")
    print(f"  Contributing (>0)  : {(df['contribution'] > 0).sum()}")
    print(f"{'─'*55}\n")

    return df


if __name__ == "__main__":
    ensure_indexes()

In [16]:
nepo_breakdown('Q116869845')

No person found with ID: Q116869845

In [17]:
# by Wikidata ID
nepo_breakdown('Q116869845')

# exact name
nepo_breakdown('Blake Lively')

# blur search — shows up to 10 matches, prompts you to pick
nepo_breakdown('lively', blur=True)
nepo_breakdown('blake', blur=True)
nepo_breakdown('kim', blur=True)
```

When blur finds multiple matches it will prompt:
```
Multiple matches found:
  [0] Q162959 — Blake Lively
  [1] Q712936 — Eric Lively
Enter number to select: 0
Selected: Blake Lively (Q162959)

SyntaxError: invalid character '—' (U+2014) (1922151235.py, line 16)

### nepo top 10

In [34]:
def top_n_nepo_breakdown(n=10):
    """
    Get nepo score breakdown for the top N nepo babies.
    Ranked by nepo_score descending, only persons with nepotag = TRUE.

    Usage:
        top_n_nepo_breakdown()         # default top 10
        top_n_nepo_breakdown(n=5)      # top 5
        top_n_nepo_breakdown(n=50)     # top 50
    """

    # Build SQL CASE from KINSHIP_WEIGHTS dict
    weight_case = "CASE k.kinship\n" + \
        "\n".join(f"        WHEN '{k}' THEN {v}" for k, v in KINSHIP_WEIGHTS.items()) + \
        "\n        ELSE 0.0\n    END"

    # Step 1: get top N nepo babies
    top_n_query = text("""
        SELECT ns.person_id, p.name, ns.nepo_score
        FROM core.neposcore ns
        JOIN core.person p ON p.person_id = ns.person_id
        WHERE ns.nepotag = TRUE
        ORDER BY ns.nepo_score DESC
        LIMIT :n
    """)

    with engine.connect() as conn:
        top_n = conn.execute(top_n_query, {"n": n}).fetchall()

    if not top_n:
        print("No nepo babies found.")
        return None

    print(f"\n{'═'*55}")
    print(f"  TOP {n} NEPO BABIES")
    print(f"{'═'*55}")
    for i, row in enumerate(top_n, 1):
        print(f"  [{i}] {row[1]} ({row[0]}) — nepo_score: {row[2]:.0f}")
    print(f"{'═'*55}\n")

    # Step 2: get breakdown for each
    results = {}

    detail_query = text(f"""
        SELECT
            k.person_id,
            p1.name                                         AS person_name,
            k.kinship,
            k.gen_delta,
            k.degree,
            r.relationship                                  AS raw_relationship,
            k.related_person_id,
            p2.name                                         AS related_name,
            ROUND(COALESCE(pp.person_point,       0))       AS person_point,
            ROUND(COALESCE(pp.person_movie_point, 0))       AS movie_point,
            ROUND(COALESCE(pp.person_award_point, 0))       AS award_point,
            {weight_case}                                   AS kinship_weight,
            ROUND(COALESCE(pp.person_point, 0) *
                {weight_case})                              AS contribution,

            ROUND(COALESCE(ns.nepo_score,        0))        AS person_nepo_score,
            ROUND(COALESCE(ns.parent_score,      0))        AS person_parent_score,
            ROUND(COALESCE(ns.grandparent_score, 0))        AS person_grandparent_score,
            ROUND(COALESCE(ns.ancestor_score,    0))        AS person_ancestor_score

        FROM core.kinship k
        LEFT JOIN core.person       p1 ON p1.person_id       = k.person_id
        LEFT JOIN core.person       p2 ON p2.person_id       = k.related_person_id
        LEFT JOIN core.personpoint  pp ON pp.person_id       = k.related_person_id
        LEFT JOIN core.neposcore    ns ON ns.person_id       = k.person_id
        LEFT JOIN core.relationship  r ON r.person_id        = :person_id
                                      AND r.related_person_id = k.related_person_id
        WHERE k.person_id = :person_id
        ORDER BY
            kinship_weight DESC,
            contribution   DESC NULLS LAST,
            k.kinship
    """)

    with engine.connect() as conn:
        for rank, (person_id, person_name, nepo_score) in enumerate(top_n, 1):
            df = pd.read_sql(detail_query, conn, params={"person_id": person_id})

            total        = df['contribution'].sum()
            contributing = (df['contribution'] > 0).sum()

            print(f"{'─'*55}")
            print(f"  #{rank} {person_name} ({person_id})")
            print(f"  Nepo score (stored): {nepo_score:.0f}")
            print(f"  Contribution sum   : {total:.0f}")
            print(f"  Relatives found    : {len(df)}")
            print(f"  Contributing (>0)  : {contributing}")
            print(f"{'─'*55}")
            print(df[['related_name', 'kinship', 'person_point',
                       'kinship_weight', 'contribution']].to_string(index=False))
            print()

            results[person_id] = df

    return results


if __name__ == "__main__":
    ensure_indexes()
    top_n_nepo_breakdown(n=10)

═══════════════════════════════════════════════════════
  TOP 10 NEPO BABIES
═══════════════════════════════════════════════════════
  [1] Moses Farrow (Q16217493) — nepo_score: 9528
  [2] Dylan Farrow (Q100135417) — nepo_score: 9524
  [3] Ronan Farrow (Q7365461) — nepo_score: 9512
  [4] Francesca Eastwood (Q5479089) — nepo_score: 8461
  [5] Emma Roberts (Q228598) — nepo_score: 7341
  [6] Cora Baker (Q63649755) — nepo_score: 7316
  [7] Shiloh Jolie (Q55430492) — nepo_score: 7273
  [8] Maddox Jolie-Pitt. (Q13147738) — nepo_score: 7273
  [9] Tex Hammond (Q56686344) — nepo_score: 7066
  [10] Weston Cage (Q4019196) — nepo_score: 6934
═══════════════════════════════════════════════════════

───────────────────────────────────────────────────────
  #1 Moses Farrow (Q16217493)
  Nepo score (stored): 9528
  Contribution sum   : 9499
  Relatives found    : 28
  Contributing (>0)  : 8
───────────────────────────────────────────────────────
      related_name     kinship  person_point  kinship_weight  contribution
       Woody Allen      PARENT        6297.0            1.00        6297.0
        Mia Farrow      PARENT        1580.0            1.00        1580.0
Maureen O'Sullivan GRANDPARENT        1478.0            0.50         739.0
       John Farrow GRANDPARENT        1231.0            0.50         615.0
 Nettie Königsberg GRANDPARENT          28.0            0.50          14.0
              None GRANDPARENT           0.0            0.50           0.0
     Letty Aronson  AUNT_UNCLE         666.0            0.25         166.0
       Tisa Farrow  AUNT_UNCLE         280.0            0.25          70.0
  Stephanie Farrow  AUNT_UNCLE          72.0            0.25          18.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
   Prudence Farrow  AUNT_UNCLE           0.0            0.25           0.0
              None  AUNT_UNCLE           0.0            0.25           0.0
      Dylan Farrow     SIBLING          49.0            0.00           0.0
    Soon-Yi Previn     SIBLING          32.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
      Ronan Farrow     SIBLING         165.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
 Frank Sinatra Jr. STEPSIBLING          85.0            0.00           0.0
     Frank Sinatra STEPSIBLING        1909.0            0.00           0.0
     Louise Lasser STEPSIBLING         550.0            0.00           0.0
     Nancy Sinatra STEPSIBLING         217.0            0.00           0.0
      Tina Sinatra STEPSIBLING          53.0            0.00           0.0
      André Previn STEPSIBLING         827.0            0.00           0.0

───────────────────────────────────────────────────────
  #2 Dylan Farrow (Q100135417)
  Nepo score (stored): 9524
  Contribution sum   : 9499
  Relatives found    : 28
  Contributing (>0)  : 8
───────────────────────────────────────────────────────
      related_name     kinship  person_point  kinship_weight  contribution
       Woody Allen      PARENT        6297.0            1.00        6297.0
        Mia Farrow      PARENT        1580.0            1.00        1580.0
Maureen O'Sullivan GRANDPARENT        1478.0            0.50         739.0
       John Farrow GRANDPARENT        1231.0            0.50         615.0
 Nettie Königsberg GRANDPARENT          28.0            0.50          14.0
              None GRANDPARENT           0.0            0.50           0.0
     Letty Aronson  AUNT_UNCLE         666.0            0.25         166.0
       Tisa Farrow  AUNT_UNCLE         280.0            0.25          70.0
  Stephanie Farrow  AUNT_UNCLE          72.0            0.25          18.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None  AUNT_UNCLE           0.0            0.25           0.0
   Prudence Farrow  AUNT_UNCLE           0.0            0.25           0.0
              None     SIBLING           0.0            0.00           0.0
      Moses Farrow     SIBLING           0.0            0.00           0.0
      Ronan Farrow     SIBLING         165.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
    Soon-Yi Previn     SIBLING          32.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
     Louise Lasser STEPSIBLING         550.0            0.00           0.0
 Frank Sinatra Jr. STEPSIBLING          85.0            0.00           0.0
      Tina Sinatra STEPSIBLING          53.0            0.00           0.0
      André Previn STEPSIBLING         827.0            0.00           0.0
     Frank Sinatra STEPSIBLING        1909.0            0.00           0.0
     Nancy Sinatra STEPSIBLING         217.0            0.00           0.0

───────────────────────────────────────────────────────
  #3 Ronan Farrow (Q7365461)
  Nepo score (stored): 9512
  Contribution sum   : 9499
  Relatives found    : 28
  Contributing (>0)  : 8
───────────────────────────────────────────────────────
      related_name     kinship  person_point  kinship_weight  contribution
       Woody Allen      PARENT        6297.0            1.00        6297.0
        Mia Farrow      PARENT        1580.0            1.00        1580.0
Maureen O'Sullivan GRANDPARENT        1478.0            0.50         739.0
       John Farrow GRANDPARENT        1231.0            0.50         615.0
 Nettie Königsberg GRANDPARENT          28.0            0.50          14.0
              None GRANDPARENT           0.0            0.50           0.0
     Letty Aronson  AUNT_UNCLE         666.0            0.25         166.0
       Tisa Farrow  AUNT_UNCLE         280.0            0.25          70.0
  Stephanie Farrow  AUNT_UNCLE          72.0            0.25          18.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None  AUNT_UNCLE           0.0            0.25           0.0
   Prudence Farrow  AUNT_UNCLE           0.0            0.25           0.0
      Moses Farrow     SIBLING           0.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
    Soon-Yi Previn     SIBLING          32.0            0.00           0.0
      Dylan Farrow     SIBLING          49.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
     Louise Lasser STEPSIBLING         550.0            0.00           0.0
      André Previn STEPSIBLING         827.0            0.00           0.0
     Frank Sinatra STEPSIBLING        1909.0            0.00           0.0
      Tina Sinatra STEPSIBLING          53.0            0.00           0.0
 Frank Sinatra Jr. STEPSIBLING          85.0            0.00           0.0
     Nancy Sinatra STEPSIBLING         217.0            0.00           0.0

───────────────────────────────────────────────────────
  #4 Francesca Eastwood (Q5479089)
  Nepo score (stored): 8461
  Contribution sum   : 8328
  Relatives found    : 13
  Contributing (>0)  : 2
───────────────────────────────────────────────────────
        related_name     kinship  person_point  kinship_weight  contribution
      Clint Eastwood      PARENT        6453.0             1.0        6453.0
      Frances Fisher      PARENT        1875.0             1.0        1875.0
                None GRANDPARENT           0.0             0.5           0.0
                None GRANDPARENT           0.0             0.5           0.0
Kimber Lynn Eastwood     SIBLING          39.0             0.0           0.0
     Alison Eastwood     SIBLING         423.0             0.0           0.0
       Kyle Eastwood     SIBLING         264.0             0.0           0.0
      Scott Eastwood     SIBLING         570.0             0.0           0.0
     Morgan Eastwood     SIBLING          11.0             0.0           0.0
    Kathryn Eastwood     SIBLING          26.0             0.0           0.0
                None     SIBLING           0.0             0.0           0.0
      Maggie Johnson STEPSIBLING           0.0             0.0           0.0
       Dina Eastwood STEPSIBLING          35.0             0.0           0.0

───────────────────────────────────────────────────────
  #5 Emma Roberts (Q228598)
  Nepo score (stored): 7341
  Contribution sum   : 7341
  Relatives found    : 10
  Contributing (>0)  : 3
───────────────────────────────────────────────────────
       related_name     kinship  person_point  kinship_weight  contribution
       Eric Roberts      PARENT        6779.0            1.00        6779.0
 Betty Lou Bredemus GRANDPARENT           0.0            0.50           0.0
      Julia Roberts  AUNT_UNCLE        2107.0            0.25         527.0
Lisa Roberts Gillan  AUNT_UNCLE         138.0            0.25          35.0
         Q116858049     SIBLING           0.0            0.00           0.0
               None     SIBLING           0.0            0.00           0.0
               None     SIBLING           0.0            0.00           0.0
      Kelly Nickels  STEPPARENT           0.0            0.00           0.0
      Eliza Roberts STEPSIBLING         678.0            0.00           0.0
      Keaton Simons STEPSIBLING          60.0            0.00           0.0

───────────────────────────────────────────────────────
  #6 Cora Baker (Q63649755)
  Nepo score (stored): 7316
  Contribution sum   : 7316
  Relatives found    : 1
  Contributing (>0)  : 1
───────────────────────────────────────────────────────
     related_name kinship  person_point  kinship_weight  contribution
Dee Bradley Baker  PARENT        7316.0             1.0        7316.0

───────────────────────────────────────────────────────
  #7 Shiloh Jolie (Q55430492)
  Nepo score (stored): 7273
  Contribution sum   : 7267
  Relatives found    : 19
  Contributing (>0)  : 5
───────────────────────────────────────────────────────
        related_name          kinship  person_point  kinship_weight  contribution
           Brad Pitt           PARENT        3852.0            1.00        3852.0
      Angelina Jolie           PARENT        2194.0            1.00        2194.0
          Jon Voight      GRANDPARENT        2348.0            0.50        1174.0
                None      GRANDPARENT           0.0            0.50           0.0
                None      GRANDPARENT           0.0            0.50           0.0
 Marcheline Bertrand      GRANDPARENT           0.0            0.50           0.0
         James Haven       AUNT_UNCLE          76.0            0.25          19.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
         Chip Taylor GREAT_AUNT_UNCLE         188.0            0.15          28.0
                None GREAT_AUNT_UNCLE           0.0            0.15           0.0
        Lauri Peters         RELATIVE          80.0            0.00           0.0
  Maddox Jolie-Pitt.          SIBLING           0.0            0.00           0.0
Harry James Thornton      STEPSIBLING          14.0            0.00           0.0
  Billy Bob Thornton      STEPSIBLING        2555.0            0.00           0.0
    Jennifer Aniston      STEPSIBLING        2048.0            0.00           0.0
    Jonny Lee Miller      STEPSIBLING         849.0            0.00           0.0

───────────────────────────────────────────────────────
  #8 Maddox Jolie-Pitt. (Q13147738)
  Nepo score (stored): 7273
  Contribution sum   : 7267
  Relatives found    : 19
  Contributing (>0)  : 5
───────────────────────────────────────────────────────
        related_name          kinship  person_point  kinship_weight  contribution
           Brad Pitt           PARENT        3852.0            1.00        3852.0
      Angelina Jolie           PARENT        2194.0            1.00        2194.0
          Jon Voight      GRANDPARENT        2348.0            0.50        1174.0
                None      GRANDPARENT           0.0            0.50           0.0
                None      GRANDPARENT           0.0            0.50           0.0
 Marcheline Bertrand      GRANDPARENT           0.0            0.50           0.0
         James Haven       AUNT_UNCLE          76.0            0.25          19.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
         Chip Taylor GREAT_AUNT_UNCLE         188.0            0.15          28.0
                None GREAT_AUNT_UNCLE           0.0            0.15           0.0
        Lauri Peters         RELATIVE          80.0            0.00           0.0
        Shiloh Jolie          SIBLING           0.0            0.00           0.0
Harry James Thornton      STEPSIBLING          14.0            0.00           0.0
    Jennifer Aniston      STEPSIBLING        2048.0            0.00           0.0
    Jonny Lee Miller      STEPSIBLING         849.0            0.00           0.0
  Billy Bob Thornton      STEPSIBLING        2555.0            0.00           0.0

───────────────────────────────────────────────────────
  #9 Tex Hammond (Q56686344)
  Nepo score (stored): 7066
  Contribution sum   : 7066
  Relatives found    : 4
  Contributing (>0)  : 1
───────────────────────────────────────────────────────
 related_name kinship  person_point  kinship_weight  contribution
 Grey DeLisle  PARENT        7066.0             1.0        7066.0
Murry Hammond  PARENT           0.0             1.0           0.0
         None SIBLING           0.0             0.0           0.0
         None SIBLING           0.0             0.0           0.0

───────────────────────────────────────────────────────
  #10 Weston Cage (Q4019196)
  Nepo score (stored): 6934
  Contribution sum   : 6914
  Relatives found    : 32
  Contributing (>0)  : 13
───────────────────────────────────────────────────────
        related_name          kinship  person_point  kinship_weight  contribution
        Nicolas Cage           PARENT        4595.0            1.00        4595.0
    Christina Fulton           PARENT         158.0            1.00         158.0
      August Coppola      GRANDPARENT           0.0            0.50           0.0
                None      GRANDPARENT           0.0            0.50           0.0
       Sofia Coppola       AUNT_UNCLE        2445.0            0.25         611.0
   Jason Schwartzman       AUNT_UNCLE        1661.0            0.25         415.0
       Roman Coppola       AUNT_UNCLE         475.0            0.25         119.0
  Robert Schwartzman       AUNT_UNCLE         339.0            0.25          85.0
     Carmine Coppola         ANCESTOR         335.0            0.25          84.0
 Christopher Coppola       AUNT_UNCLE         260.0            0.25          65.0
        Marc Coppola       AUNT_UNCLE          99.0            0.25          25.0
       Anton Coppola         ANCESTOR          34.0            0.25           9.0
      Italia Coppola         ANCESTOR          25.0            0.25           6.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
  Gian-Carlo Coppola       AUNT_UNCLE           0.0            0.25           0.0
Francis Ford Coppola GREAT_AUNT_UNCLE        3691.0            0.15         554.0
         Talia Shire GREAT_AUNT_UNCLE        1251.0            0.15         188.0
                None            CHILD           0.0            0.00           0.0
                None            CHILD           0.0            0.00           0.0
         Gia Coppola          SIBLING         185.0            0.00           0.0
                None          SIBLING           0.0            0.00           0.0
                None          SIBLING           0.0            0.00           0.0
          Enzo Rossi      STEPSIBLING          26.0            0.00           0.0
        Riley Keough      STEPSIBLING        1046.0            0.00           0.0
  Lisa Marie Presley      STEPSIBLING           0.0            0.00           0.0
   Patricia Arquette      STEPSIBLING        1599.0            0.00           0.0
     Benjamin Keough      STEPSIBLING           0.0            0.00           0.0
         Harlow Jane      STEPSIBLING          53.0            0.00           0.0
      Alice Kim Cage      STEPSIBLING           0.0            0.00           0.0

In [35]:
# Default top 10
top_n_nepo_breakdown()

═══════════════════════════════════════════════════════
  TOP 10 NEPO BABIES
═══════════════════════════════════════════════════════
  [1] Moses Farrow (Q16217493) — nepo_score: 9528
  [2] Dylan Farrow (Q100135417) — nepo_score: 9524
  [3] Ronan Farrow (Q7365461) — nepo_score: 9512
  [4] Francesca Eastwood (Q5479089) — nepo_score: 8461
  [5] Emma Roberts (Q228598) — nepo_score: 7341
  [6] Cora Baker (Q63649755) — nepo_score: 7316
  [7] Shiloh Jolie (Q55430492) — nepo_score: 7273
  [8] Maddox Jolie-Pitt. (Q13147738) — nepo_score: 7273
  [9] Tex Hammond (Q56686344) — nepo_score: 7066
  [10] Weston Cage (Q4019196) — nepo_score: 6934
═══════════════════════════════════════════════════════

───────────────────────────────────────────────────────
  #1 Moses Farrow (Q16217493)
  Nepo score (stored): 9528
  Contribution sum   : 9499
  Relatives found    : 28
  Contributing (>0)  : 8
───────────────────────────────────────────────────────
      related_name     kinship  person_point  kinship_weight  contribution
       Woody Allen      PARENT        6297.0            1.00        6297.0
        Mia Farrow      PARENT        1580.0            1.00        1580.0
Maureen O'Sullivan GRANDPARENT        1478.0            0.50         739.0
       John Farrow GRANDPARENT        1231.0            0.50         615.0
 Nettie Königsberg GRANDPARENT          28.0            0.50          14.0
              None GRANDPARENT           0.0            0.50           0.0
     Letty Aronson  AUNT_UNCLE         666.0            0.25         166.0
       Tisa Farrow  AUNT_UNCLE         280.0            0.25          70.0
  Stephanie Farrow  AUNT_UNCLE          72.0            0.25          18.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
   Prudence Farrow  AUNT_UNCLE           0.0            0.25           0.0
              None  AUNT_UNCLE           0.0            0.25           0.0
      Dylan Farrow     SIBLING          49.0            0.00           0.0
    Soon-Yi Previn     SIBLING          32.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
      Ronan Farrow     SIBLING         165.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
 Frank Sinatra Jr. STEPSIBLING          85.0            0.00           0.0
     Frank Sinatra STEPSIBLING        1909.0            0.00           0.0
     Louise Lasser STEPSIBLING         550.0            0.00           0.0
     Nancy Sinatra STEPSIBLING         217.0            0.00           0.0
      Tina Sinatra STEPSIBLING          53.0            0.00           0.0
      André Previn STEPSIBLING         827.0            0.00           0.0

───────────────────────────────────────────────────────
  #2 Dylan Farrow (Q100135417)
  Nepo score (stored): 9524
  Contribution sum   : 9499
  Relatives found    : 28
  Contributing (>0)  : 8
───────────────────────────────────────────────────────
      related_name     kinship  person_point  kinship_weight  contribution
       Woody Allen      PARENT        6297.0            1.00        6297.0
        Mia Farrow      PARENT        1580.0            1.00        1580.0
Maureen O'Sullivan GRANDPARENT        1478.0            0.50         739.0
       John Farrow GRANDPARENT        1231.0            0.50         615.0
 Nettie Königsberg GRANDPARENT          28.0            0.50          14.0
              None GRANDPARENT           0.0            0.50           0.0
     Letty Aronson  AUNT_UNCLE         666.0            0.25         166.0
       Tisa Farrow  AUNT_UNCLE         280.0            0.25          70.0
  Stephanie Farrow  AUNT_UNCLE          72.0            0.25          18.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None  AUNT_UNCLE           0.0            0.25           0.0
   Prudence Farrow  AUNT_UNCLE           0.0            0.25           0.0
              None     SIBLING           0.0            0.00           0.0
      Moses Farrow     SIBLING           0.0            0.00           0.0
      Ronan Farrow     SIBLING         165.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
    Soon-Yi Previn     SIBLING          32.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
     Louise Lasser STEPSIBLING         550.0            0.00           0.0
 Frank Sinatra Jr. STEPSIBLING          85.0            0.00           0.0
      Tina Sinatra STEPSIBLING          53.0            0.00           0.0
      André Previn STEPSIBLING         827.0            0.00           0.0
     Frank Sinatra STEPSIBLING        1909.0            0.00           0.0
     Nancy Sinatra STEPSIBLING         217.0            0.00           0.0

───────────────────────────────────────────────────────
  #3 Ronan Farrow (Q7365461)
  Nepo score (stored): 9512
  Contribution sum   : 9499
  Relatives found    : 28
  Contributing (>0)  : 8
───────────────────────────────────────────────────────
      related_name     kinship  person_point  kinship_weight  contribution
       Woody Allen      PARENT        6297.0            1.00        6297.0
        Mia Farrow      PARENT        1580.0            1.00        1580.0
Maureen O'Sullivan GRANDPARENT        1478.0            0.50         739.0
       John Farrow GRANDPARENT        1231.0            0.50         615.0
 Nettie Königsberg GRANDPARENT          28.0            0.50          14.0
              None GRANDPARENT           0.0            0.50           0.0
     Letty Aronson  AUNT_UNCLE         666.0            0.25         166.0
       Tisa Farrow  AUNT_UNCLE         280.0            0.25          70.0
  Stephanie Farrow  AUNT_UNCLE          72.0            0.25          18.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None  AUNT_UNCLE           0.0            0.25           0.0
   Prudence Farrow  AUNT_UNCLE           0.0            0.25           0.0
      Moses Farrow     SIBLING           0.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
    Soon-Yi Previn     SIBLING          32.0            0.00           0.0
      Dylan Farrow     SIBLING          49.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
     Louise Lasser STEPSIBLING         550.0            0.00           0.0
      André Previn STEPSIBLING         827.0            0.00           0.0
     Frank Sinatra STEPSIBLING        1909.0            0.00           0.0
      Tina Sinatra STEPSIBLING          53.0            0.00           0.0
 Frank Sinatra Jr. STEPSIBLING          85.0            0.00           0.0
     Nancy Sinatra STEPSIBLING         217.0            0.00           0.0

───────────────────────────────────────────────────────
  #4 Francesca Eastwood (Q5479089)
  Nepo score (stored): 8461
  Contribution sum   : 8328
  Relatives found    : 13
  Contributing (>0)  : 2
───────────────────────────────────────────────────────
        related_name     kinship  person_point  kinship_weight  contribution
      Clint Eastwood      PARENT        6453.0             1.0        6453.0
      Frances Fisher      PARENT        1875.0             1.0        1875.0
                None GRANDPARENT           0.0             0.5           0.0
                None GRANDPARENT           0.0             0.5           0.0
Kimber Lynn Eastwood     SIBLING          39.0             0.0           0.0
     Alison Eastwood     SIBLING         423.0             0.0           0.0
       Kyle Eastwood     SIBLING         264.0             0.0           0.0
      Scott Eastwood     SIBLING         570.0             0.0           0.0
     Morgan Eastwood     SIBLING          11.0             0.0           0.0
    Kathryn Eastwood     SIBLING          26.0             0.0           0.0
                None     SIBLING           0.0             0.0           0.0
      Maggie Johnson STEPSIBLING           0.0             0.0           0.0
       Dina Eastwood STEPSIBLING          35.0             0.0           0.0

───────────────────────────────────────────────────────
  #5 Emma Roberts (Q228598)
  Nepo score (stored): 7341
  Contribution sum   : 7341
  Relatives found    : 10
  Contributing (>0)  : 3
───────────────────────────────────────────────────────
       related_name     kinship  person_point  kinship_weight  contribution
       Eric Roberts      PARENT        6779.0            1.00        6779.0
 Betty Lou Bredemus GRANDPARENT           0.0            0.50           0.0
      Julia Roberts  AUNT_UNCLE        2107.0            0.25         527.0
Lisa Roberts Gillan  AUNT_UNCLE         138.0            0.25          35.0
         Q116858049     SIBLING           0.0            0.00           0.0
               None     SIBLING           0.0            0.00           0.0
               None     SIBLING           0.0            0.00           0.0
      Kelly Nickels  STEPPARENT           0.0            0.00           0.0
      Eliza Roberts STEPSIBLING         678.0            0.00           0.0
      Keaton Simons STEPSIBLING          60.0            0.00           0.0

───────────────────────────────────────────────────────
  #6 Cora Baker (Q63649755)
  Nepo score (stored): 7316
  Contribution sum   : 7316
  Relatives found    : 1
  Contributing (>0)  : 1
───────────────────────────────────────────────────────
     related_name kinship  person_point  kinship_weight  contribution
Dee Bradley Baker  PARENT        7316.0             1.0        7316.0

───────────────────────────────────────────────────────
  #7 Shiloh Jolie (Q55430492)
  Nepo score (stored): 7273
  Contribution sum   : 7267
  Relatives found    : 19
  Contributing (>0)  : 5
───────────────────────────────────────────────────────
        related_name          kinship  person_point  kinship_weight  contribution
           Brad Pitt           PARENT        3852.0            1.00        3852.0
      Angelina Jolie           PARENT        2194.0            1.00        2194.0
          Jon Voight      GRANDPARENT        2348.0            0.50        1174.0
                None      GRANDPARENT           0.0            0.50           0.0
                None      GRANDPARENT           0.0            0.50           0.0
 Marcheline Bertrand      GRANDPARENT           0.0            0.50           0.0
         James Haven       AUNT_UNCLE          76.0            0.25          19.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
         Chip Taylor GREAT_AUNT_UNCLE         188.0            0.15          28.0
                None GREAT_AUNT_UNCLE           0.0            0.15           0.0
        Lauri Peters         RELATIVE          80.0            0.00           0.0
  Maddox Jolie-Pitt.          SIBLING           0.0            0.00           0.0
Harry James Thornton      STEPSIBLING          14.0            0.00           0.0
  Billy Bob Thornton      STEPSIBLING        2555.0            0.00           0.0
    Jennifer Aniston      STEPSIBLING        2048.0            0.00           0.0
    Jonny Lee Miller      STEPSIBLING         849.0            0.00           0.0

───────────────────────────────────────────────────────
  #8 Maddox Jolie-Pitt. (Q13147738)
  Nepo score (stored): 7273
  Contribution sum   : 7267
  Relatives found    : 19
  Contributing (>0)  : 5
───────────────────────────────────────────────────────
        related_name          kinship  person_point  kinship_weight  contribution
           Brad Pitt           PARENT        3852.0            1.00        3852.0
      Angelina Jolie           PARENT        2194.0            1.00        2194.0
          Jon Voight      GRANDPARENT        2348.0            0.50        1174.0
                None      GRANDPARENT           0.0            0.50           0.0
                None      GRANDPARENT           0.0            0.50           0.0
 Marcheline Bertrand      GRANDPARENT           0.0            0.50           0.0
         James Haven       AUNT_UNCLE          76.0            0.25          19.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
         Chip Taylor GREAT_AUNT_UNCLE         188.0            0.15          28.0
                None GREAT_AUNT_UNCLE           0.0            0.15           0.0
        Lauri Peters         RELATIVE          80.0            0.00           0.0
        Shiloh Jolie          SIBLING           0.0            0.00           0.0
Harry James Thornton      STEPSIBLING          14.0            0.00           0.0
    Jennifer Aniston      STEPSIBLING        2048.0            0.00           0.0
    Jonny Lee Miller      STEPSIBLING         849.0            0.00           0.0
  Billy Bob Thornton      STEPSIBLING        2555.0            0.00           0.0

───────────────────────────────────────────────────────
  #9 Tex Hammond (Q56686344)
  Nepo score (stored): 7066
  Contribution sum   : 7066
  Relatives found    : 4
  Contributing (>0)  : 1
───────────────────────────────────────────────────────
 related_name kinship  person_point  kinship_weight  contribution
 Grey DeLisle  PARENT        7066.0             1.0        7066.0
Murry Hammond  PARENT           0.0             1.0           0.0
         None SIBLING           0.0             0.0           0.0
         None SIBLING           0.0             0.0           0.0

───────────────────────────────────────────────────────
  #10 Weston Cage (Q4019196)
  Nepo score (stored): 6934
  Contribution sum   : 6914
  Relatives found    : 32
  Contributing (>0)  : 13
───────────────────────────────────────────────────────
        related_name          kinship  person_point  kinship_weight  contribution
        Nicolas Cage           PARENT        4595.0            1.00        4595.0
    Christina Fulton           PARENT         158.0            1.00         158.0
      August Coppola      GRANDPARENT           0.0            0.50           0.0
                None      GRANDPARENT           0.0            0.50           0.0
       Sofia Coppola       AUNT_UNCLE        2445.0            0.25         611.0
   Jason Schwartzman       AUNT_UNCLE        1661.0            0.25         415.0
       Roman Coppola       AUNT_UNCLE         475.0            0.25         119.0
  Robert Schwartzman       AUNT_UNCLE         339.0            0.25          85.0
     Carmine Coppola         ANCESTOR         335.0            0.25          84.0
 Christopher Coppola       AUNT_UNCLE         260.0            0.25          65.0
        Marc Coppola       AUNT_UNCLE          99.0            0.25          25.0
       Anton Coppola         ANCESTOR          34.0            0.25           9.0
      Italia Coppola         ANCESTOR          25.0            0.25           6.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
  Gian-Carlo Coppola       AUNT_UNCLE           0.0            0.25           0.0
Francis Ford Coppola GREAT_AUNT_UNCLE        3691.0            0.15         554.0
         Talia Shire GREAT_AUNT_UNCLE        1251.0            0.15         188.0
                None            CHILD           0.0            0.00           0.0
                None            CHILD           0.0            0.00           0.0
         Gia Coppola          SIBLING         185.0            0.00           0.0
                None          SIBLING           0.0            0.00           0.0
                None          SIBLING           0.0            0.00           0.0
          Enzo Rossi      STEPSIBLING          26.0            0.00           0.0
        Riley Keough      STEPSIBLING        1046.0            0.00           0.0
  Lisa Marie Presley      STEPSIBLING           0.0            0.00           0.0
   Patricia Arquette      STEPSIBLING        1599.0            0.00           0.0
     Benjamin Keough      STEPSIBLING           0.0            0.00           0.0
         Harlow Jane      STEPSIBLING          53.0            0.00           0.0
      Alice Kim Cage      STEPSIBLING           0.0            0.00           0.0

{'Q16217493':     person_id   person_name      kinship  gen_delta  degree raw_relationship  \
 0   Q16217493  Moses Farrow       PARENT          1       0           father
 1   Q16217493  Moses Farrow       PARENT          1       0           mother
 2   Q16217493  Moses Farrow  GRANDPARENT          2       0             None
 3   Q16217493  Moses Farrow  GRANDPARENT          2       0             None
 4   Q16217493  Moses Farrow  GRANDPARENT          2       0             None
 5   Q16217493  Moses Farrow  GRANDPARENT          2       0             None
 6   Q16217493  Moses Farrow   AUNT_UNCLE          1       1             None
 7   Q16217493  Moses Farrow   AUNT_UNCLE          1       1             None
 8   Q16217493  Moses Farrow   AUNT_UNCLE          1       1             None
 9   Q16217493  Moses Farrow     ANCESTOR          3       0             None
 10  Q16217493  Moses Farrow     ANCESTOR          3       0             None
 11  Q16217493  Moses Farrow     ANCESTOR          3       0             None
 12  Q16217493  Moses Farrow     ANCESTOR          3       0             None
 13  Q16217493  Moses Farrow     ANCESTOR          3       0             None
 14  Q16217493  Moses Farrow   AUNT_UNCLE          1       1             None
 15  Q16217493  Moses Farrow   AUNT_UNCLE          1       1             None
 16  Q16217493  Moses Farrow      SIBLING          0       1          sibling
 17  Q16217493  Moses Farrow      SIBLING          0       1          sibling
 18  Q16217493  Moses Farrow      SIBLING          0       1             None
 19  Q16217493  Moses Farrow      SIBLING          0       1             None
 20  Q16217493  Moses Farrow      SIBLING          0       1          sibling
 21  Q16217493  Moses Farrow      SIBLING          0       1             None
 22  Q16217493  Moses Farrow  STEPSIBLING          0      11             None
 23  Q16217493  Moses Farrow  STEPSIBLING          1      11             None
 24  Q16217493  Moses Farrow  STEPSIBLING          1      11             None
 25  Q16217493  Moses Farrow  STEPSIBLING          0      11             None
 26  Q16217493  Moses Farrow  STEPSIBLING          0      11             None
 27  Q16217493  Moses Farrow  STEPSIBLING          1      11             None

    related_person_id        related_name  person_point  movie_point  \
 0             Q25089         Woody Allen        6297.0       5945.0
 1            Q202725          Mia Farrow        1580.0       1537.0
 2            Q230084  Maureen O'Sullivan        1478.0       1468.0
 3            Q547495         John Farrow        1231.0       1188.0
 4         Q108223445   Nettie Königsberg          28.0         28.0
 5         Q108223439                None           0.0          0.0
 6           Q3831197       Letty Aronson         666.0        653.0
 7           Q3991790         Tisa Farrow         280.0        280.0
 8           Q7608277    Stephanie Farrow          72.0         72.0
 9          Q98700213                None           0.0          0.0
 10         Q98700266                None           0.0          0.0
 11         Q98700233                None           0.0          0.0
 12        Q108223448                None           0.0          0.0
 13         Q98700276                None           0.0          0.0
 14          Q7252957     Prudence Farrow           0.0          0.0
 15         Q18387067                None           0.0          0.0
 16        Q100135417        Dylan Farrow          49.0         49.0
 17          Q1140914      Soon-Yi Previn          32.0         32.0
 18         Q22673707                None           0.0          0.0
 19         Q22673708                None           0.0          0.0
 20          Q7365461        Ronan Farrow         165.0        125.0
 21         Q75624453                None           0.0          0.0
 22          Q1349639   Frank Sinatra Jr.          85.0         85.0
 23            Q40912       Frank Sinatra        1909.0       1696.0
 24           Q273532       Louise Lasser         550.0        550.0
 25           Q233937       Nancy Sinatra         217.0        207.0
 26           Q545438        Tina Sinatra          53.0         53.0
 27           Q155712        André Previn         827.0        711.0

     award_point  kinship_weight  contribution  person_nepo_score  \
 0         352.0            1.00        6297.0             9528.0
 1          43.0            1.00        1580.0             9528.0
 2          10.0            0.50         739.0             9528.0
 3          43.0            0.50         615.0             9528.0
 4           0.0            0.50          14.0             9528.0
 5           0.0            0.50           0.0             9528.0
 6          13.0            0.25         166.0             9528.0
 7           0.0            0.25          70.0             9528.0
 8           0.0            0.25          18.0             9528.0
 9           0.0            0.25           0.0             9528.0
 10          0.0            0.25           0.0             9528.0
 11          0.0            0.25           0.0             9528.0
 12          0.0            0.25           0.0             9528.0
 13          0.0            0.25           0.0             9528.0
 14          0.0            0.25           0.0             9528.0
 15          0.0            0.25           0.0             9528.0
 16          0.0            0.00           0.0             9528.0
 17          0.0            0.00           0.0             9528.0
 18          0.0            0.00           0.0             9528.0
 19          0.0            0.00           0.0             9528.0
 20         40.0            0.00           0.0             9528.0
 21          0.0            0.00           0.0             9528.0
 22          0.0            0.00           0.0             9528.0
 23        213.0            0.00           0.0             9528.0
 24          0.0            0.00           0.0             9528.0
 25         10.0            0.00           0.0             9528.0
 26          0.0            0.00           0.0             9528.0
 27        116.0            0.00           0.0             9528.0

     person_parent_score  person_grandparent_score  person_ancestor_score
 0                7878.0                    1368.0                    0.0
 1                7878.0                    1368.0                    0.0
 2                7878.0                    1368.0                    0.0
 3                7878.0                    1368.0                    0.0
 4                7878.0                    1368.0                    0.0
 5                7878.0                    1368.0                    0.0
 6                7878.0                    1368.0                    0.0
 7                7878.0                    1368.0                    0.0
 8                7878.0                    1368.0                    0.0
 9                7878.0                    1368.0                    0.0
 10               7878.0                    1368.0                    0.0
 11               7878.0                    1368.0                    0.0
 12               7878.0                    1368.0                    0.0
 13               7878.0                    1368.0                    0.0
 14               7878.0                    1368.0                    0.0
 15               7878.0                    1368.0                    0.0
 16               7878.0                    1368.0                    0.0
 17               7878.0                    1368.0                    0.0
 18               7878.0                    1368.0                    0.0
 19               7878.0                    1368.0                    0.0
 20               7878.0                    1368.0                    0.0
 21               7878.0                    1368.0                    0.0
 22               7878.0                    1368.0                    0.0
 23               7878.0                    1368.0                    0.0
 24               7878.0                    1368.0                    0.0
 25               7878.0                    1368.0                    0.0
 26               7878.0                    1368.0                    0.0
 27               7878.0                    1368.0                    0.0  ,
 'Q100135417':      person_id   person_name      kinship  gen_delta  degree raw_relationship  \
 0   Q100135417  Dylan Farrow       PARENT          1       0           father
 1   Q100135417  Dylan Farrow       PARENT          1       0           mother
 2   Q100135417  Dylan Farrow  GRANDPARENT          2       0             None
 3   Q100135417  Dylan Farrow  GRANDPARENT          2       0             None
 4   Q100135417  Dylan Farrow  GRANDPARENT          2       0             None
 5   Q100135417  Dylan Farrow  GRANDPARENT          2       0             None
 6   Q100135417  Dylan Farrow   AUNT_UNCLE          1       1             None
 7   Q100135417  Dylan Farrow   AUNT_UNCLE          1       1             None
 8   Q100135417  Dylan Farrow   AUNT_UNCLE          1       1             None
 9   Q100135417  Dylan Farrow     ANCESTOR          3       0             None
 10  Q100135417  Dylan Farrow     ANCESTOR          3       0             None
 11  Q100135417  Dylan Farrow     ANCESTOR          3       0             None
 12  Q100135417  Dylan Farrow     ANCESTOR          3       0             None
 13  Q100135417  Dylan Farrow     ANCESTOR          3       0             None
 14  Q100135417  Dylan Farrow   AUNT_UNCLE          1       1             None
 15  Q100135417  Dylan Farrow   AUNT_UNCLE          1       1             None
 16  Q100135417  Dylan Farrow      SIBLING          0       1             None
 17  Q100135417  Dylan Farrow      SIBLING          0       1          sibling
 18  Q100135417  Dylan Farrow      SIBLING          0       1          sibling
 19  Q100135417  Dylan Farrow      SIBLING          0       1             None
 20  Q100135417  Dylan Farrow      SIBLING          0       1          sibling
 21  Q100135417  Dylan Farrow      SIBLING          0       1             None
 22  Q100135417  Dylan Farrow  STEPSIBLING          1      11             None
 23  Q100135417  Dylan Farrow  STEPSIBLING          0      11             None
 24  Q100135417  Dylan Farrow  STEPSIBLING          0      11             None
 25  Q100135417  Dylan Farrow  STEPSIBLING          1      11             None
 26  Q100135417  Dylan Farrow  STEPSIBLING          1      11             None
 27  Q100135417  Dylan Farrow  STEPSIBLING          0      11             None

    related_person_id        related_name  person_point  movie_point  \
 0             Q25089         Woody Allen        6297.0       5945.0
 1            Q202725          Mia Farrow        1580.0       1537.0
 2            Q230084  Maureen O'Sullivan        1478.0       1468.0
 3            Q547495         John Farrow        1231.0       1188.0
 4         Q108223445   Nettie Königsberg          28.0         28.0
 5         Q108223439                None           0.0          0.0
 6           Q3831197       Letty Aronson         666.0        653.0
 7           Q3991790         Tisa Farrow         280.0        280.0
 8           Q7608277    Stephanie Farrow          72.0         72.0
 9          Q98700276                None           0.0          0.0
 10        Q108223448                None           0.0          0.0
 11         Q98700213                None           0.0          0.0
 12         Q98700233                None           0.0          0.0
 13         Q98700266                None           0.0          0.0
 14         Q18387067                None           0.0          0.0
 15          Q7252957     Prudence Farrow           0.0          0.0
 16         Q22673707                None           0.0          0.0
 17         Q16217493        Moses Farrow           0.0          0.0
 18          Q7365461        Ronan Farrow         165.0        125.0
 19         Q75624453                None           0.0          0.0
 20          Q1140914      Soon-Yi Previn          32.0         32.0
 21         Q22673708                None           0.0          0.0
 22           Q273532       Louise Lasser         550.0        550.0
 23          Q1349639   Frank Sinatra Jr.          85.0         85.0
 24           Q545438        Tina Sinatra          53.0         53.0
 25           Q155712        André Previn         827.0        711.0
 26            Q40912       Frank Sinatra        1909.0       1696.0
 27           Q233937       Nancy Sinatra         217.0        207.0

     award_point  kinship_weight  contribution  person_nepo_score  \
 0         352.0            1.00        6297.0             9524.0
 1          43.0            1.00        1580.0             9524.0
 2          10.0            0.50         739.0             9524.0
 3          43.0            0.50         615.0             9524.0
 4           0.0            0.50          14.0             9524.0
 5           0.0            0.50           0.0             9524.0
 6          13.0            0.25         166.0             9524.0
 7           0.0            0.25          70.0             9524.0
 8           0.0            0.25          18.0             9524.0
 9           0.0            0.25           0.0             9524.0
 10          0.0            0.25           0.0             9524.0
 11          0.0            0.25           0.0             9524.0
 12          0.0            0.25           0.0             9524.0
 13          0.0            0.25           0.0             9524.0
 14          0.0            0.25           0.0             9524.0
 15          0.0            0.25           0.0             9524.0
 16          0.0            0.00           0.0             9524.0
 17          0.0            0.00           0.0             9524.0
 18         40.0            0.00           0.0             9524.0
 19          0.0            0.00           0.0             9524.0
 20          0.0            0.00           0.0             9524.0
 21          0.0            0.00           0.0             9524.0
 22          0.0            0.00           0.0             9524.0
 23          0.0            0.00           0.0             9524.0
 24          0.0            0.00           0.0             9524.0
 25        116.0            0.00           0.0             9524.0
 26        213.0            0.00           0.0             9524.0
 27         10.0            0.00           0.0             9524.0

     person_parent_score  person_grandparent_score  person_ancestor_score
 0                7878.0                    1368.0                    0.0
 1                7878.0                    1368.0                    0.0
 2                7878.0                    1368.0                    0.0
 3                7878.0                    1368.0                    0.0
 4                7878.0                    1368.0                    0.0
 5                7878.0                    1368.0                    0.0
 6                7878.0                    1368.0                    0.0
 7                7878.0                    1368.0                    0.0
 8                7878.0                    1368.0                    0.0
 9                7878.0                    1368.0                    0.0
 10               7878.0                    1368.0                    0.0
 11               7878.0                    1368.0                    0.0
 12               7878.0                    1368.0                    0.0
 13               7878.0                    1368.0                    0.0
 14               7878.0                    1368.0                    0.0
 15               7878.0                    1368.0                    0.0
 16               7878.0                    1368.0                    0.0
 17               7878.0                    1368.0                    0.0
 18               7878.0                    1368.0                    0.0
 19               7878.0                    1368.0                    0.0
 20               7878.0                    1368.0                    0.0
 21               7878.0                    1368.0                    0.0
 22               7878.0                    1368.0                    0.0
 23               7878.0                    1368.0                    0.0
 24               7878.0                    1368.0                    0.0
 25               7878.0                    1368.0                    0.0
 26               7878.0                    1368.0                    0.0
 27               7878.0                    1368.0                    0.0  ,
 'Q7365461':    person_id   person_name      kinship  gen_delta  degree raw_relationship  \
 0   Q7365461  Ronan Farrow       PARENT          1       0           father
 1   Q7365461  Ronan Farrow       PARENT          1       0           mother
 2   Q7365461  Ronan Farrow  GRANDPARENT          2       0             None
 3   Q7365461  Ronan Farrow  GRANDPARENT          2       0             None
 4   Q7365461  Ronan Farrow  GRANDPARENT          2       0             None
 5   Q7365461  Ronan Farrow  GRANDPARENT          2       0             None
 6   Q7365461  Ronan Farrow   AUNT_UNCLE          1       1             None
 7   Q7365461  Ronan Farrow   AUNT_UNCLE          1       1             None
 8   Q7365461  Ronan Farrow   AUNT_UNCLE          1       1             None
 9   Q7365461  Ronan Farrow     ANCESTOR          3       0             None
 10  Q7365461  Ronan Farrow     ANCESTOR          3       0             None
 11  Q7365461  Ronan Farrow     ANCESTOR          3       0             None
 12  Q7365461  Ronan Farrow     ANCESTOR          3       0             None
 13  Q7365461  Ronan Farrow     ANCESTOR          3       0             None
 14  Q7365461  Ronan Farrow   AUNT_UNCLE          1       1             None
 15  Q7365461  Ronan Farrow   AUNT_UNCLE          1       1             None
 16  Q7365461  Ronan Farrow      SIBLING          0       1          sibling
 17  Q7365461  Ronan Farrow      SIBLING          0       1             None
 18  Q7365461  Ronan Farrow      SIBLING          0       1          sibling
 19  Q7365461  Ronan Farrow      SIBLING          0       1          sibling
 20  Q7365461  Ronan Farrow      SIBLING          0       1             None
 21  Q7365461  Ronan Farrow      SIBLING          0       1             None
 22  Q7365461  Ronan Farrow  STEPSIBLING          1      11             None
 23  Q7365461  Ronan Farrow  STEPSIBLING          1      11             None
 24  Q7365461  Ronan Farrow  STEPSIBLING          1      11             None
 25  Q7365461  Ronan Farrow  STEPSIBLING          0      11             None
 26  Q7365461  Ronan Farrow  STEPSIBLING          0      11             None
 27  Q7365461  Ronan Farrow  STEPSIBLING          0      11             None

    related_person_id        related_name  person_point  movie_point  \
 0             Q25089         Woody Allen        6297.0       5945.0
 1            Q202725          Mia Farrow        1580.0       1537.0
 2            Q230084  Maureen O'Sullivan        1478.0       1468.0
 3            Q547495         John Farrow        1231.0       1188.0
 4         Q108223445   Nettie Königsberg          28.0         28.0
 5         Q108223439                None           0.0          0.0
 6           Q3831197       Letty Aronson         666.0        653.0
 7           Q3991790         Tisa Farrow         280.0        280.0
 8           Q7608277    Stephanie Farrow          72.0         72.0
 9          Q98700276                None           0.0          0.0
 10        Q108223448                None           0.0          0.0
 11         Q98700213                None           0.0          0.0
 12         Q98700233                None           0.0          0.0

In [36]:
# Top 50
top_n_nepo_breakdown(n=50)

═══════════════════════════════════════════════════════
  TOP 50 NEPO BABIES
═══════════════════════════════════════════════════════
  [1] Moses Farrow (Q16217493) — nepo_score: 9528
  [2] Dylan Farrow (Q100135417) — nepo_score: 9524
  [3] Ronan Farrow (Q7365461) — nepo_score: 9512
  [4] Francesca Eastwood (Q5479089) — nepo_score: 8461
  [5] Emma Roberts (Q228598) — nepo_score: 7341
  [6] Cora Baker (Q63649755) — nepo_score: 7316
  [7] Maddox Jolie-Pitt. (Q13147738) — nepo_score: 7273
  [8] Shiloh Jolie (Q55430492) — nepo_score: 7273
  [9] Tex Hammond (Q56686344) — nepo_score: 7066
  [10] Weston Cage (Q4019196) — nepo_score: 6934
  [11] Morgan Eastwood (Q3323973) — nepo_score: 6650
  [12] Kathryn Eastwood (Q44573283) — nepo_score: 6613
  [13] Kimber Lynn Eastwood (Q44573288) — nepo_score: 6612
  [14] Kyle Eastwood (Q976575) — nepo_score: 6590
  [15] Alison Eastwood (Q446468) — nepo_score: 6574
  [16] Scott Eastwood (Q1320494) — nepo_score: 6559
  [17] Max Spielberg (Q29260589) — nepo_score: 6387
  [18] Brittany Bennett (Q84968132) — nepo_score: 6275
  [19] Pedro Coen (Q116858037) — nepo_score: 6248
  [20] Ireland Baldwin (Q13561648) — nepo_score: 6242
  [21] Tallulah Willis (Q22350891) — nepo_score: 6055
  [22] Rumer Willis (Q234566) — nepo_score: 6014
  [23] Miles Robbins (Q47508276) — nepo_score: 5931
  [24] Raphael De Niro (Q28001783) — nepo_score: 5852
  [25] Theo Spielberg (Q29260744) — nepo_score: 5837
  [26] Destry Spielberg (Q117265290) — nepo_score: 5834
  [27] Sasha Spielberg (Q7425114) — nepo_score: 5832
  [28] Sawyer Spielberg (Q29260395) — nepo_score: 5830
  [29] Drena De Niro (Q541821) — nepo_score: 5829
  [30] Jessica Capshaw (Q40057) — nepo_score: 5798
  [31] Evan Newman (Q56612902) — nepo_score: 5671
  [32] Julian De Niro (Q28151971) — nepo_score: 5647
  [33] Barbara Bush (Q153730) — nepo_score: 5638
  [34] Jenna Bush Hager (Q153481) — nepo_score: 5628
  [35] Calista Carradine (Q117455302) — nepo_score: 5620
  [36] Joseph Williams (Q957024) — nepo_score: 5584
  [37] Raleigh West (Q96419147) — nepo_score: 5557
  [38] Lola Sheen (Q23649931) — nepo_score: 5551
  [39] Sami Sheen (Q23649881) — nepo_score: 5551
  [40] Seraphina Affleck (Q29108594) — nepo_score: 5525
  [41] Sam Affleck (Q29108688) — nepo_score: 5525
  [42] Violet Affleck (Q29075518) — nepo_score: 5525
  [43] Levon Hawke (Q119248191) — nepo_score: 5441
  [44] Chet Hanks (Q20993895) — nepo_score: 5423
  [45] Truman Hanks (Q20993896) — nepo_score: 5423
  [46] Maya Hawke (Q46994907) — nepo_score: 5414
  [47] Ash Paulsen (Q28366461) — nepo_score: 5365
  [48] Gian-Carlo Coppola (Q155299) — nepo_score: 5362
  [49] Annie Guest (Q56234831) — nepo_score: 5318
  [50] Ruby Guest (Q43376115) — nepo_score: 5318
═══════════════════════════════════════════════════════

───────────────────────────────────────────────────────
  #1 Moses Farrow (Q16217493)
  Nepo score (stored): 9528
  Contribution sum   : 9499
  Relatives found    : 28
  Contributing (>0)  : 8
───────────────────────────────────────────────────────
      related_name     kinship  person_point  kinship_weight  contribution
       Woody Allen      PARENT        6297.0            1.00        6297.0
        Mia Farrow      PARENT        1580.0            1.00        1580.0
Maureen O'Sullivan GRANDPARENT        1478.0            0.50         739.0
       John Farrow GRANDPARENT        1231.0            0.50         615.0
 Nettie Königsberg GRANDPARENT          28.0            0.50          14.0
              None GRANDPARENT           0.0            0.50           0.0
     Letty Aronson  AUNT_UNCLE         666.0            0.25         166.0
       Tisa Farrow  AUNT_UNCLE         280.0            0.25          70.0
  Stephanie Farrow  AUNT_UNCLE          72.0            0.25          18.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
   Prudence Farrow  AUNT_UNCLE           0.0            0.25           0.0
              None  AUNT_UNCLE           0.0            0.25           0.0
      Dylan Farrow     SIBLING          49.0            0.00           0.0
    Soon-Yi Previn     SIBLING          32.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
      Ronan Farrow     SIBLING         165.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
 Frank Sinatra Jr. STEPSIBLING          85.0            0.00           0.0
     Frank Sinatra STEPSIBLING        1909.0            0.00           0.0
     Louise Lasser STEPSIBLING         550.0            0.00           0.0
     Nancy Sinatra STEPSIBLING         217.0            0.00           0.0
      Tina Sinatra STEPSIBLING          53.0            0.00           0.0
      André Previn STEPSIBLING         827.0            0.00           0.0

───────────────────────────────────────────────────────
  #2 Dylan Farrow (Q100135417)
  Nepo score (stored): 9524
  Contribution sum   : 9499
  Relatives found    : 28
  Contributing (>0)  : 8
───────────────────────────────────────────────────────
      related_name     kinship  person_point  kinship_weight  contribution
       Woody Allen      PARENT        6297.0            1.00        6297.0
        Mia Farrow      PARENT        1580.0            1.00        1580.0
Maureen O'Sullivan GRANDPARENT        1478.0            0.50         739.0
       John Farrow GRANDPARENT        1231.0            0.50         615.0
 Nettie Königsberg GRANDPARENT          28.0            0.50          14.0
              None GRANDPARENT           0.0            0.50           0.0
     Letty Aronson  AUNT_UNCLE         666.0            0.25         166.0
       Tisa Farrow  AUNT_UNCLE         280.0            0.25          70.0
  Stephanie Farrow  AUNT_UNCLE          72.0            0.25          18.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None  AUNT_UNCLE           0.0            0.25           0.0
   Prudence Farrow  AUNT_UNCLE           0.0            0.25           0.0
              None     SIBLING           0.0            0.00           0.0
      Moses Farrow     SIBLING           0.0            0.00           0.0
      Ronan Farrow     SIBLING         165.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
    Soon-Yi Previn     SIBLING          32.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
     Louise Lasser STEPSIBLING         550.0            0.00           0.0
 Frank Sinatra Jr. STEPSIBLING          85.0            0.00           0.0
      Tina Sinatra STEPSIBLING          53.0            0.00           0.0
      André Previn STEPSIBLING         827.0            0.00           0.0
     Frank Sinatra STEPSIBLING        1909.0            0.00           0.0
     Nancy Sinatra STEPSIBLING         217.0            0.00           0.0

───────────────────────────────────────────────────────
  #3 Ronan Farrow (Q7365461)
  Nepo score (stored): 9512
  Contribution sum   : 9499
  Relatives found    : 28
  Contributing (>0)  : 8
───────────────────────────────────────────────────────
      related_name     kinship  person_point  kinship_weight  contribution
       Woody Allen      PARENT        6297.0            1.00        6297.0
        Mia Farrow      PARENT        1580.0            1.00        1580.0
Maureen O'Sullivan GRANDPARENT        1478.0            0.50         739.0
       John Farrow GRANDPARENT        1231.0            0.50         615.0
 Nettie Königsberg GRANDPARENT          28.0            0.50          14.0
              None GRANDPARENT           0.0            0.50           0.0
     Letty Aronson  AUNT_UNCLE         666.0            0.25         166.0
       Tisa Farrow  AUNT_UNCLE         280.0            0.25          70.0
  Stephanie Farrow  AUNT_UNCLE          72.0            0.25          18.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None    ANCESTOR           0.0            0.25           0.0
              None  AUNT_UNCLE           0.0            0.25           0.0
   Prudence Farrow  AUNT_UNCLE           0.0            0.25           0.0
      Moses Farrow     SIBLING           0.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
    Soon-Yi Previn     SIBLING          32.0            0.00           0.0
      Dylan Farrow     SIBLING          49.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
              None     SIBLING           0.0            0.00           0.0
     Louise Lasser STEPSIBLING         550.0            0.00           0.0
      André Previn STEPSIBLING         827.0            0.00           0.0
     Frank Sinatra STEPSIBLING        1909.0            0.00           0.0
      Tina Sinatra STEPSIBLING          53.0            0.00           0.0
 Frank Sinatra Jr. STEPSIBLING          85.0            0.00           0.0
     Nancy Sinatra STEPSIBLING         217.0            0.00           0.0

───────────────────────────────────────────────────────
  #4 Francesca Eastwood (Q5479089)
  Nepo score (stored): 8461
  Contribution sum   : 8328
  Relatives found    : 13
  Contributing (>0)  : 2
───────────────────────────────────────────────────────
        related_name     kinship  person_point  kinship_weight  contribution
      Clint Eastwood      PARENT        6453.0             1.0        6453.0
      Frances Fisher      PARENT        1875.0             1.0        1875.0
                None GRANDPARENT           0.0             0.5           0.0
                None GRANDPARENT           0.0             0.5           0.0
Kimber Lynn Eastwood     SIBLING          39.0             0.0           0.0
     Alison Eastwood     SIBLING         423.0             0.0           0.0
       Kyle Eastwood     SIBLING         264.0             0.0           0.0
      Scott Eastwood     SIBLING         570.0             0.0           0.0
     Morgan Eastwood     SIBLING          11.0             0.0           0.0
    Kathryn Eastwood     SIBLING          26.0             0.0           0.0
                None     SIBLING           0.0             0.0           0.0
      Maggie Johnson STEPSIBLING           0.0             0.0           0.0
       Dina Eastwood STEPSIBLING          35.0             0.0           0.0

───────────────────────────────────────────────────────
  #5 Emma Roberts (Q228598)
  Nepo score (stored): 7341
  Contribution sum   : 7341
  Relatives found    : 10
  Contributing (>0)  : 3
───────────────────────────────────────────────────────
       related_name     kinship  person_point  kinship_weight  contribution
       Eric Roberts      PARENT        6779.0            1.00        6779.0
 Betty Lou Bredemus GRANDPARENT           0.0            0.50           0.0
      Julia Roberts  AUNT_UNCLE        2107.0            0.25         527.0
Lisa Roberts Gillan  AUNT_UNCLE         138.0            0.25          35.0
         Q116858049     SIBLING           0.0            0.00           0.0
               None     SIBLING           0.0            0.00           0.0
               None     SIBLING           0.0            0.00           0.0
      Kelly Nickels  STEPPARENT           0.0            0.00           0.0
      Eliza Roberts STEPSIBLING         678.0            0.00           0.0
      Keaton Simons STEPSIBLING          60.0            0.00           0.0

───────────────────────────────────────────────────────
  #6 Cora Baker (Q63649755)
  Nepo score (stored): 7316
  Contribution sum   : 7316
  Relatives found    : 1
  Contributing (>0)  : 1
───────────────────────────────────────────────────────
     related_name kinship  person_point  kinship_weight  contribution
Dee Bradley Baker  PARENT        7316.0             1.0        7316.0

───────────────────────────────────────────────────────
  #7 Maddox Jolie-Pitt. (Q13147738)
  Nepo score (stored): 7273
  Contribution sum   : 7267
  Relatives found    : 19
  Contributing (>0)  : 5
───────────────────────────────────────────────────────
        related_name          kinship  person_point  kinship_weight  contribution
           Brad Pitt           PARENT        3852.0            1.00        3852.0
      Angelina Jolie           PARENT        2194.0            1.00        2194.0
          Jon Voight      GRANDPARENT        2348.0            0.50        1174.0
                None      GRANDPARENT           0.0            0.50           0.0
                None      GRANDPARENT           0.0            0.50           0.0
 Marcheline Bertrand      GRANDPARENT           0.0            0.50           0.0
         James Haven       AUNT_UNCLE          76.0            0.25          19.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
         Chip Taylor GREAT_AUNT_UNCLE         188.0            0.15          28.0
                None GREAT_AUNT_UNCLE           0.0            0.15           0.0
        Lauri Peters         RELATIVE          80.0            0.00           0.0
        Shiloh Jolie          SIBLING           0.0            0.00           0.0
Harry James Thornton      STEPSIBLING          14.0            0.00           0.0
    Jennifer Aniston      STEPSIBLING        2048.0            0.00           0.0
    Jonny Lee Miller      STEPSIBLING         849.0            0.00           0.0
  Billy Bob Thornton      STEPSIBLING        2555.0            0.00           0.0

───────────────────────────────────────────────────────
  #8 Shiloh Jolie (Q55430492)
  Nepo score (stored): 7273
  Contribution sum   : 7267
  Relatives found    : 19
  Contributing (>0)  : 5
───────────────────────────────────────────────────────
        related_name          kinship  person_point  kinship_weight  contribution
           Brad Pitt           PARENT        3852.0            1.00        3852.0
      Angelina Jolie           PARENT        2194.0            1.00        2194.0
          Jon Voight      GRANDPARENT        2348.0            0.50        1174.0
                None      GRANDPARENT           0.0            0.50           0.0
                None      GRANDPARENT           0.0            0.50           0.0
 Marcheline Bertrand      GRANDPARENT           0.0            0.50           0.0
         James Haven       AUNT_UNCLE          76.0            0.25          19.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
         Chip Taylor GREAT_AUNT_UNCLE         188.0            0.15          28.0
                None GREAT_AUNT_UNCLE           0.0            0.15           0.0
        Lauri Peters         RELATIVE          80.0            0.00           0.0
  Maddox Jolie-Pitt.          SIBLING           0.0            0.00           0.0
Harry James Thornton      STEPSIBLING          14.0            0.00           0.0
  Billy Bob Thornton      STEPSIBLING        2555.0            0.00           0.0
    Jennifer Aniston      STEPSIBLING        2048.0            0.00           0.0
    Jonny Lee Miller      STEPSIBLING         849.0            0.00           0.0

───────────────────────────────────────────────────────
  #9 Tex Hammond (Q56686344)
  Nepo score (stored): 7066
  Contribution sum   : 7066
  Relatives found    : 4
  Contributing (>0)  : 1
───────────────────────────────────────────────────────
 related_name kinship  person_point  kinship_weight  contribution
 Grey DeLisle  PARENT        7066.0             1.0        7066.0
Murry Hammond  PARENT           0.0             1.0           0.0
         None SIBLING           0.0             0.0           0.0
         None SIBLING           0.0             0.0           0.0

───────────────────────────────────────────────────────
  #10 Weston Cage (Q4019196)
  Nepo score (stored): 6934
  Contribution sum   : 6914
  Relatives found    : 32
  Contributing (>0)  : 13
───────────────────────────────────────────────────────
        related_name          kinship  person_point  kinship_weight  contribution
        Nicolas Cage           PARENT        4595.0            1.00        4595.0
    Christina Fulton           PARENT         158.0            1.00         158.0
      August Coppola      GRANDPARENT           0.0            0.50           0.0
                None      GRANDPARENT           0.0            0.50           0.0
       Sofia Coppola       AUNT_UNCLE        2445.0            0.25         611.0
   Jason Schwartzman       AUNT_UNCLE        1661.0            0.25         415.0
       Roman Coppola       AUNT_UNCLE         475.0            0.25         119.0
  Robert Schwartzman       AUNT_UNCLE         339.0            0.25          85.0
     Carmine Coppola         ANCESTOR         335.0            0.25          84.0
 Christopher Coppola       AUNT_UNCLE         260.0            0.25          65.0
        Marc Coppola       AUNT_UNCLE          99.0            0.25          25.0
       Anton Coppola         ANCESTOR          34.0            0.25           9.0
      Italia Coppola         ANCESTOR          25.0            0.25           6.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
                None         ANCESTOR           0.0            0.25           0.0
  Gian-Carlo Coppola       AUNT_UNCLE           0.0            0.25           0.0
Francis Ford Coppola GREAT_AUNT_UNCLE        3691.0            0.15         554.0
         Talia Shire GREAT_AUNT_UNCLE        1251.0            0.15         188.0
                None            CHILD           0.0            0.00           0.0
                None            CHILD           0.0            0.00           0.0
         Gia Coppola          SIBLING         185.0            0.00           0.0
                None          SIBLING           0.0            0.00           0.0
                None          SIBLING           0.0            0.00           0.0
          Enzo Rossi      STEPSIBLING          26.0            0.00           0.0
        Riley Keough      STEPSIBLING        1046.0            0.00           0.0
  Lisa Marie Presley      STEPSIBLING           0.0            0.00           0.0
   Patricia Arquette      STEPSIBLING        1599.0            0.00           0.0

{'Q16217493':     person_id   person_name      kinship  gen_delta  degree raw_relationship  \
 0   Q16217493  Moses Farrow       PARENT          1       0           father
 1   Q16217493  Moses Farrow       PARENT          1       0           mother
 2   Q16217493  Moses Farrow  GRANDPARENT          2       0             None
 3   Q16217493  Moses Farrow  GRANDPARENT          2       0             None
 4   Q16217493  Moses Farrow  GRANDPARENT          2       0             None
 5   Q16217493  Moses Farrow  GRANDPARENT          2       0             None
 6   Q16217493  Moses Farrow   AUNT_UNCLE          1       1             None
 7   Q16217493  Moses Farrow   AUNT_UNCLE          1       1             None
 8   Q16217493  Moses Farrow   AUNT_UNCLE          1       1             None
 9   Q16217493  Moses Farrow     ANCESTOR          3       0             None
 10  Q16217493  Moses Farrow     ANCESTOR          3       0             None
 11  Q16217493  Moses Farrow     ANCESTOR          3       0             None
 12  Q16217493  Moses Farrow     ANCESTOR          3       0             None
 13  Q16217493  Moses Farrow     ANCESTOR          3       0             None
 14  Q16217493  Moses Farrow   AUNT_UNCLE          1       1             None
 15  Q16217493  Moses Farrow   AUNT_UNCLE          1       1             None
 16  Q16217493  Moses Farrow      SIBLING          0       1          sibling
 17  Q16217493  Moses Farrow      SIBLING          0       1          sibling
 18  Q16217493  Moses Farrow      SIBLING          0       1             None
 19  Q16217493  Moses Farrow      SIBLING          0       1             None
 20  Q16217493  Moses Farrow      SIBLING          0       1          sibling
 21  Q16217493  Moses Farrow      SIBLING          0       1             None
 22  Q16217493  Moses Farrow  STEPSIBLING          0      11             None
 23  Q16217493  Moses Farrow  STEPSIBLING          1      11             None
 24  Q16217493  Moses Farrow  STEPSIBLING          1      11             None
 25  Q16217493  Moses Farrow  STEPSIBLING          0      11             None
 26  Q16217493  Moses Farrow  STEPSIBLING          0      11             None
 27  Q16217493  Moses Farrow  STEPSIBLING          1      11             None

    related_person_id        related_name  person_point  movie_point  \
 0             Q25089         Woody Allen        6297.0       5945.0
 1            Q202725          Mia Farrow        1580.0       1537.0
 2            Q230084  Maureen O'Sullivan        1478.0       1468.0
 3            Q547495         John Farrow        1231.0       1188.0
 4         Q108223445   Nettie Königsberg          28.0         28.0
 5         Q108223439                None           0.0          0.0
 6           Q3831197       Letty Aronson         666.0        653.0
 7           Q3991790         Tisa Farrow         280.0        280.0
 8           Q7608277    Stephanie Farrow          72.0         72.0
 9          Q98700213                None           0.0          0.0
 10         Q98700266                None           0.0          0.0
 11         Q98700233                None           0.0          0.0
 12        Q108223448                None           0.0          0.0
 13         Q98700276                None           0.0          0.0
 14          Q7252957     Prudence Farrow           0.0          0.0
 15         Q18387067                None           0.0          0.0
 16        Q100135417        Dylan Farrow          49.0         49.0
 17          Q1140914      Soon-Yi Previn          32.0         32.0
 18         Q22673707                None           0.0          0.0
 19         Q22673708                None           0.0          0.0
 20          Q7365461        Ronan Farrow         165.0        125.0
 21         Q75624453                None           0.0          0.0
 22          Q1349639   Frank Sinatra Jr.          85.0         85.0
 23            Q40912       Frank Sinatra        1909.0       1696.0
 24           Q273532       Louise Lasser         550.0        550.0
 25           Q233937       Nancy Sinatra         217.0        207.0
 26           Q545438        Tina Sinatra          53.0         53.0
 27           Q155712        André Previn         827.0        711.0

     award_point  kinship_weight  contribution  person_nepo_score  \
 0         352.0            1.00        6297.0             9528.0
 1          43.0            1.00        1580.0             9528.0
 2          10.0            0.50         739.0             9528.0
 3          43.0            0.50         615.0             9528.0
 4           0.0            0.50          14.0             9528.0
 5           0.0            0.50           0.0             9528.0
 6          13.0            0.25         166.0             9528.0
 7           0.0            0.25          70.0             9528.0
 8           0.0            0.25          18.0             9528.0
 9           0.0            0.25           0.0             9528.0
 10          0.0            0.25           0.0             9528.0
 11          0.0            0.25           0.0             9528.0
 12          0.0            0.25           0.0             9528.0
 13          0.0            0.25           0.0             9528.0
 14          0.0            0.25           0.0             9528.0
 15          0.0            0.25           0.0             9528.0
 16          0.0            0.00           0.0             9528.0
 17          0.0            0.00           0.0             9528.0
 18          0.0            0.00           0.0             9528.0
 19          0.0            0.00           0.0             9528.0
 20         40.0            0.00           0.0             9528.0
 21          0.0            0.00           0.0             9528.0
 22          0.0            0.00           0.0             9528.0
 23        213.0            0.00           0.0             9528.0
 24          0.0            0.00           0.0             9528.0
 25         10.0            0.00           0.0             9528.0
 26          0.0            0.00           0.0             9528.0
 27        116.0            0.00           0.0             9528.0

     person_parent_score  person_grandparent_score  person_ancestor_score
 0                7878.0                    1368.0                    0.0
 1                7878.0                    1368.0                    0.0
 2                7878.0                    1368.0                    0.0
 3                7878.0                    1368.0                    0.0
 4                7878.0                    1368.0                    0.0
 5                7878.0                    1368.0                    0.0
 6                7878.0                    1368.0                    0.0
 7                7878.0                    1368.0                    0.0
 8                7878.0                    1368.0                    0.0
 9                7878.0                    1368.0                    0.0
 10               7878.0                    1368.0                    0.0
 11               7878.0                    1368.0                    0.0
 12               7878.0                    1368.0                    0.0
 13               7878.0                    1368.0                    0.0
 14               7878.0                    1368.0                    0.0
 15               7878.0                    1368.0                    0.0
 16               7878.0                    1368.0                    0.0
 17               7878.0                    1368.0                    0.0
 18               7878.0                    1368.0                    0.0
 19               7878.0                    1368.0                    0.0
 20               7878.0                    1368.0                    0.0
 21               7878.0                    1368.0                    0.0
 22               7878.0                    1368.0                    0.0
 23               7878.0                    1368.0                    0.0
 24               7878.0                    1368.0                    0.0
 25               7878.0                    1368.0                    0.0
 26               7878.0                    1368.0                    0.0
 27               7878.0                    1368.0                    0.0  ,
 'Q100135417':      person_id   person_name      kinship  gen_delta  degree raw_relationship  \
 0   Q100135417  Dylan Farrow       PARENT          1       0           father
 1   Q100135417  Dylan Farrow       PARENT          1       0           mother
 2   Q100135417  Dylan Farrow  GRANDPARENT          2       0             None
 3   Q100135417  Dylan Farrow  GRANDPARENT          2       0             None
 4   Q100135417  Dylan Farrow  GRANDPARENT          2       0             None
 5   Q100135417  Dylan Farrow  GRANDPARENT          2       0             None
 6   Q100135417  Dylan Farrow   AUNT_UNCLE          1       1             None
 7   Q100135417  Dylan Farrow   AUNT_UNCLE          1       1             None
 8   Q100135417  Dylan Farrow   AUNT_UNCLE          1       1             None
 9   Q100135417  Dylan Farrow     ANCESTOR          3       0             None
 10  Q100135417  Dylan Farrow     ANCESTOR          3       0             None
 11  Q100135417  Dylan Farrow     ANCESTOR          3       0             None
 12  Q100135417  Dylan Farrow     ANCESTOR          3       0             None
 13  Q100135417  Dylan Farrow     ANCESTOR          3       0             None
 14  Q100135417  Dylan Farrow   AUNT_UNCLE          1       1             None
 15  Q100135417  Dylan Farrow   AUNT_UNCLE          1       1             None
 16  Q100135417  Dylan Farrow      SIBLING          0       1             None
 17  Q100135417  Dylan Farrow      SIBLING          0       1          sibling
 18  Q100135417  Dylan Farrow      SIBLING          0       1          sibling
 19  Q100135417  Dylan Farrow      SIBLING          0       1             None
 20  Q100135417  Dylan Farrow      SIBLING          0       1          sibling
 21  Q100135417  Dylan Farrow      SIBLING          0       1             None
 22  Q100135417  Dylan Farrow  STEPSIBLING          1      11             None
 23  Q100135417  Dylan Farrow  STEPSIBLING          0      11             None
 24  Q100135417  Dylan Farrow  STEPSIBLING          0      11             None
 25  Q100135417  Dylan Farrow  STEPSIBLING          1      11             None
 26  Q100135417  Dylan Farrow  STEPSIBLING          1      11             None
 27  Q100135417  Dylan Farrow  STEPSIBLING          0      11             None

    related_person_id        related_name  person_point  movie_point  \
 0             Q25089         Woody Allen        6297.0       5945.0
 1            Q202725          Mia Farrow        1580.0       1537.0
 2            Q230084  Maureen O'Sullivan        1478.0       1468.0
 3            Q547495         John Farrow        1231.0       1188.0
 4         Q108223445   Nettie Königsberg          28.0         28.0
 5         Q108223439                None           0.0          0.0
 6           Q3831197       Letty Aronson         666.0        653.0
 7           Q3991790         Tisa Farrow         280.0        280.0
 8           Q7608277    Stephanie Farrow          72.0         72.0
 9          Q98700276                None           0.0          0.0
 10        Q108223448                None           0.0          0.0
 11         Q98700213                None           0.0          0.0
 12         Q98700233                None           0.0          0.0
 13         Q98700266                None           0.0          0.0
 14         Q18387067                None           0.0          0.0
 15          Q7252957     Prudence Farrow           0.0          0.0
 16         Q22673707                None           0.0          0.0
 17         Q16217493        Moses Farrow           0.0          0.0
 18          Q7365461        Ronan Farrow         165.0        125.0
 19         Q75624453                None           0.0          0.0
 20          Q1140914      Soon-Yi Previn          32.0         32.0
 21         Q22673708                None           0.0          0.0
 22           Q273532       Louise Lasser         550.0        550.0
 23          Q1349639   Frank Sinatra Jr.          85.0         85.0
 24           Q545438        Tina Sinatra          53.0         53.0
 25           Q155712        André Previn         827.0        711.0
 26            Q40912       Frank Sinatra        1909.0       1696.0
 27           Q233937       Nancy Sinatra         217.0        207.0

     award_point  kinship_weight  contribution  person_nepo_score  \
 0         352.0            1.00        6297.0             9524.0
 1          43.0            1.00        1580.0             9524.0
 2          10.0            0.50         739.0             9524.0
 3          43.0            0.50         615.0             9524.0
 4           0.0            0.50          14.0             9524.0
 5           0.0            0.50           0.0             9524.0
 6          13.0            0.25         166.0             9524.0
 7           0.0            0.25          70.0             9524.0
 8           0.0            0.25          18.0             9524.0
 9           0.0            0.25           0.0             9524.0
 10          0.0            0.25           0.0             9524.0
 11          0.0            0.25           0.0             9524.0
 12          0.0            0.25           0.0             9524.0
 13          0.0            0.25           0.0             9524.0
 14          0.0            0.25           0.0             9524.0
 15          0.0            0.25           0.0             9524.0
 16          0.0            0.00           0.0             9524.0
 17          0.0            0.00           0.0             9524.0
 18         40.0            0.00           0.0             9524.0
 19          0.0            0.00           0.0             9524.0
 20          0.0            0.00           0.0             9524.0
 21          0.0            0.00           0.0             9524.0
 22          0.0            0.00           0.0             9524.0
 23          0.0            0.00           0.0             9524.0
 24          0.0            0.00           0.0             9524.0
 25        116.0            0.00           0.0             9524.0
 26        213.0            0.00           0.0             9524.0
 27         10.0            0.00           0.0             9524.0

     person_parent_score  person_grandparent_score  person_ancestor_score
 0                7878.0                    1368.0                    0.0
 1                7878.0                    1368.0                    0.0
 2                7878.0                    1368.0                    0.0
 3                7878.0                    1368.0                    0.0
 4                7878.0                    1368.0                    0.0
 5                7878.0                    1368.0                    0.0
 6                7878.0                    1368.0                    0.0
 7                7878.0                    1368.0                    0.0
 8                7878.0                    1368.0                    0.0
 9                7878.0                    1368.0                    0.0
 10               7878.0                    1368.0                    0.0
 11               7878.0                    1368.0                    0.0
 12               7878.0                    1368.0                    0.0
 13               7878.0                    1368.0                    0.0
 14               7878.0                    1368.0                    0.0
 15               7878.0                    1368.0                    0.0
 16               7878.0                    1368.0                    0.0
 17               7878.0                    1368.0                    0.0
 18               7878.0                    1368.0                    0.0
 19               7878.0                    1368.0                    0.0
 20               7878.0                    1368.0                    0.0
 21               7878.0                    1368.0                    0.0
 22               7878.0                    1368.0                    0.0
 23               7878.0                    1368.0                    0.0
 24               7878.0                    1368.0                    0.0
 25               7878.0                    1368.0                    0.0
 26               7878.0                    1368.0                    0.0
 27               7878.0                    1368.0                    0.0  ,
 'Q7365461':    person_id   person_name      kinship  gen_delta  degree raw_relationship  \
 0   Q7365461  Ronan Farrow       PARENT          1       0           father
 1   Q7365461  Ronan Farrow       PARENT          1       0           mother
 2   Q7365461  Ronan Farrow  GRANDPARENT          2       0             None
 3   Q7365461  Ronan Farrow  GRANDPARENT          2       0             None
 4   Q7365461  Ronan Farrow  GRANDPARENT          2       0             None
 5   Q7365461  Ronan Farrow  GRANDPARENT          2       0             None
 6   Q7365461  Ronan Farrow   AUNT_UNCLE          1       1             None
 7   Q7365461  Ronan Farrow   AUNT_UNCLE          1       1             None
 8   Q7365461  Ronan Farrow   AUNT_UNCLE          1       1             None
 9   Q7365461  Ronan Farrow     ANCESTOR          3       0             None
 10  Q7365461  Ronan Farrow     ANCESTOR          3       0             None
 11  Q7365461  Ronan Farrow     ANCESTOR          3       0             None
 12  Q7365461  Ronan Farrow     ANCESTOR          3       0             None
 13  Q7365461  Ronan Farrow     ANCESTOR          3       0             None
 14  Q7365461  Ronan Farrow   AUNT_UNCLE          1       1             None
 15  Q7365461  Ronan Farrow   AUNT_UNCLE          1       1             None
 16  Q7365461  Ronan Farrow      SIBLING          0       1          sibling
 17  Q7365461  Ronan Farrow      SIBLING          0       1             None
 18  Q7365461  Ronan Farrow      SIBLING          0       1          sibling
 19  Q7365461  Ronan Farrow      SIBLING          0       1          sibling
 20  Q7365461  Ronan Farrow      SIBLING          0       1             None
 21  Q7365461  Ronan Farrow      SIBLING          0       1             None
 22  Q7365461  Ronan Farrow  STEPSIBLING          1      11             None
 23  Q7365461  Ronan Farrow  STEPSIBLING          1      11             None
 24  Q7365461  Ronan Farrow  STEPSIBLING          1      11             None
 25  Q7365461  Ronan Farrow  STEPSIBLING          0      11             None
 26  Q7365461  Ronan Farrow  STEPSIBLING          0      11             None
 27  Q7365461  Ronan Farrow  STEPSIBLING          0      11             None

    related_person_id        related_name  person_point  movie_point  \
 0             Q25089         Woody Allen        6297.0       5945.0
 1            Q202725          Mia Farrow        1580.0       1537.0
 2            Q230084  Maureen O'Sullivan        1478.0       1468.0
 3            Q547495         John Farrow        1231.0       1188.0
 4         Q108223445   Nettie Königsberg          28.0         28.0
 5         Q108223439                None           0.0          0.0
 6           Q3831197       Letty Aronson         666.0        653.0
 7           Q3991790         Tisa Farrow         280.0        280.0
 8           Q7608277    Stephanie Farrow          72.0         72.0
 9          Q98700276                None           0.0          0.0
 10        Q108223448                None           0.0          0.0
 11         Q98700213                None           0.0          0.0
 12         Q98700233                None           0.0          0.0